### ISSUE TITLE
cinterop: relative path to headers

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1032]
Test repository: https://github.com/msink/kotlin-pi

Here I build my own static library ```build/pi.a```
Library is ok, I can use it in clang.

But citerop don't see it:
```
headers = pi.h
compilerOpts = -I../c
staticLibraries = pi.a 
libraryPath = ../../../build
```
```
...
Exception in thread "main" java.lang.IllegalStateException: Could not find 'pi.a' binary in neither of []
...
```
Are realative paths supported here, and relative to what?

**Comment by alexander-gorshenev** [comment]
`libraryPaths` should actually be plural in `.def` file.  But singular on the command line.

**Comment by msink** [comment]
Well, now
```
Exception in thread "main" java.lang.IllegalStateException: Could not find 'pi.a' binary in neither of [../../../build]
```

**Comment by alexander-gorshenev** [comment]
The relative path should be relative to the working directory of the tool invocation. If you use gradle you can use `-i` flag to check out the tool invocations and their working directories.

**Comment by msink** [comment]
With this gradle not complains:
```
headers = pi.h
compilerOpts = -Isrc/main/c
staticLibraries = pi.a 
libraryPaths = build
```
Now complains clang:
```
C:\Users\appveyor\.konan\dependencies/msys2-mingw-w64-x86_64-gcc-6.3.0-clang-llvm-3.9.1-windows-x86-64/bin/clang -Isrc/main/c -target x86_64-w64-mingw32 -isystem C:\Users\appveyor\.konan\dependencies/msys2-mingw-w64-x86_64-gcc-6.3.0-clang-llvm-3.9.1-windows-x86-64/lib/clang/3.9.1/include --sysroot=C:\Users\appveyor\.konan\dependencies/msys2-mingw-w64-x86_64-gcc-6.3.0-clang-llvm-3.9.1-windows-x86-64 -BC:\Users\appveyor\.konan\dependencies/msys2-mingw-w64-x86_64-gcc-6.3.0-clang-llvm-3.9.1-windows-x86-64/bin -emit-llvm -c C:\projects\kotlin-pi\build\konan\libs\mingw\pi.klib-build\natives\cstubs.c -o C:\projects\kotlin-pi\build\konan\libs\mingw\pi.klib-build\natives\cstubs.bc
C:\projects\kotlin-pi\build\konan\libs\mingw\pi.klib-build\natives\cstubs.c:2:10: fatal error: 'pi.h' file not found
#include <pi.h>
         ^
1 error generated.
Exception in thread "main" java.lang.Error: Process finished with non-zero exit code: 1
```

**Comment by msink** [comment]
Well, as workaround include path can be converted to absolute in build.gradle:
```
konanArtifacts {
    ...
    interop('pi') {
        includeDirs "${System.getProperty("user.dir")}/src/main/c"
    }
   ...
```
But relative paths still broken.

**Comment by norman784** [comment]
How to setup relative paths in make file?

**Comment by martmists-gh** [comment]
Relative paths seem to have broken when a change was made to use tempdirs to build:
bs2b.def: 
```
headers = ./libraries/bs2b/src/bs2b.h
package = bs2b
compilerOpts.linux = -I./libraries/bs2b/build/lib/main/release
linkerOpts.linux = -L./libraries/bs2b/build/lib/main/release -l bs2b
```
error:
```
Exception in thread "main" java.lang.Error: /tmp/17745428244578165402.c:1:10: fatal error: './libraries/bs2b/src/bs2b.h' file not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1003)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:992)
	at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:91)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:268)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:76)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:60)
```
