### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by PradeepPappuAto** [JetBrains/kotlin-native#1155]
Running tests after build produces

**./gradlew backend.native:tests:run**

> Task :backend.native:generateCompilerProto 
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.

> Task :backend.native:renamePackage UP-TO-DATE
A problem was found with the configuration of task ':backend.native:renamePackage'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - Cannot write to file '/Users/pappu/Desktop/Workspace/github/kotlin-native/backend.native/build/renamed' specified for property '$1' as it is a directory.

> Task :backend.native:macbookStdlib UP-TO-DATE
A problem was found with the configuration of task ':backend.native:macbookStdlib'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - Cannot write to file '/Users/pappu/Desktop/Workspace/github/kotlin-native/runtime/build/macbookStdlib' specified for property '$1' as it is a directory.

> Task :backend.native:tests:buildKonanTests FAILED
exception: java.lang.UnsupportedOperationException
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
        at org.jetbrains.kotlin.konan.file.FileKt.zipFileSystem(File.kt:172)
        at org.jetbrains.kotlin.konan.file.FileKt.zipFileSystem$default(File.kt:168)
        at org.jetbrains.kotlin.konan.file.FileKt.zipPath(File.kt:181)
        at org.jetbrains.kotlin.konan.file.FileKt.getAsZipRoot(File.kt:184)
        at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary$libDir$2.invoke(KonanLibrary.kt:37)
        at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary$libDir$2.invoke(KonanLibrary.kt:24)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary.getLibDir(KonanLibrary.kt)
        at org.jetbrains.kotlin.backend.konan.library.KonanLibraryLayout$DefaultImpls.getTargetsDir(KonanLibrary.kt:33)
        at org.jetbrains.kotlin.backend.konan.library.KonanLibrary$DefaultImpls.getTargetsDir(KonanLibrary.kt)
        at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary.getTargetsDir(KonanLibrary.kt:24)
        at org.jetbrains.kotlin.backend.konan.library.impl.LibraryReaderImpl.<init>(KonanLibraryReaderImpl.kt:53)
        at org.jetbrains.kotlin.backend.konan.library.SearchPathResolverKt.resolveImmediateLibraries(SearchPathResolver.kt:55)
        at org.jetbrains.kotlin.backend.konan.KonanConfig$immediateLibraries$2.invoke(KonanConfig.kt:92)
        at org.jetbrains.kotlin.backend.konan.KonanConfig$immediateLibraries$2.invoke(KonanConfig.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.getImmediateLibraries$backend_native_compiler(KonanConfig.kt)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.loadLibMetadata(KonanConfig.kt:128)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:110)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:52)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:159)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:161)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend.native:tests:buildKonanTests'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
65 actionable tasks: 6 executed, 59 up-to-date

**Comment by PradeepPappuAto** [comment]
Once you blow away the local repo and recreate it. It works fine from there on.
