### ISSUE TITLE
Issue with dynamic library generation

### ISSUE THREAD

**Issue by kyonifer** [JetBrains/kotlin-native#1169]
I was testing out the new dynamic library generation support in 0.5 by trying to get koma to build with it. Adding [this commit](https://github.com/kyonifer/koma/commit/ba846e82ce1b1d44148ae4c72aa1467ac7f723ed) and running the following command (note that i had to add `konan.home` and download k/n 0.5 manually, because by default I get [this error](https://travis-ci.org/kyonifer/koma/jobs/318694953#L662) ):

```
 ./gradlew build -Ptarget=native -Pkonan.home=kotlin-native-linux-0.5
```

yields

```
exception: kotlin.KotlinNullPointerException
        at org.jetbrains.kotlin.backend.konan.ExportedElement.addUsedTypes(CAdapterGenerator.kt:282)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.defineUsedTypesImpl(CAdapterGenerator.kt:410)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.defineUsedTypesImpl(CAdapterGenerator.kt:413)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.defineUsedTypes(CAdapterGenerator.kt:419)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.makeGlobalStruct(CAdapterGenerator.kt:455)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.visitModuleFragment(CAdapterGenerator.kt:353)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.visitModuleFragment(CAdapterGenerator.kt:293)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.visitModuleFragment(CAdapterGenerator.kt:293)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:43)
...
```

I was going to try and debug further and figure out why TypeUtils is returning a null, but currently compiling k/native from source is giving me a jvm segfault.

**Comment by olonho** [comment]
Looks like a problem with bridge generation. Could you please share the source code that produced such a problem?

**Comment by kyonifer** [comment]
You should be able to reproduce by cloning koma and typing the command above, i.e.

```
git clone -b feature/dynamic https://github.com/kyonifer/koma.git && cd koma && ./gradlew build -Ptarget=native -Pkonan.home=/path/to/kotlin-native-linux-0.5
```

reproduces for me.

**Comment by alexander-gorshenev** [comment]
Thanks for the report, we were able to reproduce the issue. We will be back to you when a fix will be available.

**Comment by olonho** [comment]
Some problems were fixed with https://github.com/JetBrains/kotlin-native/commit/a05688351a40bfb2ca8e648f442d5960d9146aca however there are few more, which require somewhat fundamental changes to the way, how reverse C bindings are generated.

**Comment by olonho** [comment]
More fixes in https://github.com/JetBrains/kotlin-native/pull/1197. Along with hack like this
`--- a/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/StaticData.kt
+++ b/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/StaticData.kt
@@ -39,7 +39,8 @@ internal class StaticData(override val context: Context): ContextUtils {
             ): LLVMValueRef {
 
                 if (isExported && LLVMGetNamedGlobal(module, name) != null) {
-                    throw IllegalArgumentException("Global '$name' already exists")
+                    if (!name.startsWith("ktypew:"))
+                        throw IllegalArgumentException("Global '$name' already exists")
                 }
 
                 // Globals created with this API are *not* thread local.
`
it seems to compile for me.

**Comment by kyonifer** [comment]
I checked out the `fix_koma2` branch and tried to build koma against the resulting `dist` folder, which yields:

```kotlin
$ ./gradlew compileKonanLibkoma -Ptarget=native -Pkonan.home=~/builds/kotlin-native/dist
<snip>
!llvm.ident = !{!0}
!llvm.module.flags = !{!1}

!0 = !{!"clang version 5.0.0 (tags/RELEASE_500/final)"}
!1 = !{i32 1, !"wchar_size", i32 4}
error: compilation failed: Invalid module

 * Source files: annotations_js.kt, annotations_jvm.kt, builders.kt, constants.kt, creators.kt, extensionfuncs.kt, Matrix.kt, MatrixFactory.kt, MatrixTypes.kt, DoubleFactoryBase.kt, DoubleMatrixBase.kt, MatrixBase.kt, matrixfuncs.kt, misc.kt, NDArray.kt, NumericalNDArray.kt, NumericalNDArrayFactory.kt, NDArrayFactoryBase.kt, DefaultNDArray.kt, operators.kt, options.kt, scalarfuncs.kt, unsigned.kt, conversion.kt, test.kt, DefaultDoubleMatrix.kt, DefaultDoubleMatrixFactory.kt, DefaultFloatMatrix.kt, DefaultFloatMatrixFactory.kt, DefaultIntMatrix.kt, DefaultIntMatrixFactory.kt, DefaultLongMatrix.kt, DefaultLongMatrixFactory.kt, DefaultDoubleNDArray.kt, DefaultFloatNDArray.kt, DefaultIntNDArray.kt, DefaultLongNDArray.kt, factories.kt, rand.kt, repr.kt, signum.kt, hacks.kt, assert.kt, collections.kt, constructors.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: DYNAMIC

exception: java.lang.Error: Invalid module
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule(IrToBitcode.kt:117)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule$default(IrToBitcode.kt:108)
        at org.jetbrains.kotlin.backend.konan.Context.verifyBitCode(Context.kt:309)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:98)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:87)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)

:compileKonanLibkomaLinux FAILED
```

kotlin-native `dist` folder was populated by running `./gradlew dependencies:update && ./gradlew dist distPlatformLibs`.

**Comment by kyonifer** [comment]
Just tested against 82ad179 and the build succeeds now. Thanks!
