### ISSUE TITLE
IllegalStateException while generating Dynamic Library when using Extension Methods

### ISSUE THREAD

**Issue by JosephCatrambone** [JetBrains/kotlin-native#1172]
Smallest reproducible code:

```
fun test() {
	val a = 10.toByte()
	val b = 20.toByte()
	val c = a.xor(b)
	println(c)
}

fun Byte.xor(v: Byte): Byte = ((this.toInt() and 0xFF) xor (v.toInt() and 0xFF)).toByte()
```

Compile with `konanc -p dynamic src/sample.kt -o sample`

Expected output: a library.

Actual output:
```
D:\Source\cpu_x1>konanc -p dynamic src/main/kotlin/io/xoana/cpu_x1/sample.kt -o cpu_x1
KtFile: sample.kt
Produced dynamic library API in cpu_x1_api.h
C:\Users\Jo\AppData\Local\Temp\api7810504448997040257.cpp:29:25: error: expected member name or ';' after declaration specifiers
      cpu_x1_KByte (*xor)(cpu_x1_KByte thiz, cpu_x1_KByte v);
      ~~~~~~~~~~~~      ^
C:\Users\Jo\AppData\Local\Temp\api7810504448997040257.cpp:104:19: error: excess elements in struct initializer
      /* xor = */ _konan_function_1_impl,
                  ^~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
exception: java.lang.IllegalStateException: The C:\Users\Jo\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64/bin/clang++ command returned non-zero exit code: 1.
        at org.jetbrains.kotlin.konan.exec.ExecuteCommandKt.runTool(ExecuteCommand.kt:44)
        at org.jetbrains.kotlin.konan.exec.ExecuteCommandKt.runTool(ExecuteCommand.kt:40)
        at org.jetbrains.kotlin.backend.konan.CAdapterCompileKt.produceCAdapterBitcode(CAdapterCompile.kt:25)
        at org.jetbrains.kotlin.backend.konan.CompilerOutputKt.produceOutput(CompilerOutput.kt:47)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:95)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:116)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:136)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:93)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:116)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:136)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:87)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:159)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:161)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)
```

Kotlinc version: info: kotlinc-native 1.2.20-dev-773 (JRE 1.8.0_51-b16)

**Comment by olonho** [comment]
xor is C keyword, which cannot be used for names. For now use eor or similar name, way may add some mangling in the future.

**Comment by JosephCatrambone** [comment]
Thanks!  I wish I'd have thought of that.  Will give it a try.
