### ISSUE TITLE
 iOS sample KtFile: Parser.kt exception: java.lang.Error: No such file or directory

### ISSUE THREAD

**Issue by lempere** [JetBrains/kotlin-native#1184]
I try to run multiple times the **./gradlew dist distPlatformLibs** with the last commits but I can't get rid of this not found exception.

Is more likely not found any component of the architecture (iphone_sim) than the Parser.kt file.

Stack of the error:
> exception: java.lang.Error: No such file or directory
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmUtilsKt.parseBitcodeFile(LlvmUtils.kt:266)
	at org.jetbrains.kotlin.backend.konan.llvm.Runtime.<init>(Runtime.kt:30)
	at org.jetbrains.kotlin.backend.konan.llvm.Llvm.<init>(ContextUtils.kt:366)
	at org.jetbrains.kotlin.backend.konan.Context.setLlvmModule(Context.kt:222)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:65)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:94)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:93)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:87)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:60)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:173)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:164)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:166)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:178)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)

**Comment by olonho** [comment]
You're compiling for cross-target (i.e. iOS) while only built the host libraries. Please use 
   ./gradlew cross_dist 
or 
  ./gradlew bundle 
to build everything you need.

**Comment by olonho** [comment]
Closing, please reopen if still an issue.
