### ISSUE TITLE
Cannot compile to linux target on macOS

### ISSUE THREAD

**Issue by jiasir** [JetBrains/kotlin-native#1191]
My kotlin-native compiler was up-to-date and cannot compile to linux target on macOS:
```
$ kotlinc main.kt -target linux -o main
exception: java.lang.IllegalStateException: Target LINUX is not available on the MACBOOK host
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:49)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:58)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)
```

And here is my `build.gradle` file:
```
buildscript {
    ext.kotlin_version = '1.2.10'

    repositories {
        mavenCentral()
        maven {
            url  "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:+"
    }
}

apply plugin: 'konan'
apply plugin: 'idea'

konan.targets = ['macbook', 'linux']

konanArtifacts {
    program('scavenger')
}
```

The gradle build output has the following warrning:
```
The target is not enabled on the current host: linux
```

**Comment by StefMa** [comment]
Isn't it clear that you can't compile to Linux on a macOS host? 🤔

**Comment by jiasir** [comment]
@StefMa I wanna build my project to  a linux binary on my macOS system and how to? ths!

**Comment by olonho** [comment]
Not all cross-compilation host/target pairs are supported, see https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md for details.

**Comment by StefMa** [comment]
If you haven't access to a Linux machine you can create a Docker image,
mount your project and let the image build your app...

**Comment by jiasir** [comment]
Golang can be cross-platform compiler, such as I can compile Linux binary or Android binary on my macOS. Does Kotlin support cross-platform compilation in the future? I think Kotlin's Native future must be very strong! Kotlin is very advantageous!
