### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by desertjim** [JetBrains/kotlin-native#1205]
I'm trying to use IOKit, and started by using the CSVParser sample in CLion new project option.  This section of code is causing problems:

    memScoped {
        var kr: kern_return_t? = null
        val masterPort = alloc<mach_port_tVar>()
        IOMasterPort(MACH_PORT_NULL, masterPort.ptr)
    }
Producing the following error:

```
Undefined symbols for architecture x86_64:
  "_dt_compile_sugar", referenced from:
      _platform_osx_kniBridge437 in combined16726039968316199687.o
ld: symbol(s) not found for architecture x86_64
exception: java.lang.IllegalStateException: The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
	at org.jetbrains.kotlin.konan.exec.ExecuteCommandKt.runTool(ExecuteCommand.kt:44)
	at org.jetbrains.kotlin.backend.konan.Command.execute(LinkStage.kt:84)
	at org.jetbrains.kotlin.backend.konan.MacOSBasedPlatform$linkCommand$1.execute(LinkStage.kt:138)
	at org.jetbrains.kotlin.backend.konan.LinkStage.link(LinkStage.kt:426)
	at org.jetbrains.kotlin.backend.konan.LinkStage.access$link(LinkStage.kt:283)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$3.invoke(LinkStage.kt:498)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$3.invoke(LinkStage.kt:283)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:497)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:106)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:105)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:159)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:161)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)
```

What am I doing wrong?

**Comment by olonho** [comment]
We will take a look on that deeper once back from vacations.

**Comment by desertjim** [comment]
@olonho thanks!

**Comment by olonho** [comment]
Following sample compiles just fine for me:

```import platform.IOKit.*
import platform.osx.*
import kotlinx.cinterop.*

fun main(args: Array<String>) = memScoped {
    var kr: kern_return_t? = null
    val masterPort = alloc<mach_port_tVar>()
    IOMasterPort(MACH_PORT_NULL, masterPort.ptr)
    Unit
}
```
Could you please provide more details on your OS and compiler version. Did you try to update to XCode 9.2?

**Comment by desertjim** [comment]
I'm using OS X: 10.13.2

How do I check for the version of the compiler (I don't recall setting this when going through the Clion wizard)?

Xcode is definitely on version 9.2

**Comment by olonho** [comment]
Could you please try `./bin/konanc file.kt` from the CLI with the file above to see if it works.

**Comment by desertjim** [comment]
Since I'm using Clion I found the path to konanc and did the following:

/Users/jim/.konan/kotlin-native-macos-0.5/bin/konanc file.kt 
KtFile: file.kt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.text.StringFactory (file:/Users/jim/.konan/kotlin-native-macos-0.5/konan/lib/kotlin-compiler.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
file.kt:6:9: warning: variable 'kr' is never used
    var kr: kern_return_t? = null
        ^
That appears to work.

**Comment by olonho** [comment]
That's strange, if it works from CLI, it likely shall work from IDE as well (it uses the same compiler).

**Comment by olonho** [comment]
OK, no more info closing the issue, please reopen if more info will be available. Ensure that JDK8 is installed, BTW, as this message you cite is coming from Java 9, while K/N only supports Java 8.
