### ISSUE TITLE
Running kotlin-native in CLion does not work with the hello world example

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/kotlin-native#1206]
I got an error about the target. The list of candidate targets was not readable because the corresponding toString method was not overriden.

So I specified the target by changing CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.8)

set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/KotlinCMakeModule)
set(KONANC_TARGET wasm32)

project(untitled Kotlin)

konanc_executable(
        NAME HelloWorld
        SOURCES hello.kt
        TARGET wasm32
)
```
Now trying to build the project I get:

```
/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Users/federico/CLionProjects/untitled/cmake-build-debug --target HelloWorld.wasm -- -j 4
[ 33%] Generating CMakeFiles/HelloWorld_TEMP.wasm
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (374.1 MiB/374.1 MiB). Done.
Extracting dependency: /Users/federico/.konan/cache/clang-llvm-5.0.0-darwin-macos.tar.gz into /Users/federico/.konan/dependencies
Downloading dependency: https://download.jetbrains.com/kotlin/native/target-sysroot-2-wasm.tar.gz (2.7 MiB/2.7 MiB). Done.
Extracting dependency: /Users/federico/.konan/cache/target-sysroot-2-wasm.tar.gz into /Users/federico/.konan/dependencies
Downloading dependency: https://download.jetbrains.com/kotlin/native/target-toolchain-2-osx-wasm.tar.gz (48.2 MiB/48.2 MiB). Done.
Extracting dependency: /Users/federico/.konan/cache/target-toolchain-2-osx-wasm.tar.gz into /Users/federico/.konan/dependencies
exception: java.lang.IllegalStateException: target-toolchain-1-osx is not available; candidates:
org.jetbrains.kotlin.konan.util.DependencySource$Remote$Internal@3caa4757
Local(path=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.<init>(DependencyProcessor.kt:231)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.<init>(DependencyProcessor.kt:99)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.<init>(DependencyProcessor.kt:130)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.<init>(DependencyProcessor.kt:119)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.<init>(DependencyProcessor.kt:119)
	at org.jetbrains.kotlin.konan.properties.KonanProperties.<init>(KonanProperties.kt:86)
	at org.jetbrains.kotlin.konan.target.ClangManager.<init>(ClangManager.kt:25)
	at org.jetbrains.kotlin.konan.target.TargetClang.<init>(ClangManager.kt:52)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:67)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:52)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:159)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:161)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)

make[3]: *** [CMakeFiles/HelloWorld_TEMP.wasm] Error 2
make[2]: *** [CMakeFiles/HelloWorld.compile.dir/all] Error 2
make[1]: *** [CMakeFiles/HelloWorld.wasm.dir/rule] Error 2
make: *** [HelloWorld.wasm] Error 2
```

**Comment by olonho** [comment]
Did you installed xcode 9.2 as requested in documentation?

**Comment by ftomassetti** [comment]
I do not think I saw that documentation. Have you a pointer?

I have used Kotlin Native before (without CLion and targeting mac osx, not wasm). I read [this](https://blog.jetbrains.com/kotlin/2017/11/kotlinnative-ide-support-preview/) which simply state "CLion will automatically download and install native packages on your computer as needed."

Which procedure should I follow to install it? Simply use the App Store or there is a command to install xcode essentials from the command line?

**Comment by StefMa** [comment]
@ftomassetti 
You can simply install Xcode from the App Store.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md#compatibility-and-features

**Comment by ftomassetti** [comment]
I confirm that the issue was due to the missing Xcode. Sorry about that!
