### ISSUE TITLE
kotlinc : llvm-lto: error: Linking globals named 'Konan_main': symbol multiply defined!

### ISSUE THREAD

**Issue by JosephCatrambone** [JetBrains/kotlin-native#1207]
After a fresh pull of master (commit 2e07b3f52f99b51d353a8c0e53bdf9fff86988e0), I build and run kotlin-native with the instructions provided in the README (full clean + rebuild with dependency update and gradlew bundle).  I then use kotlinc to try to build the following 'simple.kt' file:

```
fun main(args: Array<String>) {
        println("Hello")
}
```

Works okay on kotlinc-jvm 1.1.50 (JRE 1.8.0_45-b14), but on kotlinc-native 1.2-SNAPSHOT (JRE 1.8.0_111-b14) / Kotlin/Native: EAP 0.6.0.0 I see the following:

```
jo@Hilbert:/tmp$ kotlinc simple.kt
llvm-lto: error: Linking globals named 'Konan_main': symbol multiply defined!
error: compilation failed: The /home/jo/.konan/dependencies/clang-llvm-5.0.0-linux-x86-64/bin/llvm-lto command returned non-zero exit code: 1.

 * Source files: simple.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: PROGRAM

exception: org.jetbrains.kotlin.backend.konan.KonanExternalToolFailure: The /home/jo/.konan/dependencies/clang-llvm-5.0.0-linux-x86-64/bin/llvm-lto command returned non-zero exit code: 1.
        at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:471)
        at org.jetbrains.kotlin.backend.konan.LinkStage.llvmLto(LinkStage.kt:328)
        at org.jetbrains.kotlin.backend.konan.LinkStage.access$llvmLto(LinkStage.kt:283)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$2.invoke(LinkStage.kt:494)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$2.invoke(LinkStage.kt:283)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:489)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:106)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:105)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)
```

Other machine info: Linux Hilbert 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by olonho** [comment]
Maybe `clean` target did't clean everything. Please try the fresh tree.
