### ISSUE TITLE
Can't compile/run kotrix (built-in example with CLion plugin)

### ISSUE THREAD

**Issue by ypujante** [JetBrains/kotlin-native#1249]
I am using the latest version of CLIon (2017.3.2). I am using the latest version of the Kotlin Native plugin (0.1-dev-86).

In CLion, I simply do: Create New Project and select the kotrix example.

There are 2 issues:
1) compilation fails with this error message:
```
Undefined symbols for architecture x86_64:
  "_fmemopen", referenced from:
      _platform_posix_kniBridge803 in combined6902239869988965878.o
  "_futimens", referenced from:
      _platform_posix_kniBridge78 in combined6902239869988965878.o
  "_mkdtempat_np", referenced from:
      _platform_posix_kniBridge221 in combined6902239869988965878.o
  "_mkostempsat_np", referenced from:
      _platform_posix_kniBridge223 in combined6902239869988965878.o
  "_mkstempsat_np", referenced from:
      _platform_posix_kniBridge222 in combined6902239869988965878.o
  "_open_memstream", referenced from:
      _platform_posix_kniBridge804 in combined6902239869988965878.o
  "_open_wmemstream", referenced from:
      _platform_posix_kniBridge1239 in combined6902239869988965878.o
  "_setattrlistat", referenced from:
      _platform_posix_kniBridge102 in combined6902239869988965878.o
  "_timingsafe_bcmp", referenced from:
      _platform_posix_kniBridge487 in combined6902239869988965878.o
  "_utimensat", referenced from:
      _platform_posix_kniBridge79 in combined6902239869988965878.o
ld: symbol(s) not found for architecture x86_64

```

2. CLion does not recognize sdl types, like `SDL_Window` or `SDL_Renderer` and mark them red (unresolved references). Note that there is a file `cmake-build-debug/CMakeFiles/libs/sdl2.klib-build/kotlin/sdl2/sdl2.kt` which was generated so it seems that SDL is properly installed...

**Comment by olonho** [comment]
Could you please download binary distribution of v0.5 from https://github.com/JetBrains/kotlin-native/releases/tag/v0.5 and test sample from there.

**Comment by ypujante** [comment]
I am not sure I see a CLion plugin in the binary distribution. Am I missing something?

**Comment by olonho** [comment]
Please use command line build on samples/tetris (same example).

**Comment by ypujante** [comment]
It is failing before reaching compilation:

```
> cinterop -def /Volumes/Vault/tmp/src/kotlin-native-macos-0.5/samples/tetris/src/main/c_interop/sdl.def -compilerOpts -I/usr/local/include/SDL2 -target macbook -o /Volumes/Vault/tmp/src/kotlin-native-macos-0.5/samples/tetris/build/c_interop/sdl
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at org.jetbrains.kotlin.konan.file.FileKt.zipFileSystem(File.kt:172)
	at org.jetbrains.kotlin.konan.file.FileKt.zipFileSystem$default(File.kt:168)
	at org.jetbrains.kotlin.konan.file.FileKt.zipPath(File.kt:181)
	at org.jetbrains.kotlin.konan.file.FileKt.getAsZipRoot(File.kt:184)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary$libDir$2.invoke(KonanLibrary.kt:37)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary$libDir$2.invoke(KonanLibrary.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary.getLibDir(KonanLibrary.kt)
	at org.jetbrains.kotlin.backend.konan.library.KonanLibraryLayout$DefaultImpls.getTargetsDir(KonanLibrary.kt:34)
	at org.jetbrains.kotlin.backend.konan.library.KonanLibrary$DefaultImpls.getTargetsDir(KonanLibrary.kt)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary.getTargetsDir(KonanLibrary.kt:24)
	at org.jetbrains.kotlin.backend.konan.library.impl.LibraryReaderImpl.<init>(KonanLibraryReaderImpl.kt:53)
	at org.jetbrains.kotlin.backend.konan.library.SearchPathResolverKt.resolveImmediateLibraries(SearchPathResolver.kt:55)
	at org.jetbrains.kotlin.backend.konan.library.SearchPathResolverKt.resolveLibrariesRecursive(SearchPathResolver.kt:122)
	at org.jetbrains.kotlin.backend.konan.library.SearchPathResolverKt.resolveLibrariesRecursive$default(SearchPathResolver.kt:121)
	at org.jetbrains.kotlin.cli.utilities.MainKt.invokeCinterop(main.kt:68)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:117)

```

**Comment by olonho** [comment]
Probably it's your JDK version, could ypu please try Oracle's JDK. There were some reports regarding issues with Zulu.

**Comment by PavelPunegov** [comment]
Regarding the 1st issue: I tried the same version of CLion and Zulu JDK 8.23 and it works both with cmake and cinterop itself. @ypujante Try to cleanup your project dir and`${HOME}/.konan/`

**Comment by ypujante** [comment]
@PavelPunegov I did what you suggested (I completely recreated an empty project instead of cleaning the project dir) and got the same error:

```
/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Volumes/Vault/tmp/misc-projects/kotrix2/cmake-build-debug --target kotrix.kexe -- -j 4
Scanning dependencies of target sdl2
[ 33%] Generating CMakeFiles/libs/sdl2.klib
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-macos.tar.gz (27.6 kiB/27.6 kiB). Done.
Extracting dependency: /Users/ypujante/.konan/cache/libffi-3.2.1-2-darwin-macos.tar.gz into /Users/ypujante/.konan/dependencies
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (374.1 MiB/374.1 MiB). Done.
Extracting dependency: /Users/ypujante/.konan/cache/clang-llvm-5.0.0-darwin-macos.tar.gz into /Users/ypujante/.konan/dependencies
KtFile: sdl2.kt
[ 33%] Built target sdl2
Scanning dependencies of target kotrix.compile
[ 66%] Generating CMakeFiles/kotrix_TEMP.kexe
KtFile: SDL_Visualizer.kt
KtFile: main.kt
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_fmemopen", referenced from:
      _platform_posix_kniBridge803 in combined6696126078668668079.o
  "_futimens", referenced from:
      _platform_posix_kniBridge78 in combined6696126078668668079.o
  "_mkdtempat_np", referenced from:
      _platform_posix_kniBridge221 in combined6696126078668668079.o
  "_mkostempsat_np", referenced from:
      _platform_posix_kniBridge223 in combined6696126078668668079.o
  "_mkstempsat_np", referenced from:
      _platform_posix_kniBridge222 in combined6696126078668668079.o
  "_open_memstream", referenced from:
      _platform_posix_kniBridge804 in combined6696126078668668079.o
  "_open_wmemstream", referenced from:
      _platform_posix_kniBridge1239 in combined6696126078668668079.o
  "_setattrlistat", referenced from:
      _platform_posix_kniBridge102 in combined6696126078668668079.o
  "_timingsafe_bcmp", referenced from:
      _platform_posix_kniBridge487 in combined6696126078668668079.o
  "_utimensat", referenced from:
      _platform_posix_kniBridge79 in combined6696126078668668079.o
ld: symbol(s) not found for architecture x86_64
exception: java.lang.IllegalStateException: The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
	at org.jetbrains.kotlin.konan.exec.ExecuteCommandKt.runTool(ExecuteCommand.kt:44)
	at org.jetbrains.kotlin.backend.konan.Command.execute(LinkStage.kt:84)
	at org.jetbrains.kotlin.backend.konan.MacOSBasedPlatform$linkCommand$1.execute(LinkStage.kt:138)
	at org.jetbrains.kotlin.backend.konan.LinkStage.link(LinkStage.kt:426)
	at org.jetbrains.kotlin.backend.konan.LinkStage.access$link(LinkStage.kt:283)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$3.invoke(LinkStage.kt:498)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$3.invoke(LinkStage.kt:283)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:497)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:106)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:105)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:159)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:161)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)

make[3]: *** [CMakeFiles/kotrix_TEMP.kexe] Error 2
make[2]: *** [CMakeFiles/kotrix.compile.dir/all] Error 2
make[1]: *** [CMakeFiles/kotrix.kexe.dir/rule] Error 2
make: *** [kotrix.kexe] Error 2
```

@olonho I upgraded java to the latest oracle version (of java 8)

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

with the exact same outcome

**Comment by olonho** [comment]
What is exact version of your OS?

**Comment by ypujante** [comment]
macOS 10.11.6 (15G19009)

**Comment by olonho** [comment]
Any chance to update to 10.12 or later?

**Comment by ypujante** [comment]
Not at this time no :(

**Comment by olonho** [comment]
We will try to work around this problem with upcoming release. Problem you see appeared because platform libs were compiled against newer MacOS libc.

**Comment by ypujante** [comment]
Ok. Thank you for looking into it.

**Comment by gevariya-ajit** [comment]
I am still facing this issue, @ypujante do you have any clue for a fix?

**Comment by ypujante** [comment]
I have not had the chance to try again since it was closed.
