### ISSUE TITLE
Errors/Questions - Kotlin MPP / Native 0.6

### ISSUE THREAD

**Issue by jguerinet** [JetBrains/kotlin-native#1327]
Hi, 

I have an existing multiplatform project with Java and JS modules, and jumped on the opportunity to bring Konan to the mix (I'm looking to produce a `framework` to be consumed in Swift/ObjC). I ran into a few things: 
* I use `isInitialized` ([docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/is-initialized.html)) in 2 different locations within my MPP, and it doesn't seem to be defined for Konan (unresolved reference I believe). I've temporarily commented it out now, but I'm wondering if this is something that would potentially supported in the future? I'm not sure how `lateinit` variables get mapped in Native, so this might be a tricky one. 
* I have a few custom Exceptions that override `Exception(message, throwable)` ([docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-exception/index.html)). In the docs the `Throwable` is nullable but I'm getting an error when compiling with Konan saying that Throwable cannot be null. 
* After having put in temporary solutions to the problems above, I run  into an `AssertionError` when compiling with Konan. I've posted the entire stack trace below. I looked into the code a bit but I can't figure out what may be the problem. It's looking like there's a conflict within 2 method signatures and we're asserting that both of them are exposed...? I'm not sure where to look next. 
* A final thing I noticed is that when the error is produced the following is outputted at the top: 
```
Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
```
From the 0.6 release notes it says that 1.2.20 is now supported. Is that a typo? Kotlin is set to 1.2.21 in my project, and the plugin in IntelliJ has the same version. 

Thanks for the great work! 

Julien

Exception stacktrace: 
```
exception: java.lang.AssertionError: Assertion failed
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerKt.canHaveCommonSubtype(ObjCExportNamer.kt:348)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerKt.canBeInheritedBySameClass(ObjCExportNamer.kt:380)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerKt.canHaveSameSelector(ObjCExportNamer.kt:387)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerKt.access$canHaveSameSelector(ObjCExportNamer.kt:1)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamer$methodSelectors$1.conflict(ObjCExportNamer.kt:53)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamer$methodSelectors$1.conflict(ObjCExportNamer.kt:40)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamer$Mapping.tryAssign(ObjCExportNamer.kt:319)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamer$Mapping.getOrPut(ObjCExportNamer.kt:303)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamer.getSelector(ObjCExportNamer.kt:130)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.getSelector(ObjCExportHeaderGenerator.kt:363)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.getSignature(ObjCExportHeaderGenerator.kt:376)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.getSignatures(ObjCExportHeaderGenerator.kt:356)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateMembers(ObjCExportHeaderGenerator.kt:338)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClassOrInterfaceMembers(ObjCExportHeaderGenerator.kt:299)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClass(ObjCExportHeaderGenerator.kt:288)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.access$translateClass(ObjCExportHeaderGenerator.kt:39)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$translateModule$2.invoke(ObjCExportHeaderGenerator.kt:129)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateModule(ObjCExportHeaderGenerator.kt:136)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produceObjCFramework$backend_native_compiler(ObjCExport.kt:40)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:323)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:233)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:233)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:46)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:241)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$6.invoke(IrToBitcode.kt:100)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$6.invoke(IrToBitcode.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:99)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:95)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:94)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:182)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:173)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:175)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:187)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

**Comment by olonho** [comment]
Could you please share the reference to your code, so that we can reproduce the problem above?

**Comment by olonho** [comment]
Could you check if https://github.com/JetBrains/kotlin-native/pull/1328 helps?

**Comment by olonho** [comment]
And https://github.com/JetBrains/kotlin-native/pull/1329 shall make *Exception more compatible with JVM/JS worlds.

**Comment by jguerinet** [comment]
Hi, 

Thanks for the (very) quick response. I'll check those 2 PRs out when I have some more time this evening but just by looking at the changes it looks like it'll probably fix both the exception problem and the assertion error (it looks like that assertion was taken out completely). If those 2 problems are still present after I try these out I'll create a sample project and link it here (I can't link the actual code as it's not open source). 

Thanks

**Comment by olonho** [comment]
Are your issues resolved?

**Comment by olonho** [comment]
Closing, all reported issues shall go away with 0.6.1.

**Comment by jguerinet** [comment]
Hi @olonho, 

Sorry for the lack of response, this fell off my radar. I just pulled from master and it seems that all of the above has been fixed! Thank you very much for your help.
