### ISSUE TITLE
Assertion error with primary constructor in expect declaration

### ISSUE THREAD

**Issue by Tobi29** [JetBrains/kotlin-native#1335]
Trying to compile a project with expect declarations that contain primary constructors causes an assertion error during compilation.

Compiling the following with `konanc -Xmultiplatform ?.kt` crashes:
```Kotlin
open class Foo(
    val a: Int
)

expect class Bar(
    a: Int
) : Foo

actual class Bar actual constructor(
    a: Int
) : Foo(a)

fun main(args: Array<String>) {
    val bar = Bar(1)
    println("${bar.a}")
}
```

Changing the declaration to use an ordinary constructor works as expected (funny):
```Kotlin
open class Foo(
    val a: Int
)

expect class Bar : Foo {
    constructor(a: Int)
}

actual class Bar actual constructor(
    a: Int
) : Foo(a)

fun main(args: Array<String>) {
    val bar = Bar(1)
    println("${bar.a}")
}
```

Just for completeness sake, here's the compiler output when compiling the first code snippet:
```
error: compilation failed: expect class Bar: Super class should be any: class Foo

 * Source files: testy6.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: PROGRAM

exception: java.lang.AssertionError: expect class Bar: Super class should be any: class Foo
        at org.jetbrains.kotlin.psi2ir.generators.BodyGenerator.generateSuperConstructorCall(BodyGenerator.kt:237)
        at org.jetbrains.kotlin.psi2ir.generators.BodyGenerator.generatePrimaryConstructorBody(BodyGenerator.kt:175)
        at org.jetbrains.kotlin.psi2ir.generators.FunctionGenerator.generatePrimaryConstructor(FunctionGenerator.kt:199)
        at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generatePrimaryConstructor(ClassGenerator.kt:239)
        at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass(ClassGenerator.kt:55)
        at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassOrObjectDeclaration(DeclarationGenerator.kt:69)
        at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:43)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateSingleFile(ModuleGenerator.kt:59)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateFiles(ModuleGenerator.kt:47)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateModuleFragmentWithoutDependencies(ModuleGenerator.kt:36)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateModuleFragment(ModuleGenerator.kt:30)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:49)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$2.invoke(KonanDriver.kt:75)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:66)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:182)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:173)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:175)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:187)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```
Running a build of 3dc88795d8bf2c370f52dc566d2bd095d555b404 on Arch Linux.

**Comment by olonho** [comment]
Yes, this problem is known and will be fixed in upcoming releases: https://youtrack.jetbrains.com/issue/KT-22797
