### ISSUE TITLE
Coroutine launch block declaration crashes compiler 

### ISSUE THREAD

**Issue by yatsinar** [JetBrains/kotlin-native#1342]
I'm trying to create my own naive coroutine implementation for iOS but the simple declaration written in Native (or Common) module crashes the compiler: 

```
fun launchAsync(context: CoroutineContext, block: suspend () -> Unit) {
    TODO()
}
```

With the following exception: 

```
exception: java.lang.Error: Invalid module
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule(IrToBitcode.kt:117)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule$default(IrToBitcode.kt:108)
        at org.jetbrains.kotlin.backend.konan.Context.verifyBitCode(Context.kt:313)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:99)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:182)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:173)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:175)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:187)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

Tried to declare the function above as expected in Common module and actual in Native or simply declare inside Native module: all leads to this exception.

**Comment by olonho** [comment]
Please check https://github.com/JetBrains/kotlin-native/pull/1344

**Comment by olonho** [comment]
Shall be fixed, please reopen if still reproducible.
