### ISSUE TITLE
AssertionError: Enum class expect class MyEnum should have a default constructor

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/kotlin-native#1352]
Kotlin/Native does not support `expect enum class`.

In a common module:

```kotlin
expect enum class MyEnum {
    FOO,
    BAR
}
```

In a native module:

```kotlin
actual enum class MyEnum {
    FOO,
    BAR,
    BAZ
}
```

Makes the compiler crash thusly:

```
error: compilation failed: Enum class expect class MyEnum should have a default constructor

 * Source files: test.kt, test.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: LIBRARY

exception: java.lang.AssertionError: Enum class expect class MyEnum should have a default constructor
	at org.jetbrains.kotlin.psi2ir.generators.BodyGenerator.generateEnumConstructorCallOrSuperCall(BodyGenerator.kt:301)
	at org.jetbrains.kotlin.psi2ir.generators.BodyGenerator.generateEnumEntryInitializer(BodyGenerator.kt:278)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateEnumEntry(ClassGenerator.kt:287)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateEnumEntryDeclaration(DeclarationGenerator.kt:66)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassMemberDeclaration(DeclarationGenerator.kt:60)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateMembersDeclaredInClassBody(ClassGenerator.kt:272)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass(ClassGenerator.kt:62)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassOrObjectDeclaration(DeclarationGenerator.kt:69)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:43)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateSingleFile(ModuleGenerator.kt:59)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateFiles(ModuleGenerator.kt:47)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateModuleFragmentWithoutDependencies(ModuleGenerator.kt:36)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateModuleFragment(ModuleGenerator.kt:30)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:49)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$2.invoke(KonanDriver.kt:75)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:141)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:120)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:66)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:182)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:173)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:175)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:187)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

**Comment by olonho** [comment]
Is it 0.6 or master? Iirc smth like that was fixed recently.

**Comment by SalomonBrys** [comment]
This is master.

**Comment by SalomonBrys** [comment]
Updated with this morning's master (e035ac1) as some of the line numbers have changed ;)

**Comment by olonho** [comment]
Shall work with the current master (after f78bd00e80e1a77739bed4fd6dd95c0dc140bc96)
