### ISSUE TITLE
compilation failed: GC overhead limit exceeded

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1353]
gradlew clean bundle
```
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :platformLibs:mingw-posix
warning: IMPORTANT: the library format is unstable now. It can change with any new git commit without warning!

> Task :platformLibs:compileKonanMingw-windowsMingw
error: compilation failed: GC overhead limit exceeded

 * Source files: windows.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: LIBRARY

exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
        at java.util.HashMap.putVal(HashMap.java:630)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$TypeHierarchy.findAllInheritors(Devirtualization.kt:212)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$TypeHierarchy.findAllInheritors(Devirtualization.kt:213)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$TypeHierarchy.inheritorsOf(Devirtualization.kt:218)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$ConstraintGraphBuilder.dfgNodeToConstraintNode(Devirtualization.kt:775)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$ConstraintGraphBuilder.build(Devirtualization.kt:604)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis.analyze(Devirtualization.kt:388)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization.run(Devirtualization.kt:875)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt:94)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:141)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:120)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:93)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:95)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:141)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:94)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:141)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:120)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platformLibs:compileKonanMingw-windowsMingw'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_111\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
 --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16m 30s
83 actionable tasks: 82 executed, 1 up-to-date
```

**Comment by olonho** [comment]
Try
--- a/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/KonanPhases.kt
+++ b/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/KonanPhases.kt
@@ -65,7 +65,7 @@ enum class KonanPhase(val description: String,
     /* ... ... */ BUILD_DFG("Data flow graph building"),
     /* ... ... */ SERIALIZE_DFG("Data flow graph serializing", BUILD_DFG),
     /* ... ... */ DESERIALIZE_DFG("Data flow graph deserializing"),
-    /* ... ... */ DEVIRTUALIZATION("Devirtualization", BUILD_DFG, DESERIALIZE_DFG),
+    /* ... ... */ DEVIRTUALIZATION("Devirtualization", BUILD_DFG, DESERIALIZE_DFG, enabled = false),
     /* ... ... */ ESCAPE_ANALYSIS("Escape analysis", BUILD_DFG, DESERIALIZE_DFG, enabled = false),
     /* ... ... */ CODEGEN("Code Generation"),
     /* ... ... */ BITCODE_LINKER("Bitcode linking"),

**Comment by msink** [comment]
```
--- a/platformLibs/build.gradle
+++ b/platformLibs/build.gradle
@@ -21,7 +21,7 @@ buildscript {
     }

     ext.konanHome = distDir.absolutePath
-    ext.jvmArgs = project.findProperty("platformLibsJvmArgs") ?: "-Xmx3G"
+    ext.jvmArgs = project.findProperty("platformLibsJvmArgs") ?: "-Xmx4G"
     ext.setProperty("konan.home", konanHome)
     ext.setProperty("konan.jvmArgs", jvmArgs)
 }
```
BUILD SUCCESSFUL

**Comment by olonho** [comment]
Yep, then it's just more memory hungry algorithms of devirtualizaetion.
