### ISSUE TITLE
Add Support For STM32 (no OS!)

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#1385]
Now that Kotlin Native has recently added [Thumb support](https://github.com/JetBrains/kotlin-native/pull/1305) there is a opportunity to support STM32 boards/uCs. The STM uCs are one of the most widely used uCs for embedded development, and are reasonably well established. STM provide high level APIs (the HAL) to hardware on their uCs/boards, however there is a catch. All APIs are dynamically generated at the source level by the [STM Cube tool](http://www.st.com/en/embedded-software/stm32cube-mcu-packages.html?querycriteria=productId=LN1897), which will likely be highly challenging for C interop. Also it is safe to assume that the APIs will be macro heavy, which is a standard practise when developing embedded development APIs (every last bit of performance counts).

In order to add support for STM32 Kotlin Native will need to have the following:

- A separate "bare metal" (hardware **without** an OS) target where the architecture and board/uC is specified
- Expanded macro support beyond constants (will require analysing embedded APIs for common patterns) to ensure good interop with embedded C APIs
- Improved DCE (Dead Code Elimination) if necessary
- Some Kotlin Native embedded development samples that go beyond **"Blinky"**
- General documentation for doing embedded development with Kotlin Native (using the STM32 as an example)
- Additional code inlining to improve performance for a embedded program developed using Kotlin Native if necessary

**Comment by gpowork** [comment]
Specially "General documentation for doing embedded development with Kotlin Native (using the STM32 as an example)" and how to setup environment for this kind of development.

**Comment by turbinenreiter** [comment]
I hope it's OK to use this issue for general questions regarding the embedded toolchain. Once I get this running, I will definitely provide a write-up.

Some documentation can be found here: https://github.com/JetBrains/kotlin-native/compare/embedded_md

I have been spending the day with trying to build the Zephyr example for a different board.

As far as I understand, the necessary steps are:
* add `board` to `/.konan/platforms/zephyr`
* in `build.sh` change the `BOARD` variable to `board`
* in `c_interop/platforms` add `board.def` and `board.sh`

For all the files I copied the `stm32f4_disco` files and changed them to `nucleo_f412zg`.

When I run the build script, I get the following error:

```
error: compilation failed: No such file or directory

 * Source files: nucleo_f412zg.kt
 * Compiler version info: Konan: EAP 0.6.1.0 / Kotlin: 1.2.40
 * Output kind: LIBRARY

exception: java.lang.Error: No such file or directory
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmUtilsKt.parseBitcodeFile(LlvmUtils.kt:266)
	at org.jetbrains.kotlin.backend.konan.llvm.Runtime.<init>(Runtime.kt:30)
	at org.jetbrains.kotlin.backend.konan.llvm.Llvm.<init>(ContextUtils.kt:394)
	at org.jetbrains.kotlin.backend.konan.Context.setLlvmModule(Context.kt:226)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:66)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:97)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:96)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:90)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:30)
```

This error stems from the call to `cinterop` in the `board.sh`.

My tree of `c_interop` looks like this:

```
c_interop
│   └── platforms
│       ├── build
│       │   ├── nucleo_f412zg-build
│       │   │   ├── kotlin
│       │   │   │   └── platform
│       │   │   │       └── zephyr
│       │   │   │           └── nucleo_f412zg
│       │   │   │               └── nucleo_f412zg.kt
│       │   │   ├── manifest.properties
│       │   │   └── natives
│       │   │       └── cstubs.bc
│       │   ├── stm32f4_disco-build
│       │   │   ├── kotlin
│       │   │   │   └── platform
│       │   │   │       └── zephyr
│       │   │   │           └── stm32f4_disco
│       │   │   │               └── stm32f4_disco.kt
│       │   │   ├── manifest.properties
│       │   │   └── natives
│       │   │       └── cstubs.bc
│       │   └── stm32f4_disco.klib
│       ├── nucleo_f412zg.def
│       ├── nucleo_f412zg.sh
│       ├── stm32f4_disco.bat
│       ├── stm32f4_disco.def
│       └── stm32f4_disco.sh
```

As far as I can see, the tree looks the same for both boards and `nucleo_f412zg.kt` definitely exists.

You can find a diff here: https://github.com/JetBrains/kotlin-native/compare/v0.6.1-fixes...motius:f412-example

**Comment by alexander-gorshenev** [comment]
You still need to compile the compiler for your board as of now. (That's one of the reasons the EMBEDDED.md PR is not accepted yet). 

That is, put your new target description to `.konan/platforms/zephyr` and build the compiler. The new target shall appear in `-list_targets` output.

Before messing with Zephyr app setup and configuration, the easy step is to make sure your `konanc hello.kt -target nucleo_f412zg` produces a `program.o`.

After you have the above ready, get back to `samples/zephyr` and we'll see how it works for your.

**Comment by turbinenreiter** [comment]
I hoped to get around that, since this happens on my machine ...

```
./gradlew dependencies:update --stacktrace

> Task :buildSrc:shared:compileKotlin FAILED
Caught an exception trying to connect to Kotlin Daemon
java.lang.ClassNotFoundException: com.sun.tools.javac.util.Context
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
.
.
.
e: Compiler terminated with internal error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:shared:compileKotlin'.
> Internal compiler error. See log for more details
```

I'll try to fix that an report back.

**Comment by olonho** [comment]
@turbinenreiter likely you had JRE, while you need JDK (Context class related error).

**Comment by Takhion** [comment]
Regarding the **STM Cube** support/integration: [this](https://blog.jetbrains.com/clion/2019/02/clion-2019-1-eap-clion-for-embedded-development-part-iii/#comment-91455) might be helpful...?

**Comment by sbogolepov** [comment]
We are migrating to YouTrack, so I'm closing this issue. Feel free to [open](https://kotl.in/issue) a new one on YouTrack or share your ideas in [KT-43974](https://youtrack.jetbrains.com/issue/KT-43974).
