### ISSUE TITLE
Can't run Calculator iOS

### ISSUE THREAD

**Issue by Iliasvw** [JetBrains/kotlin-native#1438]
Hello everybody

Just trying to open and run the iOS calculator app from the samples folder, but I'm not able to run it.

I do get the following error: 

:kotlin-native-gradle-plugin:processResources UP-TO-DATE
:kotlin-native-shared:compileKotlin UP-TO-DATE
:kotlin-native-shared:compileJava NO-SOURCE
:kotlin-native-shared:processResources NO-SOURCE
:kotlin-native-shared:classes UP-TO-DATE
:kotlin-native-shared:jar UP-TO-DATE
:kotlin-native-gradle-plugin:compileKotlin UP-TO-DATE
:kotlin-native-gradle-plugin:compileJava NO-SOURCE
:kotlin-native-gradle-plugin:compileGroovy NO-SOURCE
:kotlin-native-gradle-plugin:classes UP-TO-DATE
:kotlin-native-gradle-plugin:jar UP-TO-DATE
The target is not enabled on the current host: linux
Target 'linux' of artifact 'libgit2' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
Target 'linux' of artifact 'libcurl' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: raspberrypi
Target 'linux' of artifact 'sdl' is not supported on the current host
Target 'raspberrypi' of artifact 'sdl' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: raspberrypi
Target 'linux' of artifact 'tetris' is not supported on the current host
Target 'raspberrypi' of artifact 'tetris' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
Target 'linux' of artifact 'ffmpeg' is not supported on the current host
Target 'mingw' of artifact 'ffmpeg' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
Target 'linux' of artifact 'sdl' is not supported on the current host
Target 'mingw' of artifact 'sdl' is not supported on the current host
The target is not enabled on the current host: linux
The target is not enabled on the current host: mingw
Target 'linux' of artifact 'Player' is not supported on the current host
Target 'mingw' of artifact 'Player' is not supported on the current host
The target is not enabled on the current host: mingw
:calculator:checkKonanCompiler
:calculator:compileKonanKotlinArithmeticParserIos_x64error: compilation failed: No such file or directory

 * Source files: Parser.kt
 * Compiler version info: Konan: EAP 0.6.2.0 / Kotlin: 1.2.40
 * Output kind: FRAMEWORK

exception: java.lang.Error: No such file or directory
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmUtilsKt.parseBitcodeFile(LlvmUtils.kt:266)
	at org.jetbrains.kotlin.backend.konan.llvm.Runtime.<init>(Runtime.kt:30)
	at org.jetbrains.kotlin.backend.konan.llvm.Llvm.<init>(ContextUtils.kt:389)
	at org.jetbrains.kotlin.backend.konan.Context.setLlvmModule(Context.kt:239)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:64)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:97)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:96)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:90)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':calculator:compileKonanKotlinArithmeticParserIos_x64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**:calculator:compileKonanKotlinArithmeticParserIos_x64error: compilation failed: No such file or directory**: it seems that he cannot find the framework for some reason...

Any help would be welcome, 
Ilias

**Comment by Iliasvw** [comment]
I forgot to run ./build.sh, so the problem is partly fixed. The problem now is: 
/Users/ilias/Library/Developer/Xcode/DerivedData/calculator-frkhmyoxnofposctbndppjysyull/Build/Products/Debug-iphonesimulator/KotlinArithmeticParser.framework: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

It says something is wrong with the codesigning of the framework...

**Comment by ilmat192** [comment]
Looks like you've build the the compiler for macOS but not for iOS. The calculator project requires iOS to be built too. Try to build all the cross targets running `./gradlew bundle`.

Thanks for the report, keep us informed about your progress.

**Comment by olonho** [comment]
Closing as no more info, reopen if still relevant.
