### ISSUE TITLE
exception: java.net.ConnectException: Operation timed out Behind a corporate proxy

### ISSUE THREAD

**Issue by hiucimon** [JetBrains/kotlin-native#1446]
First attempt to use the Kotlin Native compiler, and it times out trying to download the LLVM/sysroot, etc... for the first time, either on the command line or in CLion. 

Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 3.0 sec and trying again (attempt: 2/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 6.0 sec and trying again (attempt: 3/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 9.0 sec and trying again (attempt: 4/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 12.0 sec and trying again (attempt: 5/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 15.0 sec and trying again (attempt: 6/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 18.0 sec and trying again (attempt: 7/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 21.0 sec and trying again (attempt: 8/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 24.0 sec and trying again (attempt: 9/10).
Cannot download a dependency: java.net.ConnectException: Operation timed out (Connection timed out)
Waiting 27.0 sec and trying again (attempt: 10/10).
exception: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:657)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.checkHTTPResponse(DependencyDownloader.kt:66)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.tryDownload(DependencyDownloader.kt:144)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.download(DependencyDownloader.kt:180)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.download$default(DependencyDownloader.kt:158)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.downloadDependency(DependencyProcessor.kt:205)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.run(DependencyProcessor.kt:269)
	at org.jetbrains.kotlin.konan.properties.KonanPropertiesLoader.downloadDependencies(KonanProperties.kt:38)
	at org.jetbrains.kotlin.konan.target.Platform.downloadDependencies(Platform.kt)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:59)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:58)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:182)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:173)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:175)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:187)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)

**Comment by olonho** [comment]
Does passing `-Dhttp.proxyHost=xxx -Dhttp.proxyPort=yyy` according to https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html to konanc args helps in your case?

**Comment by neyb** [comment]
I have the same problem... `-Dhttp.proxy` stuff does not seem to do anything. Even using `JAVA_TOOL_OPTIONS` with options does not change the error (even if a `Picked up JAVA_TOOL_OPTIONS: -Dhttp.proxyHost=xxx.xxx.xx -Dhttp.proxyPort=xxxx` is displayed)

**Comment by olonho** [comment]
Hmm, could you please try that other Java programs work with the proxy config you provide.

**Comment by olonho** [comment]
Also what is JDK version you use?

**Comment by anidotnet** [comment]
The only way it worked for my if I modify `run_konan` like this

```bash
java_opts=(-ea \
            -Djava.net.useSystemProxies=true \
            -Xmx3G \
            "-Djava.library.path=${NATIVE_LIB}" \
            "-Dkonan.home=${KONAN_HOME}" \
           -Dfile.encoding=UTF-8)
```

Or

```bash
java_opts=(-ea \
            -Dhttp.proxyHost=xxxxxxxx \
			-Dhttp.proxyPort=xxxx \
            -Xmx3G \
            "-Djava.library.path=${NATIVE_LIB}" \
            "-Dkonan.home=${KONAN_HOME}" \
           -Dfile.encoding=UTF-8)
```

My guess is gradle script or cmake script is not propagating the `-D` options to `run_konan` at all.

My system is Ubuntu 64-bit and I tried with jdk 1.8, 1.9 and 1.10.

**Comment by ilmat192** [comment]
@anidotnet Did you try with cmake build or gradle build or both of them?

**Comment by anidotnet** [comment]
Both of them. In cmake I tried to set below env variables separately (tried with each line separately):

```cmake
set(ADDITIONAL_KONANC_FLAGS "-Dhttp.proxyHost=xxxxxx -Dhttp.proxyPort=xxxxx")
set(CMAKE_Kotlin_FLAGS "-Dhttp.proxyHost=xxxxxx -Dhttp.proxyPort=xxxx")
set(JAVA_OPTS "-Dhttp.proxyHost=xxxxxx -Dhttp.proxyPort=xxxx")
konanc_executable(
        NAME Curl
        SOURCES src/kotlin/
        LIBRARIES curl_kt
        LINKER_OPTS "${CURL_LIBRARY}"
        ADDITIONAL_KONANC_FLAGS "-Dhttp.proxyHost=xxxxxx -Dhttp.proxyPort=xxxxx"
)
```
And also during gradle build I tried

```bash
./gradlew -Dhttp.proxyHost=xxxxxxxxxxx -Dhttp.proxyPort=xxxxx -Dhttps.proxyHost=xxxxxxxxxxx -Dhttps.proxyPort=xxxx clean build
```

**Comment by ilmat192** [comment]
This patch should fix the issue with the Gradle plugin: https://github.com/JetBrains/kotlin-native/pull/1466

**Comment by anidotnet** [comment]
@ilmat192 this should propagate any `-D` properties from gradle args, but what about cmake build? Can we make it to honor `JAVA_OPTS`?

**Comment by olonho** [comment]
@anidotnet we do not plan to further invest in CMake support for K/N. CLI tools like `konanc` shall support that already, so you could just modify the compiler invocation. Or you suggest to add  `JAVA_OPTS` to arguments of running Java?

**Comment by anidotnet** [comment]
I was suggesting if `run_konan` script can honor `JAVA_OPTS`. Currently it is not doing it, is it possible to add that support?

**Comment by olonho** [comment]
Yes, Gradle will be supported in CLion. https://github.com/JetBrains/kotlin-native/pull/1478

**Comment by anidotnet** [comment]
@olonho I have not tried it yet. I'll do it soon and provide feedback. Thanks for the quick fix. :)

**Comment by olonho** [comment]
Closing, please reopen if still relevant.

**Comment by Gamadril** [comment]
I have a problem with kotlin-native behind a proxy, too. When I don't provide proxy info in JAVA_OPTS, download request times out as expected. If I provide it I get HTTP 407 error back. It seems that proxy host and port are used but proxy user and password not.

```
> Task :mpp-library:compileKotlinIosArm64
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
e: org.jetbrains.kotlin.konan.util.DependencyDownloader$HTTPResponseException: Server returned HTTP response code: 407 for URL: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-3-darwin-macos.tar.gz
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.checkHTTPResponse(DependencyDownloader.kt:67)
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.tryDownload(DependencyDownloader.kt:144)
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.download(DependencyDownloader.kt:180)
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.download$default(DependencyDownloader.kt:158)
        at org.jetbrains.kotlin.konan.util.DependencyProcessor.downloadDependency(DependencyProcessor.kt:200)
        at org.jetbrains.kotlin.konan.util.DependencyProcessor.run(DependencyProcessor.kt:275)
        at org.jetbrains.kotlin.konan.properties.KonanPropertiesLoader.downloadDependencies(KonanProperties.kt:40)
        at org.jetbrains.kotlin.konan.target.Platform.downloadDependencies(Platform.kt)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:65)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:60)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:225)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:222)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:224)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :mpp-library:compileKotlinIosArm64 FAILED

FAILURE: Build failed with an exception.
```

**Comment by hiucimon** [comment]
Why am I on this email?

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 13, 2020 at 8:49 AM, Gamadril<notifications@github.com> wrote:   
I have a problem with kotlin-native behind a proxy, too. When I don't provide proxy info in JAVA_OPTS, download request times out as expected. If I provide it I get HTTP 407 error back. It seems that proxy host and port are used but proxy user and password not.
> Task :mpp-library:compileKotlinIosArm64
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
e: org.jetbrains.kotlin.konan.util.DependencyDownloader$HTTPResponseException: Server returned HTTP response code: 407 for URL: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-3-darwin-macos.tar.gz
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.checkHTTPResponse(DependencyDownloader.kt:67)
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.tryDownload(DependencyDownloader.kt:144)
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.download(DependencyDownloader.kt:180)
        at org.jetbrains.kotlin.konan.util.DependencyDownloader.download$default(DependencyDownloader.kt:158)
        at org.jetbrains.kotlin.konan.util.DependencyProcessor.downloadDependency(DependencyProcessor.kt:200)
        at org.jetbrains.kotlin.konan.util.DependencyProcessor.run(DependencyProcessor.kt:275)
        at org.jetbrains.kotlin.konan.properties.KonanPropertiesLoader.downloadDependencies(KonanProperties.kt:40)
        at org.jetbrains.kotlin.konan.target.Platform.downloadDependencies(Platform.kt)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:65)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:60)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:225)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:222)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:224)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :mpp-library:compileKotlinIosArm64 FAILED

FAILURE: Build failed with an exception.
