### ISSUE TITLE
Bitcode section not found in object file

### ISSUE THREAD

**Issue by Scellow** [JetBrains/kotlin-native#1465]
Hello

I'm trying to use GLFW and GLEW on windows, i installed them using msys2 but i'm getting this error:

(On macOS i'm using GLFW + platform.OpenGL and it works fine)

```log
C:\Users\Scellow\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\181.4445.17\bin\cmake\bin\cmake.exe --build C:\Users\Scellow\dev\libktx\cmake-build-debug --target TestGameLib -- -j 2
[ 20%] Built target glfw_kt
[ 40%] Built target glew_kt
Scanning dependencies of target TestGameLib.compile
[ 60%] Generating CMakeFiles/TestGameLib_TEMP.exe
llvm-lto: error loading file 'C:\Users\Scellow\AppData\Local\Temp\native3747329104572567415\cstubs.bc': Bitcode section not found in object file
error: compilation failed: The C:\Users\Scellow\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64/bin/llvm-lto command returned non-zero exit code: 1.

 * Source files: main.kt
 * Compiler version info: Konan: EAP 0.6.2.0 / Kotlin: 1.2.40
 * Output kind: PROGRAM

exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The C:\Users\Scellow\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64/bin/llvm-lto command returned non-zero exit code: 1.
	at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:100)
	at org.jetbrains.kotlin.konan.exec.Command.execute(ExecuteCommand.kt:66)
	at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:51)
	at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:47)
	at org.jetbrains.kotlin.backend.konan.LinkStage.llvmLto(LinkStage.kt:66)
	at org.jetbrains.kotlin.backend.konan.LinkStage.access$llvmLto(LinkStage.kt:29)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:226)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:29)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:218)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:109)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:108)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)

CMakeFiles\TestGameLib.compile.dir\build.make:59: recipe for target 'CMakeFiles/TestGameLib_TEMP.exe' failed
mingw32-make.exe[3]: *** [CMakeFiles/TestGameLib_TEMP.exe] Error 2
mingw32-make.exe[2]: *** [CMakeFiles/TestGameLib.compile.dir/all] Error 2
CMakeFiles\Makefile2:131: recipe for target 'CMakeFiles/TestGameLib.compile.dir/all' failed
CMakeFiles\Makefile2:175: recipe for target 'CMakeFiles/TestGameLib.dir/rule' failed
mingw32-make.exe[1]: *** [CMakeFiles/TestGameLib.dir/rule] Error 2
mingw32-make.exe: *** [TestGameLib] Error 2
Makefile:156: recipe for target 'TestGameLib' failed
```

```cmake
cmake_minimum_required(VERSION 3.8)

set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/KotlinCMakeModule)

project(libKTX Kotlin)

find_package(glew REQUIRED)
cinterop(
        NAME glew_kt
        DEF_FILE src/c_interop/libglew.def
        COMPILER_OPTS "-I ${GLEW_INCLUDE_DIR}"
)

find_package(glfw3 REQUIRED)
cinterop(
        NAME glfw_kt
        DEF_FILE src/c_interop/libglfw.def
        COMPILER_OPTS "-I ${GLFW_INCLUDE_DIR}"
)

konanc_executable(
        NAME TestGameLib
        SOURCES src/kotlin/main.kt
        LIBRARIES glfw_kt glew_kt
        LINKER_OPTS "-L/lib/ -lglew32 -lglfw3"
)
```

libglew.def
```def
headers = GL/glew.h
compilerOpts =
excludedFunctions =
compilerOpts.linux = -I/usr/include
compilerOpts.osx = -I/usr/local/include
```
libglfw.def
```def
headers = GLFW/glfw3.h
compilerOpts =
excludedFunctions =
compilerOpts.linux = -I/usr/include
compilerOpts.osx = -I/usr/local/include
```

**Comment by Scellow** [comment]
Maybe that's because i'm using clion on windows with this hack:

```diff
79a80,81
>         elseif (WIN32)
>             set(CINTEROP_TARGET mingw)
142a145,146
>         elseif(WIN32)
>             set(KONANC_TARGET mingw)
195a200,201
>     elseif (${KONANC_TARGET} STREQUAL "mingw")
>         set(EXECUTABLE_EXTENSION "exe")
220,223c226,229
<     add_executable(${KONANC_NAME}.${EXECUTABLE_EXTENSION} ${KONANC_SOURCES})
<     add_dependencies(${KONANC_NAME}.${EXECUTABLE_EXTENSION} ${KONANC_NAME}.compile)
<     set_target_properties(${KONANC_NAME}.${EXECUTABLE_EXTENSION} PROPERTIES LINKER_LANGUAGE Kotlin)
<     add_custom_command(TARGET ${KONANC_NAME}.${EXECUTABLE_EXTENSION}
---
>     add_executable(${KONANC_NAME} ${KONANC_SOURCES})
>     add_dependencies(${KONANC_NAME} ${KONANC_NAME}.compile)
>     set_target_properties(${KONANC_NAME} PROPERTIES LINKER_LANGUAGE Kotlin)
>     add_custom_command(TARGET ${KONANC_NAME}
```

**Comment by olonho** [comment]
Please use Gradle as a build system. CMake support is no longer being maintained.

**Comment by Scellow** [comment]
Oh i didn't know that, i'll do it with gradle then thanks, i'm closing this, i'll reopen if i get the same error
