### ISSUE TITLE
IllegalArgumentException: List has more than one element

### ISSUE THREAD

**Issue by damianw** [JetBrains/kotlin-native#1543]
I've received this exception when compiling a multiplatform project. I don't have a smaller reproducible sample at the moment, but can try to produce one if necessary.
```
error: compilation failed: List has more than one element.

 * Source files: <redacted>
 * Compiler version info: Konan: 0.7-dev / Kotlin: 1.2.50
 * Output kind: FRAMEWORK

exception: java.lang.IllegalArgumentException: List has more than one element.
        at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:474)
        at org.jetbrains.kotlin.backend.konan.optimizations.DataFlowIR$SymbolTable.mapType(DataFlowIR.kt:498)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.<init>(DFGBuilder.kt:452)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.analyze(DFGBuilder.kt:285)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFunction(DFGBuilder.kt:240)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructor(IrElementVisitorVoid.kt:55)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitConstructor(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructor(IrElementVisitorVoid.kt:56)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitConstructor(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitConstructor(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.declarations.impl.IrConstructorImpl.accept(IrConstructorImpl.kt:77)
        at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.acceptChildren(IrClassImpl.kt:84)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:245)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:231)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitDeclaration(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:43)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:79)
        at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.acceptChildren(IrClassImpl.kt:84)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:245)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:231)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitDeclaration(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:43)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:79)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:69)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:245)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:231)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitPackageFragment(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFile(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFile(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFile(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:66)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:49)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:245)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:231)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:27)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitModuleFragment(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitModuleFragment(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitModuleFragment(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:46)
        at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder.build(DFGBuilder.kt:228)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$2.invoke(IrToBitcode.kt:77)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$2.invoke(IrToBitcode.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:76)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:97)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:96)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:90)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:68)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:40)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:72)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:38)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:171)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:162)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:190)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:181)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:183)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:195)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

**Comment by olonho** [comment]
Shall be fixed with d7861e89bd291aef0279aa04b877e70827980c9a
