### ISSUE TITLE
Execution failed for task ':uikit:compileKonanAppIos_x64'

### ISSUE THREAD

**Issue by theapache64** [JetBrains/kotlin-native#1562]
When i tried to compile the `UIKit` sample. Am getting below error.

```
:uikit:compileKonanAppIos_x64exception: java.lang.UnsupportedClassVersionError: org/jetbrains/kotlin/metadata/KonanLinkData has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.kotlin.backend.konan.serialization.KonanSerializerProtocol.<init>(KonanSerializerExtension.kt:103)
	at org.jetbrains.kotlin.backend.konan.serialization.KonanSerializerProtocol.<clinit>(KonanSerializerExtension.kt:101)
	at org.jetbrains.kotlin.backend.konan.serialization.KonanSerializationUtilKt.parseModuleHeader(KonanSerializationUtil.kt:110)
	at org.jetbrains.kotlin.backend.konan.serialization.KonanSerializationUtilKt.deserializeModule(KonanSerializationUtil.kt:118)
	at org.jetbrains.kotlin.backend.konan.library.impl.LibraryReaderImpl.moduleDescriptor(KonanLibraryReaderImpl.kt:102)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$loadLibMetadata$1.invoke(KonanConfig.kt:130)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$loadLibMetadata$1.invoke(KonanConfig.kt:39)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.loadLibMetadata(KonanConfig.kt:128)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:108)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:40)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:72)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:38)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:171)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:162)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:190)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:181)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:183)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:195)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':uikit:compileKonanAppIos_x64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2```

**Comment by olonho** [comment]
Yes, it is the problem.

**Comment by theapache64** [comment]
I want to use `java8'. Is it possible to compile and run the sample projects using `java8` ?

**Comment by theapache64** [comment]
I did recompiled it with `java8` and it worked 🤣
