### ISSUE TITLE
Compiler crash in 0.7 when returning `object` from a `memScoped` block

### ISSUE THREAD

**Issue by peterholak** [JetBrains/kotlin-native#1574]
Could be related to https://github.com/JetBrains/kotlin-native/issues/1502, but possibly a different issue (0.7 was released after that one was closed).

The simplest code that triggers the crash is `memScoped { object{} }`, which causes
```
exception: java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl@2b44605c
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmDeclarations.forClass(LlvmDeclarations.kt:53)
	at org.jetbrains.kotlin.backend.konan.llvm.ContextUtils$DefaultImpls.getTypeInfoPtr(ContextUtils.kt:202)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.getTypeInfoPtr(CodeGenerator.kt:30)
	at org.jetbrains.kotlin.backend.konan.llvm.ContextUtils$DefaultImpls.getLlvmTypeInfoPtr(ContextUtils.kt:211)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.getLlvmTypeInfoPtr(CodeGenerator.kt:30)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.typeInfoValue(CodeGenerator.kt:39)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt:109)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	...
```

I also get a different exception if I try this

```kotlin
val result = memScoped {
    object { val a = 1 }
}
println(result.a)
```

Which causes

```
exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$ConstraintGraphBuilder$dfgNodeToConstraintNode$4.invoke(Devirtualization.kt:735)
	at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$ConstraintGraphBuilder.dfgNodeToConstraintNode(Devirtualization.kt:767)
	at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$ConstraintGraphBuilder.build(Devirtualization.kt:620)
	at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis.analyze(Devirtualization.kt:404)
	at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization.run(Devirtualization.kt:895)
	...
```

**Comment by olonho** [comment]
Thanks for report, reasons were identified and will be fixed soon.

**Comment by olonho** [comment]
7ded115dddb04370766d90874db7b3cddb83d2a7 shall fix that, please test.
