### ISSUE TITLE
how to use kotlin-native at an exist iOS and Android project?

### ISSUE THREAD

**Issue by zixun** [JetBrains/kotlin-native#1609]
hi,
    our ios application is write by objective-c and android application is write by java for many years, now we want to add `kotlin-native` to our applications to develop some pages，how to do it, is there any docs?

**Comment by olonho** [comment]
Also see an example application at  https://github.com/JetBrains/kotlin-native-calculator-sample

**Comment by zixun** [comment]
@olonho thx~   I create a demo project by [https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md](https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md), while i build the ios project,it print the error:

```
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (374.1 MiB/374.1 MiB). Done.
Extracting dependency: /Users/yilong/.konan/cache/clang-llvm-5.0.0-darwin-macos.tar.gz into /Users/yilong/.konan/dependencies
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator'
exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /usr/bin/xcrun command returned non-zero exit code: 1.
	at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:100)
	at org.jetbrains.kotlin.konan.exec.Command.getOutputLines(ExecuteCommand.kt:91)
	at org.jetbrains.kotlin.konan.exec.Command.getOutputLines$default(ExecuteCommand.kt:72)
	at org.jetbrains.kotlin.konan.target.CurrentXcode.xcrun(Xcode.kt:54)
	at org.jetbrains.kotlin.konan.target.CurrentXcode.getSdkPath(Xcode.kt:56)
	at org.jetbrains.kotlin.konan.target.CurrentXcode.access$getSdkPath(Xcode.kt:37)
	at org.jetbrains.kotlin.konan.target.CurrentXcode$iphonesimulatorSdk$2.invoke(Xcode.kt:46)
	at org.jetbrains.kotlin.konan.target.CurrentXcode$iphonesimulatorSdk$2.invoke(Xcode.kt:37)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:79)
	at org.jetbrains.kotlin.konan.target.CurrentXcode.getIphonesimulatorSdk(Xcode.kt)
	at org.jetbrains.kotlin.konan.target.AppleConfigurablesImpl.getAbsoluteTargetSysRoot(Apple.kt:36)
	at org.jetbrains.kotlin.konan.target.ClangArgs.getAbsoluteTargetSysRoot(ClangArgs.kt)
	at org.jetbrains.kotlin.konan.target.ClangArgs.getSpecificClangArgs(ClangArgs.kt:62)
	at org.jetbrains.kotlin.konan.target.ClangArgs.<init>(ClangArgs.kt:180)
	at org.jetbrains.kotlin.konan.target.Platform$clang$2.invoke(Platform.kt:25)
	at org.jetbrains.kotlin.konan.target.Platform$clang$2.invoke(Platform.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:79)
	at org.jetbrains.kotlin.konan.target.Platform.getClang(Platform.kt)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:63)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:58)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:72)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:38)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:171)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:162)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)


> Task :greeting:ios:compileKonanGreetingIos_x64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':greeting:ios:compileKonanGreetingIos_x64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 17s
2 actionable tasks: 2 executed
Command /bin/sh failed with exit code 1

```

**Comment by olonho** [comment]
Please install Xcode and IOS SDKs.

**Comment by zixun** [comment]
@StefMa thx, I got it. 
In my demo project create by [https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md](https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md).
I import `Greeting` by:
`#import "Greeting.h"`
but it's empty in Greeting.h file.

**Comment by StefMa** [comment]
You can checkout this PR:
https://github.com/JetBrains/kotlin-native/pull/1494

It was build on top of the documentation and works. Hope that help you with
your issue...

@olonho you should really think about a merge of it 😉 it's the third time
someone ask about it

**Comment by olonho** [comment]
@StefMa yeah, we'll try to merge that next week.
