### ISSUE TITLE
Kotlin native installation on mac error

### ISSUE THREAD

**Issue by brabo-hi** [JetBrains/kotlin-native#1628]
I downloaded kotlin-native-macos-0.7.tar.gz, 
Created the file hello.kt
i got this following error when running inside bin : konanc hello.kt

Outut
`e1z4r13p11% exception: java.io.IOException: Operation not supported
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1073)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
        at org.jetbrains.kotlin.konan.util.DependencyProcessor.run(DependencyProcessor.kt:259)
        at org.jetbrains.kotlin.konan.properties.KonanPropertiesLoader.downloadDependencies(KonanProperties.kt:38)
        at org.jetbrains.kotlin.konan.target.Platform.downloadDependencies(Platform.kt)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:65)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:40)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:72)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:38)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:171)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:162)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:190)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:181)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:183)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:195)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)   at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)`

**Comment by olonho** [comment]
Hmm, it seems you have a filesystem which doesn't support locking. What is your filesystem?

**Comment by brabo-hi** [comment]
I am on NFS, but i tried to run it on local, and got same thing

**Comment by brabo-hi** [comment]
solved after export KONAN_DATA_DIR=/some_surely_local_place
