### ISSUE TITLE
exception: kotlin.UninitializedPropertyAccessException: lateinit property parent has not been initialized

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1719]
```
exception: kotlin.UninitializedPropertyAccessException: lateinit property parent has not been initialized
        at org.jetbrains.kotlin.ir.declarations.impl.IrDeclarationBase.getParent(IrDeclarationBase.kt:32)
        at org.jetbrains.kotlin.backend.konan.lower.CallableReferenceLowering$FunctionReferenceBuilder.getFullName(CallableReferenceLowering.kt:328)
        at org.jetbrains.kotlin.backend.konan.lower.CallableReferenceLowering$FunctionReferenceBuilder.access$getFullName$p(CallableReferenceLowering.kt:160)
        at org.jetbrains.kotlin.backend.konan.lower.CallableReferenceLowering$FunctionReferenceBuilder$createConstructorBuilder$1.buildIr(CallableReferenceLowering.kt:308)
        at org.jetbrains.kotlin.backend.konan.lower.CallableReferenceLowering$FunctionReferenceBuilder$createConstructorBuilder$1.buildIr(CallableReferenceLowering.kt:262)
        at org.jetbrains.kotlin.backend.common.lower.SymbolWithIrBuilder$builtIr$2.invoke(IrBuildUtils.kt:50)
        at org.jetbrains.kotlin.backend.common.lower.SymbolWithIrBuilder$builtIr$2.invoke(IrBuildUtils.kt:40)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.backend.common.lower.SymbolWithIrBuilder.getBuiltIr(IrBuildUtils.kt)
        at org.jetbrains.kotlin.backend.common.lower.SymbolWithIrBuilder.getIr(IrBuildUtils.kt:62)
        at org.jetbrains.kotlin.backend.konan.lower.CallableReferenceLowering$FunctionReferenceBuilder.build(CallableReferenceLowering.kt:246)
...
```

Reproduces with a lambda property with receiver as part of an enum construction:
https://github.com/korlibs/korlibs/blob/a9fd6f865dd7f6274a654a3d78659d6c5fda058f/korfl/korfl/common/src/com/soywiz/korfl/AbcOpcode.kt#L273

**Comment by homuroll** [comment]
Fixed in master.
