### ISSUE TITLE
exception: java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@1f29decc

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1720]
```
exception: java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@780074b2
        at org.jetbrains.kotlin.backend.konan.llvm.LlvmDeclarations.forFunction(LlvmDeclarations.kt:50)
        at org.jetbrains.kotlin.backend.konan.llvm.ContextUtils$DefaultImpls.getLlvmFunction(ContextUtils.kt:174)
        at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.getLlvmFunction(CodeGenerator.kt:30)
        at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.llvmFunction(CodeGenerator.kt:32)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt:97)
```

Reproduced here: https://github.com/korlibs/korlibs/blob/master/korim/korim/common/src/com/soywiz/korim/font/ttf/TtfFont.kt#L134
Seems to be related to inline + callback + nullable + maybe something in the inlined bodies.

**Comment by soywiz** [comment]
Can't reproduce on `0.8-dev-2494`
