### ISSUE TITLE
Non-local callable reference to suspend lambda

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1724]
```
 * Compiler version info: Konan: 0.8-dev-2494 / Kotlin: 1.2.60
 * Output kind: PROGRAM

exception: java.lang.Error: Non-local callable reference to suspend lambda: private final suspend fun `createServer$<no name provided>$wshandler$lambda-0`(it: com.soywiz.korio.net.http.HttpServer.WsRequest): kotlin.Unit defined in com.soywiz.korio.KorioNativeDefaults[SimpleFunctionDescriptorImpl@7d8170ec]
        at org.jetbrains.kotlin.backend.konan.lower.SuspendFunctionsLowering$transformCallableReferencesToSuspendLambdas$$inlined$forEach$lambda$1.visitFunctionReference(SuspendFunctionsLowering.kt:108)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionReference(IrElementTransformerVoid.kt:180)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionReference(IrElementTransformerVoid.kt:24)
```

Reproduced here with the commented code here: https://github.com/korlibs/korlibs/blob/b582a1c693b39ed1795f598a5fcecc9a5724239d/korio/korio/common/src/com/soywiz/korio/KorioNative.kt#L229

The code compiles fine in JVM and JS. A possible workaround is to move the anonymous class outside as a plain named class.

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/kotlin-native/pull/1732.

**Comment by homuroll** [comment]
Fixed in master.
