### ISSUE TITLE
sortedBy and sortedByDescending broken in 0.8-dev-2632 : exception: java.lang.IllegalStateException: Symbol for deserialized class Comparator is unbound

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1745]
Reproduces in 0.8-dev-2632

Related to #1420?

For the stacktrace I guess it is related to inline and the class Comparator. But for this case, finding the culprit is really hard. I'm going to try to find the code that causes this by commenting files one by one and will update the issue if I have luck.

**EDIT: `It seems that sortedBy and sortedByDescending are broken in0.8-dev-2632.`**

This build should reproduce the problem: https://travis-ci.org/korlibs/korlibs/builds/398573291

```
> Task :korim-native:compileTestDebugKotlinNative FAILED
error: compilation failed: Symbol for deserialized class Comparator is unbound

 * Source files: Korim.kt, KorimVersion.kt, Bitmap.kt, Bitmap1.kt, Bitmap16.kt, Bitmap2.kt, Bitmap32.kt, Bitmap4.kt, Bitmap8.kt, BitmapChannel.kt, BitmapExt.kt, BitmapIndexed.kt, BitmapSlice.kt, NativeImage.kt, PSNR.kt, ARGB.kt, BGRA.kt, ColorFormat.kt, ColorFormat16.kt, ColorFormat24.kt, ColorFormat32.kt, ColorTransform.kt, Colors.kt, PaletteColorFormat.kt, RGB.kt, RGBA.kt, RGBA_16.kt, RGBAd.kt, RGBAf.kt, YCbCr.kt, YUVA.kt, Bitmap32Ext.kt, BitmapFont.kt, BitmapFontGenerator.kt, TtfFont.kt, BMP.kt, DDS.kt, DXT.kt, ICO.kt, ImageData.kt, ImageDecodingProps.kt, ImageEncodingProps.kt, ImageFormat.kt, ImageFormats.kt, ImageFrame.kt, ImageInfo.kt, JPEG.kt, JPEGDecoder.kt, JPEGEncoder.kt, KorioExt.kt, NativeImageFormatProvider.kt, NativeImageFormatProviderExt.kt, PNG.kt, PSD.kt, SVG.kt, StandardImageFormats.kt, TGA.kt, RectangleExt.kt, Bitmap32Context2d.kt, Context2d.kt, GraphicsPath.kt, Shape.kt, SVG.kt, Bitmap1Test.kt, Bitmap32Test.kt, Bitmap32Context2dTest.kt, ColorFormatTest.kt, RGBATest.kt, RGBAfTest.kt, DDSTest.kt, ImageFormatsTest.kt, PSDTest.kt, ShapeTest.kt, SvgTest.kt, NativeImageFormatProviderNative.kt
 * Compiler version info: Konan: 0.8-dev-2632 / Kotlin: 1.2.60
 * Output kind: PROGRAM

exception: java.lang.IllegalStateException: Symbol for deserialized class Comparator is unbound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.getOwner(IrSymbolBase.kt:42)
        at org.jetbrains.kotlin.backend.konan.irasdescriptors.IrTypeAsKotlinTypeKt.getClass(IrTypeAsKotlinType.kt:83)
        at org.jetbrains.kotlin.backend.konan.lower.Inliner.inlineFunction(FunctionInlining.kt:194)
        at org.jetbrains.kotlin.backend.konan.lower.Inliner.inline(FunctionInlining.kt:142)
        at org.jetbrains.kotlin.backend.konan.lower.FunctionInlining.visitCall(FunctionInlining.kt:94)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:163)
...
```

**Comment by soywiz** [comment]
After removing almost all the code and being super puzzled (since it failed in two places and had to start from the beginning removing all the code twice to found what's going on), I found the culprits: 

https://github.com/korlibs/korlibs/blob/6e08e2f79b76a51fde0b44edaff2ec4c468b57aa/korim/korim/common/src/com/soywiz/korim/format/ImageData.kt#L10-L17

https://github.com/korlibs/korlibs/blob/6e08e2f79b76a51fde0b44edaff2ec4c468b57aa/korim/korim/common/src/com/soywiz/korim/vector/Bitmap32Context2d.kt#L49

It seems that `sortedBy` and `sortedByDescending` are broken in` 0.8-dev-2632`.

This simple code should reproduce the problem:

```
val items = listOf(1).sortedByDescending { it }
```

In addition to fixing this, I would suggest to include instructions for compiling the gradle plugin + dependencies locally so people can check themselves easily. README.md doesn't explain how to compile the gradle plugin and use it locally.

In addition to that, I guess it would be a good idea to catch exceptions in inliner, and rethrow with an attached context for troubleshooting.

**Comment by homuroll** [comment]
Should be fixed with https://github.com/JetBrains/kotlin-native/pull/1750.

**Comment by homuroll** [comment]
Fixed in master.

**Comment by soywiz** [comment]
Is this the recommended way for testing against master?

```
export KONAN_REPO=/Users/soywiz/projects/kotlin-native
pushd $KONAN_REPO && git pull && ./gradlew dependencies:update && ./gradlew dist distPlatformLibs && popd
./gradlew :korim-native:check -Pkonan.home=$KONAN_REPO/dist --include-build $KONAN_REPO/shared --include-build $KONAN_REPO/tools/kotlin-native-gradle-plugin
```

I'm getting this error:
```
> Task :korim-native:compileTestDebugKotlinNative
Undefined symbols for architecture x86_64:
  "_private_classes_<stdlib>_kotlin.text.regex.MatchResultImpl_829", referenced from:
      _kfun:com.soywiz.korio.KorioNativeDefaults.$createServer$<no name provided>$listenInternal$lambda-5$4.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
  "_private_functions_<stdlib>_kotlin.text.regex.MatchResultImpl.<get-groupValues>#internal_1562", referenced from:
      _kfun:com.soywiz.korio.KorioNativeDefaults.$createServer$<no name provided>$listenInternal$lambda-5$4.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
ld: symbol(s) not found for architecture x86_64
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
```

But maybe I missed something

**Comment by homuroll** [comment]
Try to run `gradlew clean`.
