### ISSUE TITLE
TypeCastException: null cannot be cast to non-null type org.jetbrains.kotlin.ir.symbols.IrValueSymbol

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1777]
```
 * Compiler version info: Konan: 0.8-rc1-2712 / Kotlin: 1.2.70
 * Output kind: PROGRAM

exception: kotlin.TypeCastException: null cannot be cast to non-null type org.jetbrains.kotlin.ir.symbols.IrValueSymbol
        at org.jetbrains.kotlin.ir.util.IrUnboundSymbolReplacer.visitGetValue(IrUnboundSymbolReplacer.kt:474)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:149)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.impl.IrGetValueImpl.accept(IrGetValueImpl.kt:49)
        at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:27)
```

Reproduced here:
https://github.com/kpspemu/kpspemu/tree/knative.problem1
with `./gradlew :kpspemu-native:check`

**Comment by soywiz** [comment]
After using source files and adding some prints, I found the issue and circumvented it:
https://github.com/kpspemu/kpspemu/commit/805130337557a8bf5cde08c21bea513581d7300e#diff-9878b7bab7893488c170faa977ce1949R1177

Though in this case for the inline I'm using a lambda, and it would have a performance impact.

**Comment by olonho** [comment]
Seems problem somehow related to substitution of `value-parameter srcSize: kotlin.Int = ... ` by inliner into` setVD_VSVT`, i.e. we failed to replace parameter with its value, if the value is default one.

**Comment by homuroll** [comment]
Fixed in master.
