### ISSUE TITLE
Failed to lookup transitive dependencies

### ISSUE THREAD

**Issue by e5l** [JetBrains/kotlin-native#1782]
Failed to lookup transitive dependencies:
```
> Task :trendings-ios:compileKonanTrendingsIos_arm64 FAILED
exception: java.lang.IllegalStateException: Could not find "ktor_utils_ios" in [/Users/jetbrains/Documents/trendings, /Users/jetbrains/Documents/trendings/trendings-ios/build/konan/bin/ios_arm64, /Users/jetbrains/Documents/trendings/trendings-ios/build/konan/libs/ios_arm64, /Users/jetbrains/.gradle/caches/modules-2/files-2.1/io.ktor/ktor_client_ios_ktor_client_ios_ios_arm64/0.9.6.3/39ddb9139b497493aaafdb4efe5a036601ea9a5, /Users/jetbrains/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx_coroutines_io_native_kotlinx_coroutines_io_native_ios_arm64/1.0.37/92b0cb3c9c1666d7f82dfb3d412c6f8e4209c77f, /Users/jetbrains/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-native_kotlinx_coroutines_core_native_ios_arm64/0.23.5.native/a95f570f75555a65381c01cfdf10251077acacac, /Users/jetbrains/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx_io_native_kotlinx_io_native_ios_arm64/1.0.37/a96bb2e25d0f70afcc6c6e3a0e1a86629623abb8, /Users/jetbrains/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-native_atomicfu_native_ios_arm64/0.10.3-native/27da09fb32dc16ef75688b59ffc6a3410aac34af, /Users/jetbrains/.konan/klib, /Users/jetbrains/.konan/kotlin-native-macos-0.8-dev-2701/klib/common, /Users/jetbrains/.konan/kotlin-native-macos-0.8-dev-2701/klib/platform/ios_arm64].
        at org.jetbrains.kotlin.konan.library.KonanLibrarySearchPathResolver.resolve(SearchPathResolver.kt:78)
        at org.jetbrains.kotlin.backend.konan.library.SearchPathResolverExtensionsKt.resolveLibrariesRecursive(SearchPathResolverExtensions.kt:68)
        at org.jetbrains.kotlin.backend.konan.KonanConfig$immediateLibraries$2.invoke(KonanConfig.kt:99)
        at org.jetbrains.kotlin.backend.konan.KonanConfig$immediateLibraries$2.invoke(KonanConfig.kt:40)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.getImmediateLibraries$backend_native_compiler(KonanConfig.kt)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.loadLibMetadata(KonanConfig.kt:127)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:109)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:62)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:42)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:95)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:66)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:34)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:171)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:197)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:188)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:190)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:202)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

To reproduce:
1. clone https://github.com/e5l/trendings-app/tree/0c522d7c95072bd7ce127ca4ba23369206307f73
2. ./gradlew clean compileKonan

Fixed by adding all transitive dependencies by hand.

**Comment by ilmat192** [comment]
Closed since the `konan` plugin is outdated.
