### ISSUE TITLE
Error:compilation failed: null

### ISSUE THREAD

**Issue by chinacharis** [JetBrains/kotlin-native#1798]
Information:Building target 'testsdk' for architecture 'arm64' using 'iOS 11.4' sdk
Information:Running script 'Compile Kotlin/Native'
> Configure project :
feature GRADLE_METADATA is not enabled: publication is disabled
> Task :checkKonanCompiler
> Task :compileKonanTestsdkIos_arm64
Error:compilation failed: null
 * Source files: KotlinNativeFramework.kt, Base64.kt, UcSTARSystem.kt
 * Compiler version info: Konan: 0.8 / Kotlin: 1.2.70
 * Output kind: FRAMEWORK
exception: kotlin.KotlinNullPointerException
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.getNode(DFGBuilder.kt:545)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.expressionToEdge(DFGBuilder.kt:539)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.getNode(DFGBuilder.kt:616)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.expressionToEdge(DFGBuilder.kt:539)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.getNode(DFGBuilder.kt:616)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.expressionToEdge(DFGBuilder.kt:539)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.getNode(DFGBuilder.kt:616)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$FunctionDFGBuilder.build(DFGBuilder.kt:504)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.analyze(DFGBuilder.kt:318)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitConstructor(DFGBuilder.kt:262)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructor(IrElementVisitorVoid.kt:56)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitConstructor(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitConstructor(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.declarations.impl.IrConstructorImpl.accept(IrConstructorImpl.kt:90)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.acceptChildren(IrClassImpl.kt:105)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:250)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitDeclaration(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:43)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:100)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.acceptChildren(IrClassImpl.kt:105)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:250)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitDeclaration(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:43)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitClass(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:100)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:79)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:250)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitPackageFragment(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFile(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFile(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitFile(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:76)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:49)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitElement(DFGBuilder.kt:250)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:27)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitModuleFragment(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitModuleFragment(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder$build$1.visitModuleFragment(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:46)
	at org.jetbrains.kotlin.backend.konan.optimizations.ModuleDFGBuilder.build(DFGBuilder.kt:247)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$2.invoke(IrToBitcode.kt:77)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$2.invoke(IrToBitcode.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:76)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:97)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:96)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:90)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:75)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:42)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:95)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:66)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:34)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:171)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:197)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:188)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:190)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:202)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
> Task :compileKonanTestsdkIos_arm64 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileKonanTestsdkIos_arm64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 15s
2 actionable tasks: 2 executed
Error:Build failed in 16 s 643 ms

[归档.zip](https://github.com/JetBrains/kotlin-native/files/2190977/default.zip)

**Comment by olonho** [comment]
Please provide minimal sample leading to the crash.

**Comment by chinacharis** [comment]
I create a ios framwork project with appcode 182.3684.8, source files only Base64.kt and UcSTARSystem.kt,  crash when build the project, see attachment files, you can not download them?

**Comment by chinacharis** [comment]
[attachment.zip](https://github.com/JetBrains/kotlin-native/files/2191537/attachment.zip)
upload again

**Comment by chinacharis** [comment]
I separate internal class Decoder and Encoder from Base64, it is ok, please fix this bug as soon as possible
