### ISSUE TITLE
java.lang.UnsupportedOperationException 	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem

### ISSUE THREAD

**Issue by jblorenzo** [JetBrains/kotlin-native#1889]
I've seen reports of this before but i cannot make it work on my machine:

Mac OS 10.14 Beta (18A336e)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
XCode 9.4.1

> Task :shared:buildSrc:compileKotlin UP-TO-DATE
> Task :shared:buildSrc:compileJava NO-SOURCE
> Task :shared:buildSrc:compileGroovy NO-SOURCE
> Task :shared:buildSrc:processResources NO-SOURCE
> Task :shared:buildSrc:classes UP-TO-DATE
> Task :shared:buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :shared:buildSrc:jar UP-TO-DATE
> Task :shared:buildSrc:assemble UP-TO-DATE
> Task :shared:buildSrc:compileTestKotlin NO-SOURCE
> Task :shared:buildSrc:compileTestJava NO-SOURCE
> Task :shared:buildSrc:compileTestGroovy NO-SOURCE
> Task :shared:buildSrc:processTestResources NO-SOURCE
> Task :shared:buildSrc:testClasses UP-TO-DATE
> Task :shared:buildSrc:test NO-SOURCE
> Task :shared:buildSrc:check UP-TO-DATE
> Task :shared:buildSrc:build UP-TO-DATE
> Task :kotlin-native-shared:generateCompilerVersion UP-TO-DATE
> Task :kotlin-native-shared:compileKotlin UP-TO-DATE
> Task :kotlin-native-shared:compileJava NO-SOURCE
> Task :kotlin-native-shared:processResources NO-SOURCE
> Task :kotlin-native-shared:classes UP-TO-DATE
> Task :kotlin-native-shared:inspectClassesForKotlinIC UP-TO-DATE
> Task :kotlin-native-shared:jar UP-TO-DATE
> Task :kotlin-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :kotlin-native-gradle-plugin:compileJava NO-SOURCE
> Task :kotlin-native-gradle-plugin:compileGroovy NO-SOURCE
> Task :kotlin-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :kotlin-native-gradle-plugin:processResources UP-TO-DATE
> Task :kotlin-native-gradle-plugin:classes UP-TO-DATE
> Task :kotlin-native-gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :kotlin-native-gradle-plugin:jar UP-TO-DATE
> Task :kotlin-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :kotlin-native-gradle-plugin:compileJava NO-SOURCE
> Task :kotlin-native-gradle-plugin:compileGroovy NO-SOURCE
> Task :kotlin-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :kotlin-native-gradle-plugin:processResources UP-TO-DATE
> Task :kotlin-native-gradle-plugin:classes UP-TO-DATE
> Task :kotlin-native-gradle-plugin:shadowJar UP-TO-DATE

> Configure project :ios
feature GRADLE_METADATA is not enabled: publication is disabled

> Task :ios:checkKonanCompiler

> Task :ios:compileKonanKotlinArithmeticParserIos_x64 FAILED
exception: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at org.jetbrains.kotlin.konan.file.FileKt.zipFileSystem(File.kt:183)
	at org.jetbrains.kotlin.konan.file.FileKt.zipFileSystem$default(File.kt:179)
	at org.jetbrains.kotlin.konan.file.FileKt.zipPath(File.kt:192)
	at org.jetbrains.kotlin.konan.file.FileKt.getAsZipRoot(File.kt:195)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary$libDir$2.invoke(KonanLibrary.kt:37)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary$libDir$2.invoke(KonanLibrary.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary.getLibDir(KonanLibrary.kt)
	at org.jetbrains.kotlin.backend.konan.library.KonanLibraryLayout$DefaultImpls.getTargetsDir(KonanLibrary.kt:34)
	at org.jetbrains.kotlin.backend.konan.library.KonanLibrary$DefaultImpls.getTargetsDir(KonanLibrary.kt)
	at org.jetbrains.kotlin.backend.konan.library.impl.ZippedKonanLibrary.getTargetsDir(KonanLibrary.kt:24)
	at org.jetbrains.kotlin.backend.konan.library.impl.LibraryReaderImpl.<init>(KonanLibraryReaderImpl.kt:57)
	at org.jetbrains.kotlin.backend.konan.library.SearchPathResolverExtensionsKt.resolveImmediateLibraries(SearchPathResolverExtensions.kt:35)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$immediateLibraries$2.invoke(KonanConfig.kt:94)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$immediateLibraries$2.invoke(KonanConfig.kt:40)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.getImmediateLibraries$backend_native_compiler(KonanConfig.kt)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.loadLibMetadata(KonanConfig.kt:129)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:109)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:63)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:42)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:91)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:69)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:37)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:201)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:192)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:206)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:197)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:199)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:211)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios:compileKonanKotlinArithmeticParserIos_x64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
2 actionable tasks: 2 executed
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by thevery** [comment]
Try to remove ~/.konan (but please backup first)

**Comment by jblorenzo** [comment]
@thevery got the same error

```
Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-1-darwin-ios_sim.tar.gz (0 bytes/23.6 kiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-1-darwin-ios_sim.tar.gz (23.6 kiB/23.6 kiB). Done.
Extracting dependency: /Users/jb.lorenzo/.konan/cache/libffi-3.2.1-1-darwin-ios_sim.tar.gz into /Users/jb.lorenzo/.konan/dependencies

Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (0 bytes/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (16.0 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (48.0 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (78.7 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (109.0 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (140.4 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (171.9 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (202.1 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (231.8 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (263.7 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (294.7 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (325.7 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (332.8 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (341.3 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (350.5 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (356.8 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (374.0 MiB/374.1 MiB). 
Downloading dependency: https://download.jetbrains.com/kotlin/native/clang-llvm-5.0.0-darwin-macos.tar.gz (374.1 MiB/374.1 MiB). Done.
Extracting dependency: /Users/jb.lorenzo/.konan/cache/clang-llvm-5.0.0-darwin-macos.tar.gz into /Users/jb.lorenzo/.konan/dependencies
exception: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
```

**Comment by olonho** [comment]
Please try fresh K/N checkout.
