### ISSUE TITLE
java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1903]
```kotlin
inline fun demo(callback: () -> Unit) {
	callback()
}

fun main(args: Array<String>) {
	demo {
		data class Test(val a: Int)
		class Test2(val a: Test)
	}
}
```

Also happens with:

```kotlin
fun main(args: Array<String>) {
        run {
                class Test
                class Test2(val a: Test)
        }
}
```

```
➜  Desktop ~/.konan/kotlin-native-macos-0.9-dev-3210/bin/konanc kdemo.kt
error: compilation failed: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@426131d7

 * Source files: kdemo.kt
 * Compiler version info: Konan: 0.9-dev-3210 / Kotlin: 1.2.70
 * Output kind: PROGRAM

exception: java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@426131d7
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmDeclarations.forFunction(LlvmDeclarations.kt:55)
	at org.jetbrains.kotlin.backend.konan.llvm.ContextUtils$DefaultImpls.getLlvmFunction(ContextUtils.kt:176)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.getLlvmFunction(CodeGenerator.kt:37)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.llvmFunction(CodeGenerator.kt:39)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt:95)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:146)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:120)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:145)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:89)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:106)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:146)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:120)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:145)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:105)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:146)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:120)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:145)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:99)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:89)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:45)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:213)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:204)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:206)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:218)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

**Comment by sbogolepov** [comment]
Fixed with #1905.
