### ISSUE TITLE
Build fails when program links against library in the same gradle project

### ISSUE THREAD

**Issue by zero9178** [JetBrains/kotlin-native#1939]
I am creating a klib as well as an exe and the exe has a dependency on the klib. When doing a build using the build task in gradle it compiles without any problems. However when I then run the exe in CLion using the gradle konan Application runner the compilation of the library fails with following stacktrace:
```
error: compilation failed: C:\Users\Markus\Documents\CLion\MKPkg\build\konan\libs\mingw_x64\pqkt.klib

 * Source files: Connection.kt, Result.kt, Util.kt
 * Compiler version info: Konan: 0.8.2 / Kotlin: 1.2.70
 * Output kind: LIBRARY

exception: java.nio.file.AccessDeniedException: C:\Users\Markus\Documents\CLion\MKPkg\build\konan\libs\mingw_x64\pqkt.klib
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.jetbrains.kotlin.konan.file.File.delete(File.kt:71)
	at org.jetbrains.kotlin.backend.konan.library.impl.LibraryWriterImpl.<init>(KonanLibraryWriterImpl.kt:54)
	at org.jetbrains.kotlin.backend.konan.library.impl.LibraryWriterImpl.<init>(KonanLibraryWriterImpl.kt:39)
	at org.jetbrains.kotlin.backend.konan.library.impl.KonanLibraryWriterImplKt.buildLibrary(KonanLibraryWriterImpl.kt:131)
	at org.jetbrains.kotlin.backend.konan.CompilerOutputKt.produceOutput(CompilerOutput.kt:81)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5$2.invoke(KonanDriver.kt:103)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:145)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:144)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:101)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:145)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:144)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:95)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:42)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:91)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:69)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:37)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:201)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:192)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:206)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:197)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:199)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:211)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

**Comment by alexander-gorshenev** [comment]
@zero9178 Could you please share your `build.gradle` (or whatever the build script you have) reproducing the issue?

**Comment by zero9178** [comment]
This is my build.gradle.kt
```
plugins {
    id("org.jetbrains.kotlin.konan").version("0.8.2")
}

konanArtifacts {
    library("pqkt") {
        srcDir("src/pqkt/kotlin")
        libraries {
            klib("libpqkt")

            useRepo("C:\\Libraries\\libpq")
        }
    }

    program("mkpkg") {
        libraries {
            artifact("pqkt")
        }
    }
}
```
libpqkt is a manually cinterop generated klib from libpq (postgresql)

**Comment by ddolovov** [comment]
@zero9178 Would it be possible to see the whole your project, not only the build file?

Also, which version of CLion and of Kotlin/Native for CLion plugin do you use?

**Comment by alexander-gorshenev** [comment]
Thanks for the repository.

I've checked out the project, downloaded the dependencies to C:\Libraries, opened the project in CLion and it got to the point of running .exe

At this point I should be seeing a stack trace. I don't see any.
Do you see the same original error in such setup?

The  `build.gradle.kts` is written so that it doesn't build any libraries, afaict. The section building the library is commented out.

**Comment by zero9178** [comment]
@alexander-gorshenev To continue working on the program I have update it since. Please use the project files from this commit https://github.com/zero9178/MGPkg/commit/502838c4a36e0488d5769ccc1d8e725a167406aa. The exception occurs before running the exe when building the exe by running the Konan application in CLion.

**Comment by alexander-gorshenev** [comment]
@zero9178 Thank you. We've been able to reproduce the issue.

**Comment by baochau62** [comment]
Hi, 
I'm getting this error when building.  I had already installed JDK 10.0.2

> Configure project :ios
feature GRADLE_METADATA is not enabled: publication is disabled

> Task :ios:checkKonanCompiler
> Task :ios:compileKonanKotlinArithmeticParserIos_x64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios:compileKonanKotlinArithmeticParserIos_x64'.
> Classpath of the tool is empty: konanc
  Probably the 'konan.home' project property contains an incorrect path.
  Please change it to the compiler root directory and rerun the build.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed
Command /bin/sh failed with exit code 1

**Comment by SvyatoslavScherbina** [comment]
Hi. Kotlin plugin for CLion is deprecated now. Please use IntelliJ IDEA Ultimate.
See more details here:
https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/
https://plugins.jetbrains.com/plugin/10454-kotlin-native-for-clion
