### ISSUE TITLE
obj-c generics are not included in klib

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#1973]
I've compiled a lib which contains the following h-file: https://github.com/TextureGroup/Texture/blob/master/Source/ASViewController.h

However, there is no `ASViewController` in the klib.
Are obj-c generics supported?

**Comment by SvyatoslavScherbina** [comment]
Objective-C classes with generics are generally imported as Kotlin classes without generics.
Are you sure that you have included this header into the library? Does it contain e.g. `ASDisplayTraitsForTraitCollectionBlock`?

**Comment by ildarsharafutdinov** [comment]
@SvyatoslavScherbina,

I've just cleaned the cache and rebuilt the klib. Also I checked my def file and klib.

There is `ASViewController.h` in my def file, however, the klib misses both `ASViewController` and `ASDisplayTraitsForTraitCollectionBlock`.

This is pretty strange since e.g. `ASDisplayNode`, which is a part of the same lib is available in klib.

Any idea of what could go wrong?

**Comment by ildarsharafutdinov** [comment]
Here is what I've found.

If I move `ASViewController.h` to the beginning of my headers list in def file, `ASViewController` is added to the klib.

Here is the def file, which results in missing `ASViewController`
```
depends = UIKit CoreText
language = Objective-C
package = pods.Texture
headers =  Texture-prefix.pch \
    ASAbsoluteLayoutElement.h ASAbsoluteLayoutSpec.h ASAbstractLayoutController.h ASAsciiArtBoxCreator.h \
    ASAssert.h ASAvailability.h ASBackgroundLayoutSpec.h ASBaseDefines.h ASBasicImageDownloader.h \
    ASBatchContext.h ASBatchFetchingDelegate.h ASBlockTypes.h ASButtonNode.h ASCGImageBuffer.h \
    ASCellNode.h ASCenterLayoutSpec.h ASCollectionElement.h ASCollectionFlowLayoutDelegate.h \
    ASCollectionGalleryLayoutDelegate.h ASCollectionLayoutContext.h \ 
    ASCollectionLayoutDelegate.h ASCollectionLayoutState.h ASCollectionNode+Beta.h ASCollectionNode.h \
    ASCollectionView.h ASCollectionViewLayoutController.h ASCollectionViewLayoutFacilitatorProtocol.h \
    ASCollectionViewLayoutInspector.h ASCollectionViewProtocols.h ASConfiguration.h ASConfigurationDelegate.h \
    ASContextTransitioning.h ASControlNode+Subclasses.h ASControlNode.h ASCornerLayoutSpec.h \
    ASDataController.h ASDelegateProxy.h ASDimension.h ASDisplayNode+Ancestry.h \
    ASDisplayNode+Beta.h ASDisplayNode+Convenience.h ASDisplayNode+Subclasses.h ASDisplayNode.h ASDisplayNodeExtras.h \
    ASEditableTextNode.h ASElementMap.h ASEqualityHelpers.h ASEventLog.h ASExperimentalFeatures.h \
    ASGraphicsContext.h ASHashing.h ASHighlightOverlayLayer.h ASImageContainerProtocolCategories.h \
    ASImageNode.h ASImageProtocols.h ASInsetLayoutSpec.h ASIntegerMap.h ASLayout.h ASLayoutController.h \
    ASLayoutElement.h ASLayoutElementExtensibility.h ASLayoutElementPrivate.h ASLayoutRangeType.h \
    ASLayoutSpec+Subclasses.h ASLayoutSpec.h ASLog.h ASMainSerialQueue.h ASMapNode.h ASMultiplexImageNode.h \
    ASMutableAttributedStringBuilder.h ASNavigationController.h ASNetworkImageLoadInfo.h ASNetworkImageNode.h \
    ASNodeController+Beta.h ASObjectDescriptionHelpers.h ASOverlayLayoutSpec.h ASPINRemoteImageDownloader.h \
    ASPageTable.h ASPagerFlowLayout.h ASPagerNode+Beta.h ASPagerNode.h ASPhotosFrameworkImageRequest.h \
    ASRangeController.h ASRangeControllerUpdateRangeProtocol+Beta.h ASRangeManagingNode.h ASRatioLayoutSpec.h \
    ASRecursiveUnfairLock.h ASRelativeLayoutSpec.h ASRunLoopQueue.h ASScrollDirection.h ASScrollNode.h \
    ASSectionContext.h ASSectionController.h ASSignpost.h ASStackLayoutDefines.h ASStackLayoutElement.h \
    ASStackLayoutSpec.h ASSupplementaryNodeSource.h ASTabBarController.h ASTableLayoutController.h \
    ASTableNode+Beta.h ASTableNode.h ASTableView.h ASTableViewProtocols.h \
    ASTextKitComponents.h ASTextNode+Beta.h ASTextNode.h ASTextNode2.h ASTextNodeCommon.h ASTextNodeTypes.h \
    ASThread.h ASTraceEvent.h ASTraitCollection.h ASVideoNode.h ASVideoPlayerNode.h ASViewController.h \
    ASVisibilityProtocols.h ASWeakProxy.h ASWeakSet.h ASYogaLayoutSpec.h ASYogaUtilities.h \
    AsyncDisplayKit+Debug.h AsyncDisplayKit+IGListKitMethods.h AsyncDisplayKit+Tips.h AsyncDisplayKit.h \
    CoreGraphics+ASConvenience.h IGListAdapter+AsyncDisplayKit.h NSArray+Diffing.h NSIndexSet+ASHelpers.h \
    NSMutableAttributedString+TextKitAdditions.h UICollectionViewLayout+ASConvenience.h \
    UIImage+ASConvenience.h UIResponder+AsyncDisplayKit.h UIView+ASConvenience.h _ASAsyncTransaction.h \
    _ASAsyncTransactionContainer+Private.h _ASAsyncTransactionContainer.h _ASAsyncTransactionGroup.h \
    _ASCollectionReusableView.h _ASCollectionViewCell.h _ASDisplayLayer.h _ASDisplayView.h \
    _ASDisplayViewAccessiblity.h _ASTransitionContext.h


#ASCollectionInternal.h ASTableViewInternal.h ASConfigurationInternal.h ASDimensionInternal.h

headerFilter = **
```

**Comment by SvyatoslavScherbina** [comment]
Btw,

> `depends = UIKit CoreText`

This is not required, all platform libs are added by default.

> `headerFilter = **`

This is not required since `**` acts exactly like the default value in your case.

And what is the reason to enumerate all the headers instead of the umbrella one?

**Comment by ildarsharafutdinov** [comment]
I'm aware of `depends` & `headerFilter` and I'll certainly clean up the def file in future. 

You're 100% right I should have used an umbrella header. However, copying the contents of a podspec(I use cocoa pods) is actually the fastest way to build a working prototype.

Btw, I tried to build klib with only pch and umbrella header. I took me 1.5 hour and failed with the exception:

 ```
error: compilation failed: kfun:pods.Texture.__tg_promote(kotlin.Long)ValueType

 * Source files: Texture.kt
 * Compiler version info: Konan: 0.9-dev / Kotlin: 1.3.0
 * Output kind: LIBRARY

exception: java.lang.AssertionError: kfun:pods.Texture.__tg_promote(kotlin.Long)ValueType
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFunction(LlvmDeclarations.kt:411)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:52)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitSimpleFunction(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:53)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitSimpleFunction(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitSimpleFunction(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl.accept(IrFunctionImpl.kt:87)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:79)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitElement(LlvmDeclarations.kt:200)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitPackageFragment(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFile(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFile(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFile(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:76)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:45)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
        at org.jetbrains.kotlin.backend.konan.llvm.LlvmDeclarationsKt.createLlvmDeclarations(LlvmDeclarations.kt:23)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:91)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:95)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:94)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:80)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:36)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:204)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:195)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:197)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:209)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)
```

Here is the def file:
```
depends = UIKit CoreText
language = Objective-C
package = pods.Texture
headers =  Texture-prefix.pch AsyncDisplayKit.h

headerFilter = **
```

**Comment by SvyatoslavScherbina** [comment]
> Btw, I tried to build klib with only pch and umbrella header. I took me 1.5 hour

Have you tried to remove the pch?

> and failed with the exception:
> exception: java.lang.AssertionError: kfun:pods.Texture.__tg_promote(kotlin.Long)ValueType

This declaration (`__tg_promote`) is not supported. It comes from the system header `tgmath.h` that is likely to get included (either directly or indirectly) by some of the library headers. You can workaround the issue by excluding `tgmath.h` from your library by writing proper `headerFilter`.

**Comment by SvyatoslavScherbina** [comment]
I believe the issue will vanish if your library imports all of the headers,  including the one with `@interface ASCollectionElement`.

**Comment by ildarsharafutdinov** [comment]
I ended up with `headers = Texture-prefix.pch AsyncDisplayKit/AsyncDisplayKit.h AsyncDisplayKit/ASCollectionElement.h`, which seems to work.

@SvyatoslavScherbina, thank you for fast and helpful replies.

**Comment by SvyatoslavScherbina** [comment]
I'm glad to know that.
You are welcome!
