### ISSUE TITLE
Windows Clion, source file too many,  Compile command too long Error

### ISSUE THREAD

**Issue by chinacharis** [JetBrains/kotlin-native#1999]
org.gradle.execution.MultipleBuildFailures: Build completed with 1 failures.
	at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:350)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:216)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:146)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:121)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:74)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileKonanUcstarsdkMingw_x64'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	... 6 more
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'D:\Program Files\Java\jdk1.8.0_181\bin\java.exe''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:231)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:355)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	... 6 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'D:\Program Files\Java\jdk1.8.0_181\bin\java.exe'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
	... 7 more
Caused by: java.io.IOException: Cannot run program "D:\Program Files\Java\jdk1.8.0_181\bin\java.exe" (in directory "F:\ucstarsdk_kotlin"): CreateProcess error=206, 文件名或扩展名太长。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1049)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=206, 文件名或扩展名太长。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:389)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1030)
	... 11 more

**Comment by olonho** [comment]
This report lacks any  information about your environment or trigger for the problem. Exception just says that `java.exe` cannot be started. Please provide more info or I have to close the issue.

**Comment by chinacharis** [comment]
win10 jdk1.8.0.181 the latest clion
I decompile ProcessImpl.class, then reput into rt.jar

private ProcessImpl(String cmd[],
                        final String envblock,
                        final String path,
                        final long[] stdHandles,
                        final boolean redirectErrorStream)
        throws IOException
    {
        String cmdstr;
        SecurityManager security = System.getSecurityManager();
        boolean allowAmbiguousCommands = false;
        if (security == null) {
            allowAmbiguousCommands = true;
            String value = System.getProperty("jdk.lang.Process.allowAmbiguousCommands");
            if (value != null)
                allowAmbiguousCommands = !"false".equalsIgnoreCase(value);
        }
        if (allowAmbiguousCommands) {
            // Legacy mode.

            // Normalize path if possible.
            String executablePath = new File(cmd[0]).getPath();

            // No worry about internal, unpaired ["], and redirection/piping.
            if (needsEscaping(VERIFICATION_LEGACY, executablePath) )
                executablePath = quoteString(executablePath);

            cmdstr = createCommandLine(
                //legacy mode doesn't worry about extended verification
                VERIFICATION_LEGACY,
                executablePath,
                cmd);
        } else {
            String executablePath;
            try {
                executablePath = getExecutablePath(cmd[0]);
            } catch (IllegalArgumentException e) {
                // Workaround for the calls like
                // Runtime.getRuntime().exec("\"C:\\Program Files\\foo\" bar")

                // No chance to avoid CMD/BAT injection, except to do the work
                // right from the beginning. Otherwise we have too many corner
                // cases from
                //    Runtime.getRuntime().exec(String[] cmd [, ...])
                // calls with internal ["] and escape sequences.

                // Restore original command line.
                StringBuilder join = new StringBuilder();
                // terminal space in command line is ok
                for (String s : cmd)
                    join.append(s).append(' ');

                // Parse the command line again.
                cmd = getTokensFromCommand(join.toString());
                executablePath = getExecutablePath(cmd[0]);

                // Check new executable name once more
                if (security != null)
                    security.checkExec(executablePath);
            }

            // Quotation protects from interpretation of the [path] argument as
            // start of longer path with spaces. Quotation has no influence to
            // [.exe] extension heuristic.
            cmdstr = createCommandLine(
                    // We need the extended verification procedure for CMD files.
                    isShellFile(executablePath)
                        ? VERIFICATION_CMD_BAT
                        : VERIFICATION_WIN32,
                    quoteString(executablePath),
                    cmd);
        }
        
        System.out.println("#########################");
        System.out.println(cmdstr);

        handle = create(cmdstr, envblock, path,
                        stdHandles, redirectErrorStream);

        java.security.AccessController.doPrivileged(
        new java.security.PrivilegedAction<Void>() {
        public Void run() {
            if (stdHandles[0] == -1L)
                stdin_stream = ProcessBuilder.NullOutputStream.INSTANCE;
            else {
                FileDescriptor stdin_fd = new FileDescriptor();
                fdAccess.setHandle(stdin_fd, stdHandles[0]);
                stdin_stream = new BufferedOutputStream(
                    new FileOutputStream(stdin_fd));
            }

            if (stdHandles[1] == -1L)
                stdout_stream = ProcessBuilder.NullInputStream.INSTANCE;
            else {
                FileDescriptor stdout_fd = new FileDescriptor();
                fdAccess.setHandle(stdout_fd, stdHandles[1]);
                stdout_stream = new BufferedInputStream(
                    new FileInputStream(stdout_fd));
            }

            if (stdHandles[2] == -1L)
                stderr_stream = ProcessBuilder.NullInputStream.INSTANCE;
            else {
                FileDescriptor stderr_fd = new FileDescriptor();
                fdAccess.setHandle(stderr_fd, stdHandles[2]);
                stderr_stream = new FileInputStream(stderr_fd);
            }

            return null; }});
    }

throw Exception code:
handle = create(cmdstr, envblock, path,
                        stdHandles, redirectErrorStream);

seem like cmdstr tool long, length=60685

print cmdstr:

"D:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -D__idea.mac.env.lock=unlocked -Dawt.toolkit=sun.awt.windows.WToolkit -Dcom.jetbrains.suppressWindowRaise=false -Dfile.encoding.pkg=sun.io -Dfile.separator=\ -Dide.native.launcher=true -Didea.cycle.buffer.size=1024 -Didea.dynamic.classpath=false -Didea.fatal.error.notification=disabled -Didea.jars.nocopy=true -Didea.max.content.load.filesize=20000 -Didea.max.intellisense.filesize=2500 -Didea.no.launcher=false -Didea.paths.selector=CLion2018.2 -Didea.platform.prefix=CLion -Didea.popup.weight=heavy -Didea.registered=true -Dio.netty.machineId=28:f0:76:ff:fe:16:65:0e -Dio.netty.processId=5742 "-Dio.netty.serviceThreadPrefix=Netty " -Djava.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment -Djava.awt.printerjob=sun.awt.windows.WPrinterJob -Djava.class.path=C:\gradle-4.9\lib\gradle-launcher-4.9.jar -Djava.class.version=52.0 "-Djava.endorsed.dirs=D:\Program Files\JetBrains\CLion 2018.2.1\jre64\lib\endorsed" "-Djava.ext.dirs=D:\Program Files\Java\jdk1.8.0_181\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext" "-Djava.home=D:\Program Files\Java\jdk1.8.0_181\jre" -Djava.library.path=C:\Users\zhua\.konan\kotlin-native-windows-0.8.2/konan/nativelib -Djava.net.preferIPv4Stack=true -Djava.rmi.server.disableHttp=true -Djava.rmi.server.hostname=127.0.0.1 "-Djava.runtime.name=OpenJDK Runtime Environment" -Djava.runtime.version=1.8.0_181-b13 "-Djava.specification.name=Java Platform API Specification" "-Djava.specification.vendor=Oracle Corporation" -Djava.specification.version=1.8 -Djava.util.concurrent.ForkJoinPool.common.threadFactory=com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory "-Djava.vendor=Oracle Corporation" -Djava.vendor.url=http://java.oracle.com/ -Djava.vendor.url.bug=https://youtrack.jetbrains.com -Djava.version=1.8.0_181 "-Djava.vm.info=mixed mode" "-Djava.vm.name=Java HotSpot(TM) 64-Bit Server VM" "-Djava.vm.specification.name=Java Virtual Machine Specification" "-Djava.vm.specification.vendor=Oracle Corporation" -Djava.vm.specification.version=1.8 "-Djava.vm.vendor=Oracle Corporation" -Djava.vm.version=25.181-b13 -Djavax.swing.rebaseCssSizeMap=true "-Djb.vmOptionsFile=D:\Program Files\JetBrains\CLion 2018.2.1\bin\clion64.exe.vmoptions" -Djbre.popupwindow.settype=true -Djbre.win.app.icon.supported=true -Djdk.http.auth.tunneling.disabledSchemes=\"\" -Djna.loaded=true -Djna.nosys=true -Djna.tmpdir=C:\Users\zhua\.CLion2018.2\system\tmp -Djnidispatch.path=C:\Users\zhua\.CLion2018.2\system\tmp\jna2730907554740140595.dll -Dkonan.home=C:\Users\zhua\.konan\kotlin-native-windows-0.8.2 -Dlibrary.jansi.path=C:\gradle\native\jansi\1.14\windows64 -Dline.separator=
 -Dlog4j.defaultInitOverride=true -Dos.arch=amd64 "-Dos.name=Windows 10" -Dos.version=10.0 -Dpath.separator=; -Drun.processes.with.pty=true -Dsun.arch.data.model=64 "-Dsun.boot.class.path=D:\Program Files\Java\jdk1.8.0_181\jre\lib\resources.jar;D:\Program Files\Java\jdk1.8.0_181\jre\lib\rt.jar;D:\Program Files\Java\jdk1.8.0_181\jre\lib\sunrsasign.jar;D:\Program Files\Java\jdk1.8.0_181\jre\lib\jsse.jar;D:\Program Files\Java\jdk1.8.0_181\jre\lib\jce.jar;D:\Program Files\Java\jdk1.8.0_181\jre\lib\charsets.jar;D:\Program Files\Java\jdk1.8.0_181\jre\lib\jfr.jar;D:\Program Files\Java\jdk1.8.0_181\jre\classes" "-Dsun.boot.library.path=D:\Program Files\Java\jdk1.8.0_181\jre\bin" -Dsun.cpu.endian=little -Dsun.cpu.isalist=amd64 -Dsun.desktop=windows -Dsun.io.unicode.encoding=UnicodeLittle "-Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.9" -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=GBK "-Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers" -Dsun.os.patch.level -Dswing.bufferPerWindow=false -Duser.dir=F:\ucstarsdk_kotlin -Duser.home=C:\Users\zhua -Duser.name=zhua -Duser.script -Duser.timezone=Asia/Shanghai -Dwinp.folder.preferred=C:\Users\zhua\.CLion2018.2\system\tmp -Xmx3G -Dfile.encoding=GBK -Djava.io.tmpdir=C:\Users\zhua\AppData\Local\Temp\ -Duser.country=CN -Duser.language=zh -Duser.variant -ea -cp C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\backend.native.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\Indexer.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\klib.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\kotlin-compiler.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\kotlin-reflect.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\kotlin-script-runtime.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\kotlin-stdlib.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\protobuf-java-2.6.1.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\Runtime.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\shared.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\StubGenerator.jar;C:\Users\zhua\.konan\kotlin-native-windows-0.8.2\konan\lib\utilities.jar org.jetbrains.kotlin.cli.utilities.MainKt konanc -output F:\ucstarsdk_kotlin\build\konan\bin\mingw_x64\ucstarsdk.exe -repo F:\ucstarsdk_kotlin\build\konan\bin\mingw_x64 -repo F:\ucstarsdk_kotlin\build\konan\libs\mingw_x64 -produce program -target mingw_x64 -g -verbose F:\ucstarsdk_kotlin\src\main\kotlin\android\app\AppGlobals.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\app\PlatformDependence.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\content\ContentValues.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\content\Context.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\content\SharedPreferences.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\CharArrayBuffer.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\CrossProcessCursor.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\Cursor.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\CursorIndexOutOfBoundsException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\CursorWrapper.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\IDatabase.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\SQLException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDatabase.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDatabaseConfiguration.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDatabaseCorruptException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDatabaseLockedException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDatatypeMismatchException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDiskIOException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteDoneException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteFullException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteMisuseException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteOutOfMemoryException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteReadOnlyDatabaseException.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteStatementInfo.kt F:\ucstarsdk_kotlin\src\main\kotlin\android\database\sqlite\SQLiteTableLockedException.kt 
.....

copy into notepad++, appear newline after -Dline.separator=

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin-native/pull/2040/commits/8fc6c06ee45c0ba5ab3fded337e5193a109bfc1f
