### ISSUE TITLE
compilation failed: GC overhead limit exceeded

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#2044]
```
> Task :platformLibs:compileKonanMingw_x64-windowsMingw_x64
warning: argument --temporary_files_dir is deprecated. Please use -Xtemporary-files-dir instead
warning: argument -nativelibrary is deprecated. Please use -native-library instead
warning: argument --purge_user_libs is deprecated. Please use -Xpurge-user-libs instead
error: compilation failed: GC overhead limit exceeded

 * Source files: windows.kt
 * Compiler version info: Konan: 0.9-dev / Kotlin: 1.3.0
 * Output kind: LIBRARY

exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3308)
        at java.util.BitSet.ensureCapacity(BitSet.java:337)
        at java.util.BitSet.or(BitSet.java:943)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$analyze$12.invoke(Devirtualization.kt:537)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis$analyze$12.invoke(Devirtualization.kt:541)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization$DevirtualizationAnalysis.analyze(Devirtualization.kt:558)
        at org.jetbrains.kotlin.backend.konan.optimizations.Devirtualization.run(Devirtualization.kt:985)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt:117)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:115)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:95)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:94)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)            17:37
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:80)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:36)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
```

This patch fixes it:
``` diff
diff --git a/platformLibs/build.gradle b/platformLibs/build.gradle
index bbe5070a3..0fe2c2066 100644
--- a/platformLibs/build.gradle
+++ b/platformLibs/build.gradle
@@ -22,7 +22,7 @@ buildscript {
     }
 
     ext.konanHome = distDir.absolutePath
-    ext.jvmArgs = project.findProperty("platformLibsJvmArgs") ?: "-Xmx4G"
+    ext.jvmArgs = project.findProperty("platformLibsJvmArgs") ?: "-Xmx5G"
     ext.setProperty("konan.home", konanHome)
     ext.setProperty("konan.jvmArgs", jvmArgs)
 }
```
Last time - in February - memory limit was bumped from 3G to 4G, and now exceeded again.

**Comment by olonho** [comment]
Yeah, bumped limit for now, will analyze what is responsible for such consumption a bit later.

**Comment by msink** [comment]
Do'nt see it bumped on master.
