### ISSUE TITLE
EXC_BAD_ACCESS (code=EXC_I386_GPFLT) in an unexpected place

### ISSUE THREAD

**Issue by subprogram** [JetBrains/kotlin-native#2101]
While migration from 0.9 to 0.9.1 I've stumbled on this error.
My research shows that with 0.9-dev-3770 my app works fine but with 0.9-dev-3909 it is crashes.
The stacktrace:
```
#0  0x0000000113b0a4b0 in swift_beginAccess ()
#1  0x000000010bc8efd4 in BaseViewController.viewWillDisappear(_:) at /Users/subprogram/Documents/workspace/GuitarSongs_new/iOs/GuitarSongs/screens/base/BaseViewController.swift:110
#2  0x000000010bc8f053 in @objc BaseViewController.viewWillDisappear(_:) ()
#3  0x000000010bbd6f94 in MainViewController.viewWillDisappear(_:) at /Users/subprogram/Documents/workspace/GuitarSongs_new/iOs/GuitarSongs/screens/main/MainViewController.swift:50
#4  0x000000010bbd6fe3 in @objc MainViewController.viewWillDisappear(_:) ()
#5  0x000000010e99dec9 in -[UIViewController _setViewAppearState:isAnimating:] ()
#6  0x000000010e99e747 in -[UIViewController __viewWillDisappear:] ()
#7  0x000000010e968e06 in __56-[UIPresentationController runTransitionForCurrentState]_block_invoke ()
#8  0x000000010e7ff4b3 in _runAfterCACommitDeferredBlocks ()
#9  0x000000010e7ee71e in _cleanUpAfterCAFlushAndRunDeferredBlocks ()
#10 0x000000010e81cea5 in _afterCACommitHandler ()
#11 0x0000000112736607 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#12 0x000000011273655e in __CFRunLoopDoObservers ()
#13 0x000000011271ab81 in __CFRunLoopRun ()
#14 0x000000011271a30b in CFRunLoopRunSpecific ()
#15 0x0000000118991a73 in GSEventRunModal ()
#16 0x000000010e7f4057 in UIApplicationMain ()
#17 0x000000010bc8cc17 in main at /Users/subprogram/Documents/workspace/GuitarSongs_new/iOs/GuitarSongs/AppDelegate.swift:13
#18 0x00000001143b8955 in start ()
```

I don't know if it helps but just in case, the code:
```
class BaseViewController: UIViewController, UISearchBarDelegate, IBaseViewController {
    let helper: BaseVcHelper   //BaseVcHelper is a swift class that extends NSObject and some Kotlin interfaces

   ...

   init(nibName: String) {
        self.helper = BaseVcHelper(false)
        super.init(nibName: nibName, bundle: nil)
        ...
    }

   ...    

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        helper.viewWillDisappear(animated)   //Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    }

   ...
}
```
Any ideas?

**Comment by SvyatoslavScherbina** [comment]
This code snippet doesn't seem to be enough to reproduce the issue. Could you please provide a reproducer?

**Comment by subprogram** [comment]
@SvyatoslavScherbina I've send you email.
