### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Dkhusainov** [JetBrains/kotlin-native#2120]
I'm using new `kotlin-multiplatform'
Kotlin: 1.3.0-rc57
Gradle: 4.10

All I have is this trace from with --debug flag. Unfortunately It doesn't tell which class crashes the compilation, I have a lot of them in the module so figuring out which one is it is hard.  Any advice how to produce better stacktrace?

14:46:45.139 [ERROR] [system.err]  * Compiler version info: Konan: 0.9.2-dev-4008 / Kotlin: 1.3.0
14:46:45.139 [ERROR] [system.err]  * Output kind: FRAMEWORK
14:46:45.139 [ERROR] [system.err] 
14:46:45.139 [ERROR] [system.err] exception: java.lang.AssertionError: Assertion failed
14:46:45.139 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClassName(ObjCExportHeaderGenerator.kt:303)
14:46:45.139 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReferenceTypeIgnoringNullability$backend_native_compiler(ObjCExportHeaderGenerator.kt:857)
14:46:45.139 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.CustomTypeMapper$Collection.mapType(CustomTypeMapper.kt:40)
14:46:45.140 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReferenceTypeIgnoringNullability$backend_native_compiler(ObjCExportHeaderGenerator.kt:836)
14:46:45.140 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReferenceType$backend_native_compiler(ObjCExportHeaderGenerator.kt:797)
14:46:45.140 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapType(ObjCExportHeaderGenerator.kt:892)
14:46:45.140 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReturnType(ObjCExportHeaderGenerator.kt:754)
14:46:45.140 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.buildProperty(ObjCExportHeaderGenerator.kt:609)
14:46:45.140 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.access$buildProperty(ObjCExportHeaderGenerator.kt:26)
14:46:45.141 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$buildAsDeclaredOrInheritedProperties$$inlined$getOrPut$lambda$2.invoke(ObjCExportHeaderGenerator.kt:593)
14:46:45.141 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$buildAsDeclaredOrInheritedProperties$$inlined$getOrPut$lambda$2.invoke(ObjCExportHeaderGenerator.kt:26)
14:46:45.141 [ERROR] [system.err]       at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
14:46:45.141 [ERROR] [system.err]       at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
14:46:45.141 [ERROR] [system.err]       at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:685)
14:46:45.141 [ERROR] [system.err]       at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:726)
14:46:45.141 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.buildAsDeclaredOrInheritedProperties(ObjCExportHeaderGenerator.kt:595)
14:46:45.142 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.access$buildAsDeclaredOrInheritedProperties(ObjCExportHeaderGenerator.kt:26)
14:46:45.142 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$translateClassMembers$2.invoke(ObjCExportHeaderGenerator.kt:512)
14:46:45.142 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$translateClassMembers$2.invoke(ObjCExportHeaderGenerator.kt:26)
14:46:45.142 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.collectMethodsOrProperties(ObjCExportHeaderGenerator.kt:561)
14:46:45.142 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClassMembers(ObjCExportHeaderGenerator.kt:512)
14:46:45.143 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClassMembers(ObjCExportHeaderGenerator.kt:460)
14:46:45.143 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClass(ObjCExportHeaderGenerator.kt:435)
14:46:45.143 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.access$translateClass(ObjCExportHeaderGenerator.kt:26)
14:46:45.143 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$translateModule$4.invoke(ObjCExportHeaderGenerator.kt:211)
14:46:45.143 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateModule(ObjCExportHeaderGenerator.kt:219)
14:46:45.144 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produceFrameworkSpecific(ObjCExport.kt:68)
14:46:45.144 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produce$backend_native_compiler(ObjCExport.kt:41)
14:46:45.144 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:382)
14:46:45.144 [ERROR] [system.err]       at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
14:46:45.144 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:291)
14:46:45.144 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:291)
14:46:45.145 [ERROR] [system.err]       at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:42)
14:46:45.145 [ERROR] [system.err]       at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:247)
14:46:45.145 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$7.invoke(IrToBitcode.kt:162)
14:46:45.145 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$7.invoke(IrToBitcode.kt)
14:46:45.145 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
14:46:45.146 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
14:46:45.146 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
14:46:45.146 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
14:46:45.146 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:161)
14:46:45.146 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:95)
14:46:45.146 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
14:46:45.147 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
14:46:45.147 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
14:46:45.147 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
14:46:45.147 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
14:46:45.147 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:94)
14:46:45.148 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
14:46:45.148 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
14:46:45.148 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
14:46:45.148 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
14:46:45.149 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
14:46:45.149 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
14:46:45.149 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
14:46:45.150 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:38)
14:46:45.150 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
14:46:45.150 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
14:46:45.150 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
14:46:45.151 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
14:46:45.151 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
14:46:45.151 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
14:46:45.151 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
14:46:45.151 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:209)
14:46:45.152 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:200)
14:46:45.152 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
14:46:45.152 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
14:46:45.152 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:202)
14:46:45.152 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:214)
14:46:45.152 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:15)

**Comment by Dkhusainov** [comment]
Removing `internal` from everthing fixed the problem. Is this intended behaviour?

**Comment by subprogram** [comment]
I've accidentally found a case that reproduces the same error:
Common module:
```
expect fun Char.isLetter(): Boolean
```
K/N module:
```
actual fun Char.isLetter(): Boolean = true
```
The same extension of `Int` instead of `Char` is compiled without errors.

**Comment by SvyatoslavScherbina** [comment]
@subprogram thank you for the report. This case reproduces the same error but is not actually related  to the original report.

**Comment by SvyatoslavScherbina** [comment]
@Dkhusainov thank you for the report. It looks like you are trying to compile the code which is not supposed to be allowed by the compiler: https://youtrack.jetbrains.com/issue/KT-27112

**Comment by olonho** [comment]
Could it be closed?

**Comment by subprogram** [comment]
Is it possible to add a source filename and a line number in the error message? I think it will help to find other bugs much faster in the future.

**Comment by olonho** [comment]
This is an internal compiler error, failed assertion, not regular compilation error, so not sure if we could have very good diagnostics here.
