### ISSUE TITLE
Compiler crash "Global already exists" with suspending lambdas in properties

### ISSUE THREAD

**Issue by Tobi29** [JetBrains/kotlin-native#2126]
Declaring two properties like
```Kotlin
val things = sequence { yield("1") }
```
and
```Kotlin
val stuff = sequence { yield("A") }
```
in two different files (but same package) causes a compiler crash:
```
error: compilation failed: Global 'ktype:$lambda-0$0' already exists

 * Source files: Program.kt, Stuff.kt
 * Compiler version info: Konan: 0.9.3-dev / Kotlin: 1.3.0
 * Output kind: PROGRAM

exception: java.lang.IllegalArgumentException: Global 'ktype:$lambda-0$0' already exists
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.createClassDeclarations(LlvmDeclarations.kt:246)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitClass(LlvmDeclarations.kt:204)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitClass(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitClass(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:102)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:79)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitElement(LlvmDeclarations.kt:200)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitPackageFragment(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFile(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFile(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.backend.konan.llvm.DeclarationsGeneratorVisitor.visitFile(LlvmDeclarations.kt:145)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:76)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:45)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:251)
        at org.jetbrains.kotlin.backend.konan.llvm.LlvmDeclarationsKt.createLlvmDeclarations(LlvmDeclarations.kt:23)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:95)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:95)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:94)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:38)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:212)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:203)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:205)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:217)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```
As far as I can tell this only happens with suspending lambdas.

Files to reproduce the problem:
[konan-bug.tar.gz](https://github.com/JetBrains/kotlin-native/files/2410258/konan-bug.tar.gz)

Tested with a174e6544bf10080b0afeb164e987ea65ef7b672.

**Comment by homuroll** [comment]
Fixed in master.
