### ISSUE TITLE
Printing IR tree fails on classes with generic constructor parameters

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#2163]
```
~/.konan/kotlin-native-macos-0.9.3|⇒ bat Hello.kt
───────┬──────────────────────────────────────────────────────────────────────────────────────
       │ File: Hello.kt
───────┼──────────────────────────────────────────────────────────────────────────────────────
   1   │ data class Data<T>(val name: String, val id: Int = 42, val t: T? = null)
   2   │
   3   │ fun main(args: Array<String>) {
   4   │     val data = Data("a", 42, "b")
   5   │     println("Hello, $data!")
   6   │ }
───────┴──────────────────────────────────────────────────────────────────────────────────────
~/.konan/kotlin-native-macos-0.9.3|⇒ bin/kotlinc Hello.kt -Xprint-ir-with-descriptors

... some ir output ...

--- IR after: Default Parameter Extent Lowering ----------------------

... a little bit more ir output ...

error: compilation failed: org.jetbrains.kotlin.ir.expressions.impl.IrDelegatingConstructorCallImpl@39b626e5: No such type argument slot: 0

 * Source files: Hello.kt
 * Compiler version info: Konan: 0.9.3 / Kotlin: 1.3.0
 * Output kind: PROGRAM

exception: java.lang.AssertionError: org.jetbrains.kotlin.ir.expressions.impl.IrDelegatingConstructorCallImpl@39b626e5: No such type argument slot: 0
	at org.jetbrains.kotlin.ir.expressions.impl.IrMemberAccessExpressionBase.getTypeArgument(IrMemberAccessExpressionBase.kt:44)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpressionKt.getTypeArgument(IrMemberAccessExpression.kt:32)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.dumpTypeArguments(DumpIrTreeWithDescriptorsVisitor.kt:287)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitMemberAccess(DumpIrTreeWithDescriptorsVisitor.kt:275)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitMemberAccess(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunctionAccess(IrElementVisitor.kt:75)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitFunctionAccess(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitFunctionAccess(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitDelegatingConstructorCall(IrElementVisitor.kt:77)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitDelegatingConstructorCall(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitDelegatingConstructorCall(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.expressions.impl.IrDelegatingConstructorCallImpl.accept(IrDelegatingConstructorCallImpl.kt:67)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.acceptChildren(IrBlockBodyImpl.kt:44)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.dumpLabeledSubTree(DumpIrTreeWithDescriptorsVisitor.kt:354)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitElement(DumpIrTreeWithDescriptorsVisitor.kt:216)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitElement(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBody(IrElementVisitor.kt:45)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitBody(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitBody(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlockBody(IrElementVisitor.kt:47)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitBlockBody(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitBlockBody(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.accept(IrBlockBodyImpl.kt:40)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitFunctionWithParameters(DumpIrTreeWithDescriptorsVisitor.kt:262)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitConstructor(DumpIrTreeWithDescriptorsVisitor.kt:247)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitConstructor(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.declarations.impl.IrConstructorImpl.accept(IrConstructorImpl.kt:90)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.acceptChildren(IrClassImpl.kt:107)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.dumpLabeledSubTree(DumpIrTreeWithDescriptorsVisitor.kt:354)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitElement(DumpIrTreeWithDescriptorsVisitor.kt:216)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitElement(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitDeclaration(IrElementVisitor.kt:30)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitDeclaration(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitDeclaration(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitClass(IrElementVisitor.kt:31)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitClass(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitClass(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:102)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitFile(DumpIrTreeWithDescriptorsVisitor.kt:229)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitFile(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:76)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:45)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.dumpLabeledSubTree(DumpIrTreeWithDescriptorsVisitor.kt:354)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitElement(DumpIrTreeWithDescriptorsVisitor.kt:216)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitElement(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitModuleFragment(IrElementVisitor.kt:25)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitModuleFragment(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.backend.common.DumpIrTreeWithDescriptorsVisitor.visitModuleFragment(DumpIrTreeWithDescriptorsVisitor.kt:204)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:42)
	at org.jetbrains.kotlin.backend.konan.Context.printIrWithDescriptors(Context.kt:420)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:152)
	at org.jetbrains.kotlin.backend.konan.KonanLower.lowerFile(KonanLower.kt:115)
	at org.jetbrains.kotlin.backend.konan.KonanLower.lower(KonanLower.kt:31)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$1.invoke(KonanDriver.kt:90)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$1.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:89)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:38)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:212)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:203)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:205)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by SvyatoslavScherbina** [comment]
Obsolete. `-Xprint-ir-with-descriptors` is no longer supported, `-Xprint-ir` works ok for this code.
