### ISSUE TITLE
Creating lambda object inside let produces exception: java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@6df11e91

### ISSUE THREAD

**Issue by lukaville** [JetBrains/kotlin-native#2179]
Compiler version: kotlin-native-macos-0.9.3

1. Create file `test.kt`:
```kotlin
fun someFunction() {
    123?.let {
        object : () -> Unit {
            override fun invoke() = Unit
        }
    }
}

fun main() {

}
```

2. Execute `konanc -o test test.kt`

* **Expected result:**  successful compilation
* **Actual result:**  java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@6df11e91

_Note:_ if you change `123?.let` to `123.let` everything works fine.

Full stacktrace:
```
konanc -o test test.kt
error: compilation failed: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@6df11e91

 * Source files: test.kt
 * Compiler version info: Konan: 0.9.3 / Kotlin: 1.3.0
 * Output kind: PROGRAM

exception: java.lang.IllegalStateException: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@6df11e91
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmDeclarations.forFunction(LlvmDeclarations.kt:44)
	at org.jetbrains.kotlin.backend.konan.llvm.ContextUtils$DefaultImpls.getLlvmFunction(ContextUtils.kt:164)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.getLlvmFunction(CodeGenerator.kt:26)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGenerator.llvmFunction(CodeGenerator.kt:28)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt:125)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$4.invoke(IrToBitcode.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:119)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:95)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:94)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:38)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:212)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:203)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:205)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by homuroll** [comment]
Fixed in master.
