### ISSUE TITLE
error: compilation failed: Unexpected file extension: DS_Store

### ISSUE THREAD

**Issue by dinuchiriac** [JetBrains/kotlin-native#2228]
Just downloaded the last build of kotlin-native from the release page and I'm trying to build the "hello kotlin" example from the tutorials page:
https://kotlinlang.org/docs/tutorials/native/basic-kotlin-native-app.html#obtaining-the-compiler
hello.kt
```
fun main(args: Array<String>) {
    println("Hello Kotlin/Native!")
}
```

I'm running MacOS Mojave 10.14 (18A391)
I'm getting the following error when trying to build it:
```
kotlinc-native hello.kt
error: compilation failed: Unexpected file extension: DS_Store

 * Source files: hello.kt
 * Compiler version info: Konan: 0.9.3 / Kotlin: 1.3.0
 * Output kind: PROGRAM

exception: java.lang.IllegalStateException: Unexpected file extension: DS_Store
	at org.jetbrains.kotlin.konan.library.impl.KonanLibraryLayoutImplKt.zippedKonanLibraryChecks(KonanLibraryLayoutImpl.kt:40)
	at org.jetbrains.kotlin.konan.library.impl.ZippedKonanLibraryLayout.<init>(KonanLibraryLayoutImpl.kt:18)
	at org.jetbrains.kotlin.konan.library.impl.KonanLibraryLayoutImplKt.createKonanLibraryLayout(KonanLibraryLayoutImpl.kt:89)
	at org.jetbrains.kotlin.konan.library.impl.KonanLibraryImpl.<init>(KonanLibraryImpl.kt:25)
	at org.jetbrains.kotlin.konan.library.KonanLibraryUtilsKt.createKonanLibrary(KonanLibraryUtils.kt:49)
	at org.jetbrains.kotlin.konan.library.KonanLibraryUtilsKt.createKonanLibrary$default(KonanLibraryUtils.kt:48)
	at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver$resolve$matching$1.invoke(SearchPathResolver.kt:190)
	at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver$resolve$matching$1.invoke(SearchPathResolver.kt:171)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:134)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:158)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:126)
	at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver.resolve(SearchPathResolver.kt:194)
	at org.jetbrains.kotlin.konan.library.KonanLibrarySearchPathResolver.defaultLinks(SearchPathResolver.kt:163)
	at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.findLibraries(KonanLibraryResolverImpl.kt:36)
	at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.resolveWithDependencies(KonanLibraryResolverImpl.kt:16)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:94)
	at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.getResolvedLibraries$backend_native_compiler(KonanConfig.kt)
	at org.jetbrains.kotlin.backend.konan.TopDownAnalyzerFacadeForKonan.analyzeFiles(TopDownAnalyzerFacadeForKonan.kt:43)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1$1.invoke(KonanDriver.kt:47)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1$1.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1.invoke(KonanDriver.kt:46)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:44)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:38)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:212)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:203)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:205)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

It might be something trivial simple to fix however cannot find any threads related to the issue.

**Comment by alexander-gorshenev** [comment]
There seems to be a `.DS_Store` file left over in the `klib` directory of your distribution somewhere.
https://en.wikipedia.org/wiki/.DS_Store
It seem to confuse the compiler. Just find and remove it.

**Comment by dinuchiriac** [comment]
Sorted,  all good after deleting all `.DS_Store` from the `kotlin-native` directory. 
```
find . -name \*.DS_Store -type f -delete
```
Thanks @alexander-gorshenev
