### ISSUE TITLE
Assertion failed when using Koltin-Native with Ktor on Ios

### ISSUE THREAD

**Issue by salztorte** [JetBrains/kotlin-native#2240]
I'm using the 'kotlin-platform-native' gradle plugin
Kotlin: 1.3.0-rc-146
Gradle: 4.7
Ktor: 1.0.0-beta-1

Android works fine but every time i try to build the ios framework it failed.
If i remove Ktor everything works fine.

I already create a Issue in the Ktor repo https://github.com/ktorio/ktor/issues/658

Some Ideas about that?
```
* Compiler version info: Konan: 0.9.3 / Kotlin: 1.3.0

Output kind: FRAMEWORK
exception: java.lang.AssertionError: Assertion failed
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateClassName(ObjCExportHeaderGenerator.kt:303)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReferenceTypeIgnoringNullability$backend_native_compiler(ObjCExportHeaderGenerator.kt:855)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReferenceType$backend_native_compiler(ObjCExportHeaderGenerator.kt:797)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapType(ObjCExportHeaderGenerator.kt:892)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.mapReturnType(ObjCExportHeaderGenerator.kt:754)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.buildMethod(ObjCExportHeaderGenerator.kt:687)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translatePlainMembers(ObjCExportHeaderGenerator.kt:547)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateBaseMembers(ObjCExportHeaderGenerator.kt:534)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateInterfaceMembers(ObjCExportHeaderGenerator.kt:465)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateInterface(ObjCExportHeaderGenerator.kt:313)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.access$translateInterface(ObjCExportHeaderGenerator.kt:26)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$superProtocols$2.invoke(ObjCExportHeaderGenerator.kt:327)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$superProtocols$2.invoke(ObjCExportHeaderGenerator.kt:26)
at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:685)
at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:715)
at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:706)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.getSuperProtocols(ObjCExportHeaderGenerator.kt:330)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateInterface(ObjCExportHeaderGenerator.kt:314)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateModule(ObjCExportHeaderGenerator.kt:234)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produceFrameworkSpecific(ObjCExport.kt:68)
at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produce$backend_native_compiler(ObjCExport.kt:41)
at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:382)
at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:291)
at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:291)
at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:42)
at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:247)
at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$7.invoke(IrToBitcode.kt:162)
at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt$emitLLVM$7.invoke(IrToBitcode.kt)
at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:161)
at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt:95)
at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$2.invoke(KonanDriver.kt)
at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:94)
at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:135)
at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:109)
at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:134)
at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:82)
at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:38)
at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:212)
at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:203)
at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:205)
at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:217)
at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by olonho** [comment]
Not enough info, we need to see sources that triggers such behavior.

**Comment by Syrou** [comment]
@olonho Have the samme issue, i'll chip in with what information I can provide
```
kotlin_version=1.3.0-rc-190
org.jetbrains.kotlin.native.version=0.9.3
Coroutines uses version: 0.30.2-eap13
Serialization uses version: 0.8.2-rc13
Ktor uses version: 1.0.0-beta-1
```
A common code with the following code:

```
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.features.json.serializer.KotlinxSerializer
import kotlin.coroutines.CoroutineContext

class RestClient(private val uiContext: CoroutineContext,
                val baseURL: String = "https://yourcoolserver.com") {

    val client = io.ktor.client.HttpClient {
        install(JsonFeature) {
            serializer = KotlinxSerializer().apply {
            }
        }
    }

}
```

Will produce the error described above

**Comment by Syrou** [comment]
@olonho Updated the code above incase you started reading the old post I did

**Comment by Syrou** [comment]
If i bump coroutines to use version 1.0.0-RC1 I get this following error instead:
```
Undefined symbols for architecture x86_64:
  "_kfun:kotlinx.coroutines.CoroutineScope.<get-isActive>()ValueType", referenced from:
      _kmethods:io.ktor.client.call.HttpClientCall in combined.o
ld: symbol(s) not found for architecture x86_64
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
```

**Comment by russhwolf** [comment]
I'm seeing this as well. If you need more sources here's my repro as a diff on a new project based on the multiplatform android/ios template: [link](https://github.com/russhwolf/ktor-demo/compare/c60065de44782149e77288f7a346bd13506d39b9...master)

**Comment by Syrou** [comment]
@russhwolf Tried to see if that repo had direct dependency on HttpResponse as well, but it does not seem it has that, so this error maybe it not souly from using/importing HttpResponse

**Comment by dcoletto** [comment]
@olonho is there any ETA about this new release? Or at least if we need to wait days/weeks/months (just to understand if it makes sense to find a workaround or not)

**Comment by antanas-arvasevicius** [comment]
Hi,
maybe this could help: https://github.com/ktorio/ktor/issues/668#issuecomment-432287025
Just use jitpack for unreleased ktor with coroutines v1.0.0

**Comment by dcoletto** [comment]
Actually I'm trying to use it but I can't find the correct artifact for ktor-client

**Comment by antanas-arvasevicius** [comment]
Oh, for Kotlin Native maybe is completely different

**Comment by russhwolf** [comment]
Updating ktor to 1.0.0-beta-2 appears to fix the compiler error for my demo project
