### ISSUE TITLE
MalformedInputException on any Kotlin file

### ISSUE THREAD

**Issue by iamareebjamal** [JetBrains/kotlin-native#2307]
Regression in 1.3.31: https://github.com/JetBrains/kotlin-native/issues/2307#issuecomment-488327556

Using this release https://github.com/JetBrains/kotlin-native/releases/tag/v1.0.1, I cannot get any code compiled, with either kotlinc or kotlinc native(even hello world). It always fails with this output:

```
exception: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at java.base/java.io.Reader.read(Reader.java:229)
	at java.base/java.util.Properties$LineReader.readLine(Properties.java:497)
	at java.base/java.util.Properties.load0(Properties.java:416)
	at java.base/java.util.Properties.load(Properties.java:378)
	at org.jetbrains.kotlin.konan.properties.PropertiesKt.loadProperties(Properties.kt:28)
	at org.jetbrains.kotlin.konan.target.Distribution$properties$2.invoke(Distribution.kt:64)
	at org.jetbrains.kotlin.konan.target.Distribution$properties$2.invoke(Distribution.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.konan.target.Distribution.getProperties(Distribution.kt)
	at org.jetbrains.kotlin.konan.target.PlatformManager.<init>(Platform.kt:35)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:36)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:60)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:211)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:202)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:204)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:256)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)

```

**Comment by iamareebjamal** [comment]
https://github.com/JetBrains/kotlin/releases/download/v1.3.0/kotlin-native-linux-1.3.0.tar.gz

From this tar, I used kotlinc, kotlinc-native, konanc. Basically tried everything

**Comment by olonho** [comment]
Please try to download same binary again, seems it was corrupted.

**Comment by iamareebjamal** [comment]
Works now, thanks

**Comment by boonshift** [comment]
Seems to be same problem happening now with https://github.com/JetBrains/kotlin/releases/download/v1.3.31/kotlin-native-linux-1.3.31.tar.gz

**Comment by EXL** [comment]
@boonshift I can confirm I encountered a similar problem. 

There is no bug in v1.3.30

**Comment by odilonjk** [comment]
I found the same problem using **v1.3.31**.

Confirmed that it doesn't happen in **v1.3.30**, like @EXL said.

**Comment by Sfinx** [comment]
same here with v1.3.31

**Comment by DeadNumbers** [comment]
same on `kotlinc-native 1.3.31 (JRE 10.0.2+13)`

**Comment by pkos98** [comment]
Can confirm this behaviour using `kotlinc-native 1.3.31 (JRE 10.0.2+13)`

**Comment by KaenDagger** [comment]
I am facing same problem with `kotlinc-native 1.3.31 (JRE 10.0.2+13)`

**Comment by olonho** [comment]
Shall be fixed, please redownload the distro. For cursious, problem was arising from https://superuser.com/questions/61185/why-do-i-get-files-like-foo-in-my-tarball-on-os-x/61188#61188 and the fact that GNU tar unpacks extended attributes as regular files.
