### ISSUE TITLE
Compiler error when compiling crossline lambdas: "Cause: Captured field not found"

### ISSUE THREAD

**Issue by SiraWiz** [JetBrains/kotlin-native#2419]
Not related to Android, but you may note that the below is happening in an Android Studio environment.

I have several inlined extension functions, each accept 2 crossline lambdas:

The first function:
```kotlin
inline fun Context.createAlertDialog(title: String? = null,
                                     message: String?,
                                     positiveButtonText: String? = null,
                                     negativeButtonText: String? = null,
                                     crossinline onPositiveButtonClick: (() -> Unit) = {},
                                     crossinline onNegativeButtonClick: (() -> Unit) = {}): AlertDialog {
    val builder = AlertDialog.Builder(this)
    if (title != null) builder.setTitle(title)
    builder.setMessage(message)
    if (positiveButtonText != null) builder.setPositiveButton(positiveButtonText) { _, _ ->
        onPositiveButtonClick.invoke()
    }
    if (negativeButtonText != null) builder.setNegativeButton(negativeButtonText) { _, _ ->
        onNegativeButtonClick.invoke()
    }
    return builder.create()
}
```

And another extension function which makes use of the above one:
```kotlin
inline fun Context.showLocationServiceDialog(crossinline positiveOnClickListener: () -> Unit = {},
                                             crossinline negativeOnClickListener: () -> Unit = {}) {
    createAlertDialog(null, getString(R.string.General_Turn_On_Location_Dialog_Message),
            getString(R.string.General_Ok), getString(R.string.General_Cancel), positiveOnClickListener, negativeOnClickListener)
            .show()
}
```

And one more extension function which makes use of the above one:
```kotlin
inline fun Activity.showLocationRequest(crossinline positiveOnClickListener: () -> Unit = {},
                                        crossinline negativeOnClickListener: () -> Unit = {}) {
    val googleApiClient = GoogleApiClient.Builder(this).addApi(LocationServices.API).build()
    googleApiClient.connect()

    val locationRequest = LocationRequest.create()
    locationRequest.priority = LocationRequest.PRIORITY_LOW_POWER
    locationRequest.interval = 60000
    locationRequest.fastestInterval = (60000 / 2).toLong()

    val builder = LocationSettingsRequest.Builder().addLocationRequest(locationRequest)
    builder.setAlwaysShow(true)

    val result = LocationServices.SettingsApi.checkLocationSettings(googleApiClient, builder.build())
    result.setResultCallback { locationSettingsResult ->
        val status = locationSettingsResult.status
        when (status.statusCode) {
            LocationSettingsStatusCodes.SUCCESS -> {
            }
            LocationSettingsStatusCodes.RESOLUTION_REQUIRED -> try {
                // Show the dialog by calling startResolutionForResult(), and check the result
                // in onActivityResult().
                status.startResolutionForResult(this, Constants.REQUEST_CODES.CHECK_LOCATION_SETTINGS)
            } catch (e: IntentSender.SendIntentException) {
                showLocationServiceDialog(positiveOnClickListener, negativeOnClickListener)
            }

            LocationSettingsStatusCodes.SETTINGS_CHANGE_UNAVAILABLE ->
                //Try old method, bring user to settings
                showLocationServiceDialog(positiveOnClickListener, negativeOnClickListener)
        }//Good, do nothing
    }
}
```

Finally I call `showLocationRequest()` in another class:
```kotlin
    override fun showTurnOnLocationDialog() {
        activity?.showLocationRequest(positiveOnClickListener = {
            activity?.startActivity(Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS))
        })
    }
```

When I try to build the project, gradle gives me a long error:
```
e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Couldn't inline method call 'showLocationRequest' into
public open fun showTurnOnLocationDialog(): kotlin.Unit defined in ***.***.***.*****.*******.****.****Fragment
override fun showTurnOnLocationDialog() {
        activity?.showLocationRequest(positiveOnClickListener = {
            activity?.startActivity(Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS))
        })
    }
Cause: showLocationRequest$default (Landroid/app/Activity;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V:
   L0
   L1
   L2
    LINENUMBER 15 L2
    INVOKESTATIC $$$DEFAULT_LAMBDA_FAKE_CALL$$$.$$$DEFAULT_LAMBDA_FAKE_CALL$$$2 ()V
   L3
   L4
   L5
    ALOAD 0
    LDC "$receiver"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 1
    LDC "positiveOnClickListener"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 2
    LDC "negativeOnClickListener"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L6
    LINENUMBER 48 L6
    NEW com/google/android/gms/common/api/GoogleApiClient$Builder
    DUP
    ALOAD 0
    CHECKCAST android/content/Context
    INVOKESPECIAL com/google/android/gms/common/api/GoogleApiClient$Builder.<init> (Landroid/content/Context;)V
    GETSTATIC com/google/android/gms/location/LocationServices.API : Lcom/google/android/gms/common/api/Api;
    INVOKEVIRTUAL com/google/android/gms/common/api/GoogleApiClient$Builder.addApi (Lcom/google/android/gms/common/api/Api;)Lcom/google/android/gms/common/api/GoogleApiClient$Builder;
    INVOKEVIRTUAL com/google/android/gms/common/api/GoogleApiClient$Builder.build ()Lcom/google/android/gms/common/api/GoogleApiClient;
    ASTORE 4
   L7
   L8
    LINENUMBER 49 L8
    ALOAD 4
    INVOKEVIRTUAL com/google/android/gms/common/api/GoogleApiClient.connect ()V
   L9
    LINENUMBER 51 L9
    INVOKESTATIC com/google/android/gms/location/LocationRequest.create ()Lcom/google/android/gms/location/LocationRequest;
    ASTORE 5
   L10
   L11
    LINENUMBER 52 L11
    ALOAD 5
    DUP
    LDC "locationRequest"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    BIPUSH 104
    INVOKEVIRTUAL com/google/android/gms/location/LocationRequest.setPriority (I)Lcom/google/android/gms/location/LocationRequest;
    POP
   L12
    LINENUMBER 53 L12
    ALOAD 5
    DUP
    LDC "locationRequest"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    LDC 60000
    INVOKEVIRTUAL com/google/android/gms/location/LocationRequest.setInterval (J)Lcom/google/android/gms/location/LocationRequest;
    POP
   L13
    LINENUMBER 54 L13
    ALOAD 5
    DUP
    LDC "locationRequest"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    SIPUSH 30000
    I2L
    INVOKEVIRTUAL com/google/android/gms/location/LocationRequest.setFastestInterval (J)Lcom/google/android/gms/location/LocationRequest;
    POP
   L14
    LINENUMBER 56 L14
    NEW com/google/android/gms/location/LocationSettingsRequest$Builder
    DUP
    INVOKESPECIAL com/google/android/gms/location/LocationSettingsRequest$Builder.<init> ()V
    ALOAD 5
    INVOKEVIRTUAL com/google/android/gms/location/LocationSettingsRequest$Builder.addLocationRequest (Lcom/google/android/gms/location/LocationRequest;)Lcom/google/android/gms/location/LocationSettingsRequest$Builder;
    ASTORE 6
   L15
   L16
    LINENUMBER 57 L16
    ALOAD 6
    ICONST_1
    INVOKEVIRTUAL com/google/android/gms/location/LocationSettingsRequest$Builder.setAlwaysShow (Z)Lcom/google/android/gms/location/LocationSettingsRequest$Builder;
    POP
   L17
    LINENUMBER 59 L17
    GETSTATIC com/google/android/gms/location/LocationServices.SettingsApi : Lcom/google/android/gms/location/SettingsApi;
    ALOAD 4
    ALOAD 6
    INVOKEVIRTUAL com/google/android/gms/location/LocationSettingsRequest$Builder.build ()Lcom/google/android/gms/location/LocationSettingsRequest;
    INVOKEINTERFACE com/google/android/gms/location/SettingsApi.checkLocationSettings (Lcom/google/android/gms/common/api/GoogleApiClient;Lcom/google/android/gms/location/LocationSettingsRequest;)Lcom/google/android/gms/common/api/PendingResult;
    ASTORE 7
   L18
   L19
    LINENUMBER 60 L19
    ALOAD 7
    NEW ***/***/***utils/extensions/ActivityExtensionsKt$showLocationRequest$3
    DUP
    ALOAD 0
    ALOAD 1
    ALOAD 2
    INVOKESPECIAL ***/***/***utils/extensions/ActivityExtensionsKt$showLocationRequest$3.<init> (Landroid/app/Activity;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function0;)V
    CHECKCAST com/google/android/gms/common/api/ResultCallback
    INVOKEVIRTUAL com/google/android/gms/common/api/PendingResult.setResultCallback (Lcom/google/android/gms/common/api/ResultCallback;)V
   L20
    LINENUMBER 61 L20
    RETURN
   L21
    RETURN
    LOCALVARIABLE result Lcom/google/android/gms/common/api/PendingResult; L18 L21 7
    LOCALVARIABLE builder Lcom/google/android/gms/location/LocationSettingsRequest$Builder; L15 L21 6
    LOCALVARIABLE locationRequest Lcom/google/android/gms/location/LocationRequest; L10 L21 5
    LOCALVARIABLE googleApiClient Lcom/google/android/gms/common/api/GoogleApiClient; L7 L21 4
    LOCALVARIABLE $receiver Landroid/app/Activity; L0 L21 0
    LOCALVARIABLE positiveOnClickListener Lkotlin/jvm/functions/Function0; L0 L21 1
    LOCALVARIABLE negativeOnClickListener Lkotlin/jvm/functions/Function0; L3 L21 2
    LOCALVARIABLE $i$f$showLocationRequest I L4 L21 3
    MAXSTACK = 6
    MAXLOCALS = 8

Cause: Captured field not found: /***/***/***/****Fragment.kt$showTurnOnLocationDialog$1.this$0
File being compiled at position: (151,19) in /***/***/***/***/***/app/src/main/java/***/***/***/****Fragment.kt
The root cause was thrown at: LambdaInfo.kt:56
File being compiled at position: file:////***/***/***/***/***/app/src/main/java/***/***/***/****Fragment.kt
The root cause was thrown at: InlineCodegen.kt:124
	at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:446)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:142)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:223)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:38)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:89)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:597)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:454)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1020)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1062)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1019)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:453)
	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'showLocationRequest' into
public open fun showTurnOnLocationDialog(): kotlin.Unit defined in ***.***.***.*****.*******.****.****Fragment
override fun showTurnOnLocationDialog() {
        activity?.showLocationRequest(positiveOnClickListener = {
            activity?.startActivity(Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS))
        })
    }
Cause: showLocationRequest$default (Landroid/app/Activity;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V:
   L0
   L1
   L2
    LINENUMBER 15 L2
    INVOKESTATIC $$$DEFAULT_LAMBDA_FAKE_CALL$$$.$$$DEFAULT_LAMBDA_FAKE_CALL$$$2 ()V
   L3
   L4
   L5
    ALOAD 0
    LDC "$receiver"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 1
    LDC "positiveOnClickListener"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 2
    LDC "negativeOnClickListener"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L6
    LINENUMBER 48 L6
    NEW com/google/android/gms/common/api/GoogleApiClient$Builder
    DUP
    ALOAD 0
    CHECKCAST android/content/Context
    INVOKESPECIAL com/google/android/gms/common/api/GoogleApiClient$Builder.<init> (Landroid/content/Context;)V
    GETSTATIC com/google/android/gms/location/LocationServices.API : Lcom/google/android/gms/common/api/Api;
    INVOKEVIRTUAL com/google/android/gms/common/api/GoogleApiClient$Builder.addApi (Lcom/google/android/gms/common/api/Api;)Lcom/google/android/gms/common/api/GoogleApiClient$Builder;
    INVOKEVIRTUAL com/google/android/gms/common/api/GoogleApiClient$Builder.build ()Lcom/google/android/gms/common/api/GoogleApiClient;
    ASTORE 4
   L7
   L8
    LINENUMBER 49 L8
    ALOAD 4
    INVOKEVIRTUAL com/google/android/gms/common/api/GoogleApiClient.connect ()V
   L9
    LINENUMBER 51 L9
    INVOKESTATIC com/google/android/gms/location/LocationRequest.create ()Lcom/google/android/gms/location/LocationRequest;
    ASTORE 5
   L10
   L11
    LINENUMBER 52 L11
    ALOAD 5
    DUP
    LDC "locationRequest"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    BIPUSH 104
    INVOKEVIRTUAL com/google/android/gms/location/LocationRequest.setPriority (I)Lcom/google/android/gms/location/LocationRequest;
    POP
   L12
    LINENUMBER 53 L12
    ALOAD 5
    DUP
    LDC "locationRequest"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    LDC 60000
    INVOKEVIRTUAL com/google/android/gms/location/LocationRequest.setInterval (J)Lcom/google/android/gms/location/LocationRequest;
    POP
   L13
    LINENUMBER 54 L13
    ALOAD 5
    DUP
    LDC "locationRequest"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    SIPUSH 30000
    I2L
    INVOKEVIRTUAL com/google/android/gms/location/LocationRequest.setFastestInterval (J)Lcom/google/android/gms/location/LocationRequest;
    POP
   L14
    LINENUMBER 56 L14
    NEW com/google/android/gms/location/LocationSettingsRequest$Builder
    DUP
    INVOKESPECIAL com/google/android/gms/location/LocationSettingsRequest$Builder.<init> ()V
    ALOAD 5
    INVOKEVIRTUAL com/google/android/gms/location/LocationSettingsRequest$Builder.addLocationRequest (Lcom/google/android/gms/location/LocationRequest;)Lcom/google/android/gms/location/LocationSettingsRequest$Builder;
    ASTORE 6
   L15
   L16
    LINENUMBER 57 L16
    ALOAD 6
    ICONST_1
    INVOKEVIRTUAL com/google/android/gms/location/LocationSettingsRequest$Builder.setAlwaysShow (Z)Lcom/google/android/gms/location/LocationSettingsRequest$Builder;
    POP
   L17
    LINENUMBER 59 L17
    GETSTATIC com/google/android/gms/location/LocationServices.SettingsApi : Lcom/google/android/gms/location/SettingsApi;
    ALOAD 4
    ALOAD 6
    INVOKEVIRTUAL com/google/android/gms/location/LocationSettingsRequest$Builder.build ()Lcom/google/android/gms/location/LocationSettingsRequest;
    INVOKEINTERFACE com/google/android/gms/location/SettingsApi.checkLocationSettings (Lcom/google/android/gms/common/api/GoogleApiClient;Lcom/google/android/gms/location/LocationSettingsRequest;)Lcom/google/android/gms/common/api/PendingResult;
    ASTORE 7
   L18
   L19
    LINENUMBER 60 L19
    ALOAD 7
    NEW ***/***/***utils/extensions/ActivityExtensionsKt$showLocationRequest$3
    DUP
    ALOAD 0
    ALOAD 1
    ALOAD 2
    INVOKESPECIAL ***/***/***utils/extensions/ActivityExtensionsKt$showLocationRequest$3.<init> (Landroid/app/Activity;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function0;)V
    CHECKCAST com/google/android/gms/common/api/ResultCallback
    INVOKEVIRTUAL com/google/android/gms/common/api/PendingResult.setResultCallback (Lcom/google/android/gms/common/api/ResultCallback;)V
   L20
    LINENUMBER 61 L20
    RETURN
   L21
    RETURN
    LOCALVARIABLE result Lcom/google/android/gms/common/api/PendingResult; L18 L21 7
    LOCALVARIABLE builder Lcom/google/android/gms/location/LocationSettingsRequest$Builder; L15 L21 6
    LOCALVARIABLE locationRequest Lcom/google/android/gms/location/LocationRequest; L10 L21 5
    LOCALVARIABLE googleApiClient Lcom/google/android/gms/common/api/GoogleApiClient; L7 L21 4
    LOCALVARIABLE $receiver Landroid/app/Activity; L0 L21 0
    LOCALVARIABLE positiveOnClickListener Lkotlin/jvm/functions/Function0; L0 L21 1
    LOCALVARIABLE negativeOnClickListener Lkotlin/jvm/functions/Function0; L3 L21 2
    LOCALVARIABLE $i$f$showLocationRequest I L4 L21 3
    MAXSTACK = 6
    MAXLOCALS = 8

Cause: Captured field not found: /***/***/***/****Fragment.kt$showTurnOnLocationDialog$1.this$0
File being compiled at position: (151,19) in /***/***/***/***/***/app/src/main/java/***/***/***/****Fragment.kt
The root cause was thrown at: LambdaInfo.kt:56
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.throwCompilationException(InlineCodegen.kt:124)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:164)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCallInner(InlineCodegen.kt:679)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultImpls.genCall(CallGenerator.kt:114)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCall(InlineCodegen.kt:660)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2428)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2371)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.CoercionValue.putSelector(StackValue.kt:31)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:112)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:101)
	at org.jetbrains.kotlin.codegen.StackValue$StackValueWithSimpleReceiver.putReceiver(StackValue.java:1911)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putReceiver(StackValue.kt:63)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:110)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:101)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:350)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:335)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1644)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:84)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:678)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:434)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:265)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:182)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:153)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:196)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:155)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:75)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:128)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassOrObject(PackageCodegenImpl.java:161)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:86)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	... 43 more
Caused by: java.lang.IllegalStateException: Captured field not found: /***/***/***/****Fragment.kt$showTurnOnLocationDialog$1.this$0
	at org.jetbrains.kotlin.codegen.inline.LambdaInfo.addAllParameters(LambdaInfo.kt:56)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.visitMethodInsn(MethodInliner.kt:267)
	at org.jetbrains.org.objectweb.asm.tree.MethodInsnNode.accept(MethodInsnNode.java:133)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:385)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:99)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:72)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethod(AnonymousObjectTransformer.kt:317)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethodAndUpdateGlobalResult(AnonymousObjectTransformer.kt:281)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.doTransform(AnonymousObjectTransformer.kt:166)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.handleAnonymousObjectRegeneration(MethodInliner.kt:178)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.anew(MethodInliner.kt:203)
	at org.jetbrains.org.objectweb.asm.commons.InstructionAdapter.visitTypeInsn(InstructionAdapter.java:478)
	at org.jetbrains.org.objectweb.asm.tree.TypeInsnNode.accept(TypeInsnNode.java:83)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:385)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:99)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:72)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethod(AnonymousObjectTransformer.kt:317)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.inlineMethodAndUpdateGlobalResult(AnonymousObjectTransformer.kt:281)
	at org.jetbrains.kotlin.codegen.inline.AnonymousObjectTransformer.doTransform(AnonymousObjectTransformer.kt:166)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.handleAnonymousObjectRegeneration(MethodInliner.kt:178)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner$doInline$lambdaInliner$1.anew(MethodInliner.kt:203)
	at org.jetbrains.org.objectweb.asm.commons.InstructionAdapter.visitTypeInsn(InstructionAdapter.java:478)
	at org.jetbrains.org.objectweb.asm.tree.TypeInsnNode.accept(TypeInsnNode.java:83)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:385)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:99)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:72)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:277)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:158)
	... 78 more
```

## What I observed

1. Reducing the chained crossline argument from 3 functions to 2 will succeed the build;
2. Commenting out the usage of crossline arguments in the first extension function will succeed the build (And! if I uncomment and build again, the build will succeed; but if I clean and build again it will fail.);
3. If I do not supply any argument (the lambda) from the fragment, the build will succeed

**Comment by olonho** [comment]
Clearly a JVM backend issue, unrelated to native.

**Comment by SiraWiz** [comment]
@olonho Do you mean this is a JVM bug instead of an issue of Kotlin? If that's the case, is there anything that I can do?

**Comment by sbogolepov** [comment]
@SiraWiz This repository is only for Kotlin/Native project. To report an issue about Kotlin/JVM please use [YouTrack](https://youtrack.jetbrains.com/issues/KT).

**Comment by SiraWiz** [comment]
Oh sorry, I didn't understand the difference. Thanks!
