### ISSUE TITLE
Segmentation Fault in FreezeSubgraph when accessing enum .get

### ISSUE THREAD

**Issue by novocaine** [JetBrains/kotlin-native#2441]
Hi,

I am loading a Kotlin native .so in Python using CFFI.

```
info: kotlinc-native 1.3.0-rc-190 (JRE 11.0.1+13-Debian-2)
Kotlin/Native: 1.0.2
```

Generated header:

```
#ifndef KONAN_SUPERCHARGE_H
#define KONAN_SUPERCHARGE_H
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
typedef bool            supercharge_KBoolean;
#else
typedef _Bool           supercharge_KBoolean;
#endif
typedef unsigned short     supercharge_KChar;
typedef signed char        supercharge_KByte;
typedef short              supercharge_KShort;
typedef int                supercharge_KInt;
typedef long long          supercharge_KLong;
typedef unsigned char      supercharge_KUByte;
typedef unsigned short     supercharge_KUShort;
typedef unsigned int       supercharge_KUInt;
typedef unsigned long long supercharge_KULong;
typedef float              supercharge_KFloat;
typedef double             supercharge_KDouble;
typedef void*              supercharge_KNativePtr;
struct supercharge_KType;
typedef struct supercharge_KType supercharge_KType;

typedef struct {
  supercharge_KNativePtr pinned;
} supercharge_kref_Difficulty;
typedef struct {
  supercharge_KNativePtr pinned;
} supercharge_kref_Difficulty_Easy;
typedef struct {
  supercharge_KNativePtr pinned;
} supercharge_kref_Difficulty_Moderate;
typedef struct {
  supercharge_KNativePtr pinned;
} supercharge_kref_Difficulty_Hard;
typedef struct {
  supercharge_KNativePtr pinned;
} supercharge_kref_Supercharge;


typedef struct {
  /* Service functions. */
  void (*DisposeStablePointer)(supercharge_KNativePtr ptr);
  void (*DisposeString)(const char* string);
  supercharge_KBoolean (*IsInstance)(supercharge_KNativePtr ref, const supercharge_KType* type);

  /* User functions. */
  struct {
    struct {
      struct {
        supercharge_KType* (*_type)(void);
        struct {
          supercharge_kref_Difficulty (*get)(); /* enum entry for Easy. */
        } Easy;
        struct {
          supercharge_kref_Difficulty (*get)(); /* enum entry for Moderate. */
        } Moderate;
        struct {
          supercharge_kref_Difficulty (*get)(); /* enum entry for Hard. */
        } Hard;
      } Difficulty;
      struct {
        supercharge_KType* (*_type)(void);
        supercharge_kref_Supercharge (*Supercharge)();
        supercharge_KBoolean (*shouldSupercharge)(supercharge_kref_Supercharge thiz, supercharge_KInt growthLevel, supercharge_kref_Difficulty difficulty);
      } Supercharge;
    } root;
  } kotlin;
} supercharge_ExportedSymbols;
extern supercharge_ExportedSymbols* supercharge_symbols(void);
#ifdef __cplusplus
}  /* extern "C" */
#endif
#endif  /* KONAN_SUPERCHARGE_H */
```

python wrapper:

```
from _supercharge_api import ffi, lib
from enum import Enum

symbols = lib.supercharge_symbols()


def should_supercharge(growth_level, difficulty):
    difficulty_struct = getattr(symbols.kotlin.root.Difficulty, difficulty).get()
    charge = symbols.kotlin.root.Supercharge.Supercharge()
    return symbols.kotlin.root.Supercharge.shouldSupercharge(charge, growth_level, 
            difficulty_struct)

if __name__ == "__main__":
    print(should_supercharge(2, "Easy"))
```

With this order of operations, I receive a crash at `symbols.kotlin.root.Difficulty.get()` with the following trace

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff766f200 in FreezeSubgraph () from /lib/libsupercharge.so
(gdb) bt
#0  0x00007ffff766f200 in FreezeSubgraph () from /lib/libsupercharge.so
#1  0x00007ffff7652867 in kfun:kotlin.native.concurrent.freeze@#GENERIC.()Generic () from /lib/libsupercharge.so
#2  0x00007ffff76509cc in kfun:Difficulty.$OBJECT.<init>()Difficulty.$OBJECT () from /lib/libsupercharge.so
#3  0x00007ffff766f054 in InitSharedInstance () from /lib/libsupercharge.so
#4  0x00007ffff76506e6 in kfun:Difficulty.$OBJECT.$get-VALUES()kotlin.Array<Difficulty> () from /lib/libsupercharge.so
#5  0x00007ffff7650d63 in _konan_function_1 () from /lib/libsupercharge.so
#6  0x00007ffff7650287 in _konan_function_1_impl() () from /lib/libsupercharge.so
#7  0x00007ffff71d3df0 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#8  0x00007ffff71d3858 in ffi_call (cif=cif@entry=0x7ffff76c3b88, fn=0x7ffff7650260 <_konan_function_1_impl()>, rvalue=rvalue@entry=0x7ffff77ea620, avalue=avalue@entry=0x7ffff77ea620) at ../src/x86/ffi64.c:525
#9  0x00007ffff73f1e04 in cdata_call (cd=0x7ffff7711760, args=<optimized out>, kwds=<optimized out>) at c/_cffi_backend.c:3025
#10 0x00000000005d984b in _PyObject_FastCallKeywords ()
#11 0x000000000054a721 in ?? ()
#12 0x0000000000551acc in _PyEval_EvalFrameDefault ()
#13 0x00000000005d8968 in _PyFunction_FastCallKeywords ()
#14 0x000000000054da8c in _PyEval_EvalFrameDefault ()
#15 0x000000000054b012 in _PyEval_EvalCodeWithName ()
#16 0x000000000054d583 in PyEval_EvalCode ()
#17 0x000000000062df62 in ?? ()
#18 0x000000000062e01a in PyRun_FileExFlags ()
#19 0x000000000062ed28 in PyRun_SimpleFileExFlags ()
#20 0x00000000006518c5 in ?? ()
#21 0x00000000006519ee in _Py_UnixMain ()
#22 0x00007ffff7a2209b in __libc_start_main (main=0x4ba980 <main>, argc=2, argv=0x7fffffffecb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffeca8) at ../csu/libc-start.c:308
#23 0x00000000005e02fa in _start ()
```

Interestingly if I change the order of operations to this, everything works fine

```
    charge = symbols.kotlin.root.Supercharge.Supercharge()
    difficulty_struct = getattr(symbols.kotlin.root.Difficulty, difficulty).get()
```

(which is what I'm going to do, but I thought you might appreciate the report). The implication is that `symbols.kotlin.root.Supercharge.Supercharge()` is actually initialising something necessary for 
`symbols.kotlin.root.Difficulty.<difficulty>` to work, which doesn't seem right :)

**Comment by olonho** [comment]
No answer, closing.
