### ISSUE TITLE
NSOutputStream ambiguous constructor

### ISSUE THREAD

**Issue by bedalton** [JetBrains/kotlin-native#2522]
I am trying to use NSOuputStream's no arg constructor, and Kotlin has flagged it in error, because there are two zero-arg constructors in the 003_Foundation.knm I cannot figure out a way to edit the knm file to remove the duplicate constructor. Is this something I can do?

```
 @kotlinx.cinterop.ExternalObjCClass public open class NSOutputStream : platform.Foundation.NSStream {
    public companion object : platform.Foundation.NSOutputStreamMeta, kotlinx.cinterop.ObjCClassOf<platform.Foundation.NSOutputStream> {
    }

    @kotlinx.cinterop.ObjCConstructor public constructor() { /* compiled code */ }

    @kotlinx.cinterop.ObjCConstructor public constructor(toBuffer: kotlinx.cinterop.CPointer<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?, capacity: platform.darwin.NSUInteger /* = kotlin.ULong */) { /* compiled code */ }

    @kotlinx.cinterop.ObjCConstructor public constructor(uRL: platform.Foundation.NSURL, append: kotlin.Boolean) { /* compiled code */ }

    @kotlinx.cinterop.ObjCConstructor public constructor() { /* compiled code */ }

    public final val hasSpaceAvailable: kotlin.Boolean /* compiled code */

    @kotlinx.cinterop.ObjCMethod public open external fun hasSpaceAvailable(): kotlin.Boolean { /* compiled code */ }

    @kotlinx.cinterop.ObjCMethod public open external fun init(): platform.Foundation.NSOutputStream? { /* compiled code */ }

    @kotlinx.cinterop.ObjCMethod public open external fun initToBuffer(buffer: kotlinx.cinterop.CPointer<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?, capacity: platform.darwin.NSUInteger /* = kotlin.ULong */): platform.Foundation.NSOutputStream { /* compiled code */ }

    @kotlinx.cinterop.ObjCMethod public open external fun initToMemory(): platform.Foundation.NSOutputStream { /* compiled code */ }

    @kotlinx.cinterop.ObjCMethod public open external fun initWithURL(url: platform.Foundation.NSURL, append: kotlin.Boolean): platform.Foundation.NSOutputStream? { /* compiled code */ }

    @kotlinx.cinterop.ObjCMethod public open external fun write(buffer: kotlinx.cinterop.CPointer<platform.posix.uint8_tVar /* = kotlinx.cinterop.UByteVarOf<platform.posix.uint8_t /* = kotlin.UByte */> */>?, maxLength: platform.darwin.NSUInteger /* = kotlin.ULong */): platform.darwin.NSInteger /* = kotlin.Long */ { /* compiled code */ }
}
```

**Comment by bedalton** [comment]
This worked. Thank you

**Comment by subprogram** [comment]
I've got the same issue. But the workaround with `outputStreamToMemory` factory method is not working for me because I need to extend `NSOutputStream` by my own kotlin class. I've tried to use another constructor and define my class as `class GZIPOutputStream() : NSOutputStream(NSURL(), false)` but I receive a compilation error in this case:
```
e: java.lang.IllegalArgumentException: Sequence contains more than one matching element.
	at org.jetbrains.kotlin.backend.konan.lower.InteropLoweringPart1.visitDelegatingConstructorCall(InteropLowering.kt:1306)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDelegatingConstructorCall(IrElementTransformerVoid.kt:174)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDelegatingConstructorCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrDelegatingConstructorCallImpl.accept(IrDelegatingConstructorCallImpl.kt:69)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:27)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:23)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:23)
	...
```

**Comment by SvyatoslavScherbina** [comment]
Supported with #3250 as `NSOutputStream(toMemory = Unit)` (just like in Swift).
