### ISSUE TITLE
[Bug] Calling inline methods with default parameters across projects

### ISSUE THREAD

**Issue by Dominaezzz** [JetBrains/kotlin-native#2584]
Kotlin 1.3.20
IntelliJ 2018.3.3

In a library project A,
```kotlin
// Common
expect inline fun test(name: String, id: String? = null): String

// JVM, mingw and linux
actual inline fun test(name: String, id: String?): String {
    return ""
}
```
In an application project B with dependency on project A,
```kotlin
fun main(args: Array<String>) {
    test("The Name")
    test("The Name", "The ID") // work around
}
```

Project A builds successfully.
Project B builds successfully for jvm but fails on native with,
```
error: compilation failed: Incomplete expression: call to public fun test_0_0(name: kotlin.String, id: kotlin.String = ...): kotlin.String defined in sample.utils[SimpleFunctionDescriptorImpl@1c62d2ad] has no argument at index 1

 * Source files: Main.kt
 * Compiler version info: Konan: 1.1.1 / Kotlin: 1.3.20
 * Output kind: PROGRAM

exception: java.lang.Error: Incomplete expression: call to public fun test_0_0(name: kotlin.String, id: kotlin.String = ...): kotlin.String defined in sample.utils[SimpleFunctionDescriptorImpl@1c62d2ad] has no argument at index 1
	at org.jetbrains.kotlin.backend.konan.lower.Inliner.buildParameterToArgument(FunctionInlining.kt:490)
	at org.jetbrains.kotlin.backend.konan.lower.Inliner.evaluateArguments(FunctionInlining.kt:502)
	at org.jetbrains.kotlin.backend.konan.lower.Inliner.inlineFunction(FunctionInlining.kt:243)
	at org.jetbrains.kotlin.backend.konan.lower.Inliner.inline(FunctionInlining.kt:227)
	at org.jetbrains.kotlin.backend.konan.lower.FunctionInlining.visitCall(FunctionInlining.kt:173)
	at org.jetbrains.kotlin.backend.konan.lower.FunctionInlining.visitCall(FunctionInlining.kt:119)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:100)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:27)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:23)
	at org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl.transformChildren(IrVariableImpl.kt:93)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitDeclaration(IrElementTransformer.kt:38)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitDeclaration(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitVariable(IrElementTransformer.kt:50)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitVariable(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitVariable(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl.accept(IrVariableImpl.kt:86)
	at org.jetbrains.kotlin.ir.declarations.IrDeclaration$DefaultImpls.transform(IrDeclaration.kt:37)
	at org.jetbrains.kotlin.ir.declarations.impl.IrDeclarationBase.transform(IrDeclarationBase.kt:25)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.transformChildren(IrBlockBodyImpl.kt:49)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitBody(IrElementTransformer.kt:55)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitBody(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitBlockBody(IrElementTransformer.kt:58)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitBlockBody(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitBlockBody(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.accept(IrBlockBodyImpl.kt:40)
	at org.jetbrains.kotlin.ir.expressions.IrBody$DefaultImpls.transform(IrBody.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody$DefaultImpls.transform(IrBody.kt)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.transform(IrBlockBodyImpl.kt:26)
	at org.jetbrains.kotlin.ir.declarations.impl.IrAnonymousInitializerImpl.transformChildren(IrAnonymousInitializerImpl.kt:74)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitDeclaration(IrElementTransformer.kt:38)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitDeclaration(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitAnonymousInitializer(IrElementTransformer.kt:49)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitAnonymousInitializer(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitAnonymousInitializer(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.declarations.impl.IrAnonymousInitializerImpl.accept(IrAnonymousInitializerImpl.kt:66)
	at org.jetbrains.kotlin.ir.declarations.IrDeclaration$DefaultImpls.transform(IrDeclaration.kt:37)
	at org.jetbrains.kotlin.ir.declarations.impl.IrDeclarationBase.transform(IrDeclarationBase.kt:25)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.transformChildren(IrClassImpl.kt:113)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitDeclaration(IrElementTransformer.kt:38)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitDeclaration(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitClass(IrElementTransformer.kt:40)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitClassNew(FunctionInlining.kt:101)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitClass(FunctionInlining.kt:58)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitClass(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:102)
	at org.jetbrains.kotlin.ir.declarations.IrDeclaration$DefaultImpls.transform(IrDeclaration.kt:37)
	at org.jetbrains.kotlin.ir.declarations.impl.IrDeclarationBase.transform(IrDeclarationBase.kt:25)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.transformChildren(IrFileImpl.kt:84)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitFile(IrElementTransformer.kt:32)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitFileNew(FunctionInlining.kt:97)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitFile(FunctionInlining.kt:51)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitFile(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:76)
	at org.jetbrains.kotlin.ir.declarations.IrFile$DefaultImpls.transform(IrFile.kt:47)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.transform(IrFileImpl.kt:33)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.transformChildren(IrModuleFragmentImpl.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitModuleFragment(IrElementTransformer.kt:29)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitModuleFragment(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.backend.konan.lower.IrElementTransformerWithContext.visitModuleFragment(FunctionInlining.kt:45)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:42)
	at org.jetbrains.kotlin.backend.konan.lower.FunctionInlining.inline(FunctionInlining.kt:128)
	at org.jetbrains.kotlin.backend.konan.KonanLower$lowerModule$4.invoke(KonanLower.kt:55)
	at org.jetbrains.kotlin.backend.konan.KonanLower$lowerModule$4.invoke(KonanLower.kt:24)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:111)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:136)
	at org.jetbrains.kotlin.backend.konan.KonanLower.lowerModule(KonanLower.kt:54)
	at org.jetbrains.kotlin.backend.konan.KonanLower.lower(KonanLower.kt:30)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$1.invoke(KonanDriver.kt:90)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6$1.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:111)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:136)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt:89)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$6.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:111)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:136)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:88)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:79)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:204)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:196)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:279)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

Also if it helps, this exception is not thrown if all the code is in a single project, only when used as dependency.
Work around is

**Comment by Dominaezzz** [comment]
#2163 Might be related?
