### ISSUE TITLE
Applying Gradle plugin crashes on Android

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [JetBrains/kotlin-native#2614]
Part of the stacktrace:
```
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'KonanGenerateCMakeTask'.
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:75)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:69)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
        at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:188)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:69)
        at org.gradle.api.internal.project.taskfactory.PropertyAssociationTaskFactory.create(PropertyAssociationTaskFactory.java:48)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:44)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:326)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:78)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$2.call(DefaultTaskContainer.java:302)
        ... 154 more
Caused by: java.lang.ExceptionInInitializerError
        at shadow.org.jetbrains.kotlin.gradle.plugin.tasks.KonanGenerateCMakeTask.<init>(KonanGenerateCMakeTask.kt:51)
        at shadow.org.jetbrains.kotlin.gradle.plugin.tasks.KonanGenerateCMakeTask_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:63)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:72)
        ... 163 more
Caused by: shadow.org.jetbrains.kotlin.konan.target.TargetSupportException: Unknown operating system: Android
        at shadow.org.jetbrains.kotlin.konan.target.HostManager$Companion.host_os(KonanTarget.kt:210)
        at shadow.org.jetbrains.kotlin.konan.target.HostManager.<clinit>(KonanTarget.kt:238)
        ... 170 more
```

I use Gradle 5.1.1, the `build.gradle.kts` is:
```kotlin
plugins {
    id("org.jetbrains.kotlin.konan") version "1.3.21"
}
```
I ran it in Termux on Android 8.1 on AArch64 with an OpenJDK 9 from the abandoned `termux-extra-packages` repository.

**Comment by SvyatoslavScherbina** [comment]
Kotlin/Native doesn't support Android as host system, i.e. you can't compile Kotlin/Native projects on Android.

**Comment by arpie42** [comment]
Sorry, my bad.

**Comment by arpie42** [comment]
Now I'm curious. Why would you want to compile on an android host?

**Comment by kaeptmblaubaer1000** [comment]
Because I often only have access to my phone, and I can run Gradle and the standard Kotlin/JVM compiler on it... why wouldn't I try to run Kotlin/Native?

**Comment by olonho** [comment]
Using Android host is not supported configuration.

**Comment by kaeptmblaubaer1000** [comment]
> Using Android host is not supported configuration.

I know... look, this is a feature request to add that...
