### ISSUE TITLE
Project with only test code fails to compile

### ISSUE THREAD

**Issue by charleskorn** [JetBrains/kotlin-native#2617]
If I have a project that only has test code (eg. code in `commonTest` but not `commonMain`), attempting to build the tests fails with an error like this:

```
> Task :integration-test:linkTestDebugExecutableMacOS FAILED
error: compilation failed: Could not find "/Users/charleskorn/Repositories/Personal/OSS/spek/integration-test/build/classes/kotlin/macOS/main/integration-test.klib" in [/Users/charleskorn/Repositories/Personal/OSS/spek, /Users/charleskorn/.konan/klib, /Users/charleskorn/.konan/kotlin-native-macos-1.1.1/klib/common, /Users/charleskorn/.konan/kotlin-native-macos-1.1.1/klib/platform/macos_x64].

 * Source files: AbstractSpecTest.kt, EmptyGroupTest.kt, FixturesTest.kt, MemoizedTests.kt, NonUniquePathTest.kt, SetFeature.kt, SetSpec.kt, SkipTest.kt, calculator.kt
 * Compiler version info: Konan: 1.1.1 / Kotlin: 1.3.20
 * Output kind: PROGRAM

exception: java.lang.IllegalStateException: Could not find "/Users/charleskorn/Repositories/Personal/OSS/spek/integration-test/build/classes/kotlin/macOS/main/integration-test.klib" in [/Users/charleskorn/Repositories/Personal/OSS/spek, /Users/charleskorn/.konan/klib, /Users/charleskorn/.konan/kotlin-native-macos-1.1.1/klib/common, /Users/charleskorn/.konan/kotlin-native-macos-1.1.1/klib/platform/macos_x64].
        at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver.resolve(SearchPathResolver.kt:194)
        at org.jetbrains.kotlin.konan.library.SearchPathResolver$DefaultImpls.resolve$default(SearchPathResolver.kt:18)
        at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl$findLibraries$userProvidedLibraries$1.invoke(KonanLibraryResolverImpl.kt:33)
        at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl$findLibraries$userProvidedLibraries$1.invoke(KonanLibraryResolverImpl.kt:8)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
        at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.findLibraries(KonanLibraryResolverImpl.kt:34)
        at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.resolveWithDependencies(KonanLibraryResolverImpl.kt:16)
        at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:94)
        at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:28)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.backend.konan.KonanConfig.getResolvedLibraries$backend_native_compiler(KonanConfig.kt)
        at org.jetbrains.kotlin.backend.konan.TopDownAnalyzerFacadeForKonan.analyzeFiles(TopDownAnalyzerFacadeForKonan.kt:43)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1$1.invoke(KonanDriver.kt:47)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1$1.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1.invoke(KonanDriver.kt:46)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$1.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:111)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:136)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:44)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:79)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:204)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:196)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:279)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

(Projects with only test code are useful for things like integration tests.)

**Comment by ilmat192** [comment]
Fixed by https://github.com/JetBrains/kotlin/commit/df46dfc63de6d3192d4514015ad3d960de4b2469.
