### ISSUE TITLE
[Problem] Sample/VideoPlayer  compile fail that based on master(d74384db) on macOS.

### ISSUE THREAD

**Issue by Guang1234567** [JetBrains/kotlin-native#2741]
Hello dev:

I just want to compile the `sample/videoplayer`that based on newest master (d74384db).

But 

```ruby 
llvm-lto: error: Linking globals named 'kobjref:kotlinx.wasm.jsinterop.ArenaManager': symbol multiply defined!
```

Could you give me some suggestion? Thx.

**Detail**
```ruby

> Task :videoplayer:linkMainDebugExecutableVideoPlayer
llvm-lto: error: Linking globals named 'kobjref:kotlinx.wasm.jsinterop.ArenaManager': symbol multiply defined!
error: compilation failed: The /Users/XXX/.konan/dependencies/clang-llvm-6.0.1-darwin-macos/bin/llvm-lto command returned non-zero exit code: 1.

 * Source files: DecoderWorker.kt, Dimensions.kt, Disposable.kt, Queue.kt, SDLAudio.kt, SDLErrors.kt, SDLInput.kt, SDLVideo.kt, VideoPlayer.kt
 * Compiler version info: Konan: 1.2-dev / Kotlin: 1.3.30
 * Output kind: PROGRAM

exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /Users/XXX/.konan/dependencies/clang-llvm-6.0.1-darwin-macos/bin/llvm-lto command returned non-zero exit code: 1.
        at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:105)
        at org.jetbrains.kotlin.konan.exec.Command.execute(ExecuteCommand.kt:66)

```

**Comment by Guang1234567** [comment]
maybe not do

```ruby
After that, you should be able to compile your programs like this:

export PATH=./dist/bin:$PATH
```
