### ISSUE TITLE
An incorrect phase name in verbose-phases leads to NPE

### ISSUE THREAD

**Issue by ptmt** [JetBrains/kotlin-native#2770]
E.g. `'-Xverbose-phases=linker` instead of '-Xverbose-phases=linker':
```
* Compiler version info: Konan: 1.2-eap-8472 / Kotlin: 1.3.30
 * Output kind: LIBRARY

e: kotlin.KotlinNullPointerException
        at org.jetbrains.kotlin.backend.common.phaser.PhaseConfig.phaseSetFromConfiguration(PhaseConfig.kt:64)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseConfig.<init>(PhaseConfig.kt:14)
        at org.jetbrains.kotlin.backend.konan.Context.<init>(Context.kt:216)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:20)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by gogabr** [comment]
https://upsource.jetbrains.com/kotlin/review/KOTLIN-CR-2837

**Comment by SvyatoslavScherbina** [comment]
Fixed.
