### ISSUE TITLE
Cinterop with ultralight error

### ISSUE THREAD

**Issue by G0BL1N** [JetBrains/kotlin-native#2808]
So i'm trying to use cinterop tool to get bindings with [ultralight](https://github.com/ultralight-ux/ultralight)
Here's my `.def` file:
```
headers = Ultralight/Ultralight.h JavaScriptCore/JavaScript.h
staticLibraries = Ultralight.lib UltralightCore.lib WebCore.lib AppCore.lib
libraryPaths = C:/ultralight-sdk-1.0-win/lib/win/x64
compilerOpts = -x c++-header -std=c++11
```
`compilerOpts` are there because Ultralight needs C++11 ('cstdint' file not found error otherwise).
Call to `cinterop`:
`cinterop -def ultralight.def -compilerOpts -IC:/ultralight`
Leads to this exception:
```
Exception in thread "Thread-1" java.lang.IllegalArgumentException: CXCursor_ClassTemplatePartialSpecialization
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.structHasNaturalLayout(Indexer.kt:461)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.createStructDef(Indexer.kt:207)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.getStructDeclAt(Indexer.kt:189)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.indexDeclaration(Indexer.kt:706)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt$indexDeclarations$2.indexDeclaration(Indexer.kt:919)
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt$indexTranslationUnit$1$indexerCallbacks$1$3.invoke(Utils.kt:372)
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt$indexTranslationUnit$1$indexerCallbacks$1$3.invoke(Utils.kt)
        at kotlinx.cinterop.JvmCallbacksKt$createStaticCFunctionImpl$$inlined$ffiClosureImpl$3.invoke(JvmCallbacks.kt:487)
        at kotlinx.cinterop.JvmCallbacksKt$createStaticCFunctionImpl$$inlined$ffiClosureImpl$3.invoke(JvmCallbacks.kt)
        at kotlinx.cinterop.JvmCallbacksKt.ffiFunImpl(JvmCallbacks.kt:448)
        at kotlinx.cinterop.JvmCallbacksKt.ffiFunImpl0(JvmCallbacks.kt:435)
```
Can someone help me with that? Am i doing something wrong with `compilerOpts`?

**Comment by olonho** [comment]
Kotlin/Native currently provides interoperability with C, not C++ libraries.

**Comment by G0BL1N** [comment]
Even if library provides C interface?
As I understand, it just needs C++11 compiler to link it, but it does provide C API bindings.

**Comment by G0BL1N** [comment]
Got it, i needed to include `CAPI.h`, not `Ultralight.h`. No need for any compiler options.
Also `stdint.h` was missing for some reason.
Thanks for the help anyway.
