### ISSUE TITLE
Generic class literals in annotation arguments cause unbound symbol in 1.3.30

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#2899]
See related discussions: 
https://github.com/Kotlin/kotlinx.serialization/issues/436
https://github.com/Kotlin/kotlinx.coroutines/issues/1099

Problem is reproducible on:
```
class Foo(@Serializable(HashMapSerializer::class) val bar: String)
```

Note that `Foo` class is not marked as Serialiable, so compiler plugin does not process it. However, `HashMapSerializer` is a generic class which has type arguments K and V. It seems using its class literal in an annotation argument (w/o actual type parameters, ofc) causes unbound type parameter descriptor K:

```
e: java.lang.AssertionError: findDeserializedDeclaration: symbol org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterSymbolImpl@5cff6b74 is unbound, descriptor = K, hash = 1476061571
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.findDeserializedDeclaration(KotlinIrLinker.kt:365)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateOrGetTypeParameterStub$1.invoke(DeclarationStubGenerator.kt:220)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateOrGetTypeParameterStub$1.invoke(DeclarationStubGenerator.kt:35)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareGlobalTypeParameter(SymbolTable.kt:671)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.generateOrGetTypeParameterStub$ir_tree(DeclarationStubGenerator.kt:219)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator$DependencyGenerationTask.run(ExternalDependenciesGenerator.kt:59)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:36)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:48)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:61)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:98)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:58)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:56)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)

```

**Comment by SvyatoslavScherbina** [comment]
Must have been fixed in 1.3.40.
