### ISSUE TITLE
Samples don't build on windows+msys2

### ISSUE THREAD

**Issue by darkoverlordofdata** [JetBrains/kotlin-native#2939]
I could build the compiler and libraries without incident. But when I try to build samples, either en mass using   ./gradlew buildAllSamples or individually using ../gradlew assemble, I get the same error:

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\darko\Documents\GitHub\kotlin-native\samples\settings.gradle' line: 1

* What went wrong:
A problem occurred evaluating settings 'samples'.
> Could not find method exitpluginManagement() for arguments [settings_5y26qeh2sfknbw3krnp1z4tg8$_run_closure1@5919067b]
on settings 'samples' of type org.gradle.initialization.DefaultSettings.

It looks like gradle is missing a method, and I've no idea how to fix that - I've never had any luck with gradle. I was hoping that Kotlin Native being native didn't require much experience with jvm related tools.

**Comment by olonho** [comment]
Could you please build with Gradle 5.2.

**Comment by msink** [comment]
Looks like you tried to build not from Windows terminal, but from MSYS2 console window.
I never tried it (from MSYS2), but in plain Windows terminal it works just fine on my computer.
At least it worked a month ago, will try to rebuild now.

**Comment by msink** [comment]
Cannot confirm - yes, samples don't build, but differently:
```
$ cd /f/src/kotlin-native/samples/tetris/ && ../gradlew build
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :csvparser
Kotlin Multiplatform Projects are an experimental feature.

> Configure project :libcurl
This build is set up to publish Kotlin multiplatform libraries with experimental Gradle metadata. Future Gradle versions may fail to resolve dependencies on these publications. You can disable Gradle metadata usage during publishing and dependencies resolution by removing `enableFeaturePreview('GRADLE_METADATA')` from the settings.gradle file.

> Configure project :tetris
project ':tetris' has been configured for mingwX64 platform.

Some native binaries in this build are configured using deprecated DSL elements. Use the `binaries` DSL block instead.
The following deprecated DSL elements are used in this build:
    KotlinNativeCompilation.entryPoint
    KotlinNativeCompilation.entryPoint(...)
    KotlinNativeCompilation.findLinkTask(...)
    KotlinNativeCompilation.linkTaskName(...)
    KotlinNativeCompilation.linkerOpts
    KotlinNativeCompilation.linkerOpts(...)
    KotlinNativeCompilation.outputKinds
    KotlinNativeCompilation.outputKinds(...)

See details about the `binaries` block at https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries

> Task :tetris:cinteropSdlTetris FAILED
Exception in thread "main" java.lang.IllegalStateException: Unknown option -compilerOpt
Usage: 
Options: 
    -target [host] -> native target to compile to { String }
    -def -> the library definition file { String }
    -header -> header file to produce kotlin bindings for { String }
    -h -> header file to produce kotlin bindings for { String } Warning: Option -h is deprecated. Please use -header.
    -headerFilterAdditionalSearchPrefix, -hfasp -> header file to produce kotlin bindings for { String }
    -compilerOpts -> additional compiler options (allows to add several options separated by spaces) { String }
    -compiler-options -> additional compiler options (allows to add several options separated by spaces) { String }
    -linkerOpts -> additional linker options (allows to add several options separated by spaces) { String }
    -linker-options -> additional linker options (allows to add several options separated by spaces) { String }
    -compiler-option -> additional compiler option { String }
    -linker-option -> additional linker option { String }
    -copt -> additional compiler options (allows to add several options separated by spaces) { String } Warning: Option -copt is deprecated. Please use -compiler-options.
    -lopt -> additional linker options (allows to add several options separated by spaces) { String } Warning: Option -lopt is deprecated. Please use -linker-options.
    -linker -> use specified linker { String }
    -verbose [false] -> Enable verbose logging output 
    -flavor [jvm] -> Interop target { Value should be one of [jvm, native, wasm] }
    -pkg -> place generated bindings to the package { String }
    -output, -o [nativelib] -> specifies the resulting library file { String }
    -libraryPath -> add a library search path { String }
    -staticLibrary -> embed static library to the result { String }
    -generated [F:\src\kotlin-native\samples\tetris] -> place generated bindings to the directory { String }
    -natives [F:\src\kotlin-native\samples\tetris] -> where to put the built native files { String }
    -library, -l -> library to use for building { String }
    -repo, -r -> repository to resolve dependencies { String }
    -nodefaultlibs [false] -> don't link the libraries from dist/klib automatically 
    -Xpurge-user-libs [false] -> don't link unused libraries even explicitly specified 
    -Xtemporary-files-dir -> save temporary files to the given directory { String }
    -help -> Usage info 

	at org.jetbrains.kliopt.ArgParser.printError(KliOpt.kt:171)
	at org.jetbrains.kliopt.ArgParser.parse(KliOpt.kt:250)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:24)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tetris:cinteropSdlTetris'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_111\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by LepilkinaElena** [comment]
@msink thank you, forgot to set up new version of MPP. I change version of MPP plugin in samples, now cinterop should work.

**Comment by olonho** [comment]
Fixed in master.
