### ISSUE TITLE
Kotlin 1.3.40-eap-21: InvalidProtocolBufferException when compiling for iOS

### ISSUE THREAD

**Issue by jonasbark** [JetBrains/kotlin-native#2992]
The task `compileKotlinIosX64` fails with the following error:

```
e: Compilation failed: Message was missing required fields.  (Lite runtime could not determine which fields were missing).

 * Source files: ...
 * Compiler version info: Konan: 1.3-eap-10124 / Kotlin: 1.3.40
 * Output kind: LIBRARY

e: org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
	at org.jetbrains.kotlin.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
	at org.jetbrains.kotlin.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parseFrom(AbstractParser.java:89)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIr$IrModule.parseFrom(KotlinIr.java:7163)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.deserializeIrModuleHeader(KotlinIrLinker.kt:413)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.deserializeIrModuleHeader(KotlinIrLinker.kt:433)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:117)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:116)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:114)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:113)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:23)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:112)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:92)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:113)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:23)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:112)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:92)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:41)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:79)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:218)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:215)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:40)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:34)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:299)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)

```

My (relevant) gradle files:
https://gist.github.com/jonasbark/874003fca9d573dcfb835b9ca4002d7f

If relevant, my project uses coroutines, kotlinx-serialization and ktor

**Comment by SvyatoslavScherbina** [comment]
> If relevant, my project uses coroutines, kotlinx-serialization and ktor

Have you updated the dependencies to 1.3.40-compatible versions?

**Comment by jonasbark** [comment]
As they don't exist yet I will report back if they do and the problem still persists.

**Comment by olonho** [comment]
Yeah, this is compiler problem which will be fixed in next EAP update.

**Comment by olonho** [comment]
Shall be fixed, please retest.

**Comment by jonasbark** [comment]
Thank you!
The error doesn't appear anymore but to be 100% sure I'll have to wait for compatible versions of coroutines + ktor + kotlinx-serialization. I'll reopen this ticket if it reappears.
