### ISSUE TITLE
unable to determine `namespace` in c++ header file

### ISSUE THREAD

**Issue by theLimitBreaker** [JetBrains/kotlin-native#3018]
I tried to do `cinterop` for `stl_stack` header file in C++ standard template library. 

```
#stl_stack.def

headers = /usr/include/c++/7/bits/stl_stack.h
```

And this is how configured `build.gradle` for including directories forearching header files
(for linux)
```
  linuxX64("linux"){
        compilations.main.cinterops{
            stack_stl{
                includeDirs.allHeaders(
                        "/usr/include/c++/7/",
                        "/usr/include/x86_64-linux-gnu/c++/7/"
                )
            }
        }
    }
```

I get this exception
```
Exception in thread "main" java.lang.Error: /usr/include/c++/7/debug/debug.h:48:1: error: unknown type name 'namespace'
```

and this is stacktrace

```

Exception in thread "main" java.lang.Error: /usr/include/c++/7/debug/debug.h:48:1: error: unknown type name 'namespace'
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:133)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:959)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:951)
	at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:74)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:229)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:67)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)
```

**Comment by sbogolepov** [comment]
There is no support for C++ interoperability, only C.

**Comment by theLimitBreaker** [comment]
I want to use STL Stack of C++ . how could I use that functionality then ?  Do I have to implement my own stack for native ?

**Comment by olonho** [comment]
Either implement your own or use existing C stack implementation, i.e. one from https://github.com/fgmcoelho/libcargo https://developer.gnome.org/glib/ http://apr.apache.org/  to just name a few.
