### ISSUE TITLE
ISE: IrSimpleFunctionSymbolImpl for WrappedSimpleFunctionDescriptor is already bound

### ISSUE THREAD

**Issue by fluidsonic** [JetBrains/kotlin-native#3019]
Using the [repro project](https://github.com/JetBrains/kotlin-native/files/3220540/kotlin-native-bug.zip):
```shell
./gradlew build
```

The exception doesn't occur if
- I don't use `com.github.fluidsonic.fluid.stdlib.GeoCoordinate`
- I don't mark `GeoCoordinate` as `@Serializable`
- I remove the `init` block from `GeoCoordinate`

```
e: Compilation failed: IrSimpleFunctionSymbolImpl for org.jetbrains.kotlin.backend.common.descriptors.WrappedSimpleFunctionDescriptor@1df41490 is already bound

 * Source files: Sample.kt
 * Compiler version info: Konan: 1.2.1 / Kotlin: 1.3.31
 * Output kind: LIBRARY

e: java.lang.IllegalStateException: IrSimpleFunctionSymbolImpl for org.jetbrains.kotlin.backend.common.descriptors.WrappedSimpleFunctionDescriptor@1df41490 is already bound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.bind(IrSymbolBase.kt:48)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl.<init>(IrFunctionImpl.kt:88)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer$deserializeIrFunction$function$1.invoke(IrModuleDeserializer.kt:851)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer$deserializeIrFunction$function$1.invoke(IrModuleDeserializer.kt:47)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareSimpleFunction(SymbolTable.kt:641)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrFunction(IrModuleDeserializer.kt:849)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeDeclaration(IrModuleDeserializer.kt:1126)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeStatement(IrModuleDeserializer.kt:186)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeBlock(IrModuleDeserializer.kt:204)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeOperation(IrModuleDeserializer.kt:634)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeExpression(IrModuleDeserializer.kt:700)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeMemberAccessCommon(IrModuleDeserializer.kt:216)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeCall(IrModuleDeserializer.kt:270)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeOperation(IrModuleDeserializer.kt:640)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeExpression(IrModuleDeserializer.kt:700)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeStatement(IrModuleDeserializer.kt:188)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeBlockBody(IrModuleDeserializer.kt:144)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeStatement(IrModuleDeserializer.kt:180)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrFunctionBase(IrModuleDeserializer.kt:825)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrConstructor(IrModuleDeserializer.kt:972)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeDeclaration(IrModuleDeserializer.kt:1120)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrClass(IrModuleDeserializer.kt:801)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeDeclaration(IrModuleDeserializer.kt:1124)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.deserializeTopLevelDeclaration(KotlinIrLinker.kt:293)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.deserializeAllReachableTopLevels(KotlinIrLinker.kt:325)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.findDeserializedDeclarationForDescriptor(KotlinIrLinker.kt:355)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.findDeserializedDeclaration(KotlinIrLinker.kt:362)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateClassStub$1.invoke(DeclarationStubGenerator.kt:198)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateClassStub$1.invoke(DeclarationStubGenerator.kt:35)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass(SymbolTable.kt:554)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass$default(SymbolTable.kt:236)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.generateClassStub$ir_tree(DeclarationStubGenerator.kt:195)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator$DependencyGenerationTask.run(ExternalDependenciesGenerator.kt:44)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:36)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:48)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:61)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:98)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:58)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:56)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by fluidsonic** [comment]
Another case with `IrVariableSymbolImpl` instead.
Cannot create a repro though as that scenario is more complex and uses private code I cannot share.

```
e: java.lang.IllegalStateException: IrVariableSymbolImpl for org.jetbrains.kotlin.backend.common.descriptors.WrappedVariableDescriptor@4bc71f6e is already bound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.bind(IrSymbolBase.kt:48)
        at org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl.<init>(IrVariableImpl.kt:78)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrVariable(IrModuleDeserializer.kt:883)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeDeclaration(IrModuleDeserializer.kt:1134)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeStatement(IrModuleDeserializer.kt:186)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeBlock(IrModuleDeserializer.kt:204)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeOperation(IrModuleDeserializer.kt:634)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeExpression(IrModuleDeserializer.kt:700)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeStatement(IrModuleDeserializer.kt:188)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeBlockBody(IrModuleDeserializer.kt:144)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeStatement(IrModuleDeserializer.kt:180)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrFunctionBase(IrModuleDeserializer.kt:825)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrConstructor(IrModuleDeserializer.kt:972)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeDeclaration(IrModuleDeserializer.kt:1120)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeIrClass(IrModuleDeserializer.kt:801)
        at org.jetbrains.kotlin.backend.konan.serialization.IrModuleDeserializer.deserializeDeclaration(IrModuleDeserializer.kt:1124)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.deserializeTopLevelDeclaration(KotlinIrLinker.kt:293)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.deserializeAllReachableTopLevels(KotlinIrLinker.kt:325)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.findDeserializedDeclarationForDescriptor(KotlinIrLinker.kt:355)
        at org.jetbrains.kotlin.backend.konan.serialization.KotlinIrLinker.findDeserializedDeclaration(KotlinIrLinker.kt:362)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateClassStub$1.invoke(DeclarationStubGenerator.kt:198)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateClassStub$1.invoke(DeclarationStubGenerator.kt:35)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass(SymbolTable.kt:554)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass$default(SymbolTable.kt:236)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.generateClassStub$ir_tree(DeclarationStubGenerator.kt:195)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator$DependencyGenerationTask.run(ExternalDependenciesGenerator.kt:44)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:36)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:48)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:61)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:98)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:58)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:56)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

**Comment by sandwwraith** [comment]
Can you post the contents of your `init` block, please?

**Comment by SvyatoslavScherbina** [comment]
I believe this is it: https://github.com/fluidsonic/fluid-stdlib/commit/031c60ca7fc8388d0d0cedf17ded19fc575a5986

**Comment by olonho** [comment]
Looks like an issue in `kotlinx.serialization` compiler plugin, better to keep track of the issue in appropriate tracker.

**Comment by SvyatoslavScherbina** [comment]
I guess this is fixed with https://github.com/JetBrains/kotlin/commit/d8b69226923fda3a2324f8d6fd3356dbd7db4446
