### ISSUE TITLE
Failure invoking xcrun on OSX catalina

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/kotlin-native#3063]
i think this is because xcrun is being invoked with a sdk names that don't exist

```
> Task :linkReleaseFrameworkIosArm64 FAILED
2 actionable tasks: 1 executed, 1 up-to-date
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
e: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /usr/bin/xcrun command returned non-zero exit code: 1.
	at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:105)
	at org.jetbrains.kotlin.konan.exec.Command.getResult(ExecuteCommand.kt:94)
	at org.jetbrains.kotlin.konan.exec.Command.getOutputLines(ExecuteCommand.kt:73)
	at org.jetbrains.kotlin.konan.exec.Command.getOutputLines$default(ExecuteCommand.kt:72)
```

**Comment by olonho** [comment]
Are mobile SDKs indeed installed?

**Comment by SvyatoslavScherbina** [comment]
If you have Xcode 11 beta downloaded and unpacked manually, then it requires to be properly configured with `xcode-select`.

**Comment by artdfel** [comment]
Closing as obsolete.
