### ISSUE TITLE
Nullable Unit in function signature causes compiler crash when producing shared library

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#3187]
I try to build a shared library on macos:

```gradle
macosX64("macos") {
        binaries {
            sharedLib {
                baseName = "native"
            }
        }
    }
```

My code:

```kotlin
fun foo(i: Int, u: Unit?, f: String?): String {
    println(u)
    return f ?: ""
}
```

Task :linkDebugSharedMacos FAILED, exception:

```
Produced library API in libnative_api.h
deserialized class Unit
e: Compilation failed: kotlin.Unit

 * Source files: Data.kt, GeoCoordinate.kt, Helpers.kt, Sample.kt, SampleMacos.kt
 * Compiler version info: Konan: 1.3.1 / Kotlin: 1.3.40
 * Output kind: DYNAMIC

e: java.lang.AssertionError: kotlin.Unit
        at org.jetbrains.kotlin.backend.konan.ExportedElement.translateArgument(CAdapterGenerator.kt:408)
        at org.jetbrains.kotlin.backend.konan.ExportedElement.translateBody(CAdapterGenerator.kt:427)
        at org.jetbrains.kotlin.backend.konan.ExportedElement.makeFunctionDeclaration(CAdapterGenerator.kt:351)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.makeElementDefinition(CAdapterGenerator.kt:753)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.makeScopeDefinitions(CAdapterGenerator.kt:782)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.makeScopeDefinitions(CAdapterGenerator.kt:783)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.makeScopeDefinitions(CAdapterGenerator.kt:783)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.makeGlobalStruct(CAdapterGenerator.kt:963)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.generateBindings(CAdapterGenerator.kt:712)
        at org.jetbrains.kotlin.backend.konan.CAdapterGenerator.generateBindings(CAdapterGenerator.kt:677)
        at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.appendCAdapters(IrToBitcode.kt:298)
        at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:328)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
        at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:199)
        at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:199)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:41)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:258)
        at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$codegenPhase$1.invoke(BitcodePhases.kt:107)
        at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$codegenPhase$1.invoke(BitcodePhases.kt)
        at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:54)
        at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:52)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:23)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:112)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:92)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:23)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:112)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:92)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:23)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:112)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:92)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:23)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:112)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:92)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:41)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:79)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:215)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:212)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:40)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:34)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:214)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
```

Possible cause: https://github.com/JetBrains/kotlin-native/blob/13684eea98e0fcdd2773c34d19bf93459999ad80/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/CAdapterGenerator.kt#L285 reports `true` for `Unit?`. However, stripping a nullable unit from signature disallows passing `null` there.

**Comment by olonho** [comment]
Shall be fixed https://github.com/JetBrains/kotlin-native/pull/3198
