### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:976): cannot locate symbol "__isnanf" referenced by "libdemo.so"...

### ISSUE THREAD

**Issue by ZhouGongZaiShi** [JetBrains/kotlin-native#3327]
Environment:
```
Android Stuido 3.5
Android gradle plugin: 3.5.0
Kotlin version: 1.3.50
```

My project like:
```
project root dir
----clib
--------armeabi-v7a
------------libnative.a
--------header
------------native.h
----src
--------arm32Main
------------kotlin
----------------main.kt
--------nativeInterop
------------cinterop
----------------libnative.def
```
main.kt:
```
import platform.android.*
import kotlinx.cinterop.*
import libnative.*

@CName("Java_com_example_kotlinnatvie_MainActivity_sayHello")
fun sayHello(){
    __android_log_print(ANDROID_LOG_INFO.toInt(), "Kotlin Native", "Hello %s", "Native")
}

@CName("Java_com_example_kotlinnatvie_MainActivity_stringFromJNI")
fun stringFromJNI(env: CPointer<JNIEnvVar>, thiz: jobject): jstring {
    __android_log_print(ANDROID_LOG_INFO.toInt(), "Kotlin Native", "invoke third lib method: mysqrt(16.0) = %s", mysqrt(16.0).toString())
    memScoped {
        return env.pointed.pointed!!.NewStringUTF!!.invoke(env, "This is from Kotlin Native!!".cstr.ptr)!!
    }
}

@CName("Java_com_example_kotlinnatvie_MainActivity_callJavaMethod")
fun callJavaMethod(env: CPointer<JNIEnvVar>, thiz: jobject): jstring {
    memScoped {
        val jniEnvVal = env.pointed.pointed!!
        val jclass = jniEnvVal.GetObjectClass!!.invoke(env, thiz)
        val methodId = jniEnvVal.GetMethodID!!.invoke(env, jclass, "callFromNative".cstr.ptr, "()Ljava/lang/String;".cstr.ptr)
        return jniEnvVal.CallObjectMethodA!!.invoke(env, thiz, methodId, null) as jstring
    }
}
```

libnative.def:
```
headers = native.h
compilerOpts = -I./clib/header
staticLibraries = libnative.a
libraryPaths = clib/armeabi-v7a/
```
Compile successfully and generate `libdemo.so`.		
If I load `libdemo.so` with an `api>17` android device, I can load the native library and call the native method. 		
But devices with `api<=17` will crash:
```
java.lang.ExceptionInInitializerError
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1319)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1071)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
        at android.app.ActivityThread.access$700(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5306)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:976): cannot locate symbol "__isnanf" referenced by "libdemo.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:535)
        at com.example.kotlinnatvie.MainActivity.<clinit>(MainActivity.kt:75)
        at java.lang.Class.newInstanceImpl(Native Method) 
        at java.lang.Class.newInstance(Class.java:1319) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1071) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299) 
        at android.app.ActivityThread.access$700(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5306) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
        at dalvik.system.NativeStart.main(Native Method) 
```
How to solve this problem?	
Thanks.

**Comment by olonho** [comment]
Devices with that API level (Android Jelly bean, 4.2) are 7 years old now, and are not supported.

**Comment by ZhouGongZaiShi** [comment]
> Devices with that API level (Android Jelly bean, 4.2) are 7 years old now, and are not supported.

Thank you for your answer.    
I always thought it was the problem caused by my code.
