### ISSUE TITLE
Kotlinx.serialization can't be built with Kotlin 1.3.60

### ISSUE THREAD

**Issue by sandwwraith** [JetBrains/kotlin-native#3426]
Branch: `no_infra` (https://github.com/Kotlin/kotlinx.serialization/tree/no_infra)

Kotlin version: 1.3.60-eap-11 from bintray/kotlin-dev

Compiler crash:

```
~/work/x-ser-runtime|no_infra ⇒ ./gradlew macosX64Test

> Configure project :kotlinx-serialization-runtime
Kotlin Multiplatform Projects are an experimental feature.
Project property 'org.jetbrains.kotlin.native.jvmArgs' is deprecated. Please use 'kotlin.native.jvmArgs' instead.
Publication maven not found in project :kotlinx-serialization-runtime.
Using Kotlin compiler version: 1.3.60-eap-11

> Task :kotlinx-serialization-runtime:compileKotlinMacosX64
e: Compilation failed: No descriptor ID found for public final val id: kotlin.Int defined in kotlinx.serialization.SerialId.Impl[PropertyDescriptorImpl@e4e9bc2]

 * Source files: Buffers.kt, Streams.kt, Writers.kt, Annotations.kt, Coders.kt, ContextSerializer.kt, Core.kt, Deprecated.kt, Descriptors.kt, ElementWise.kt, Exceptions.kt, Mapper.kt, PlatformUtils.kt, Polymorphic.kt, SerialFormat.kt, SerialImplicits.kt, SerializerResolving.kt, Shorthands.kt, Tagged.kt, Cbor.kt, Deprecated.kt, CollectionDescriptors.kt, CollectionSerializers.kt, Enums.kt, GeneratedSerializer.kt, LongAsStringSerializer.kt, NullableSerializer.kt, PrimitiveArraysSerializers.kt, Primitives.kt, SerialClassDescImpl.kt, Tuples.kt, Util.kt, Deprecated.kt, Json.kt, JsonConfiguration.kt, JsonElement.kt, JsonElementBuilders.kt, JsonElementSerializer.kt, JsonElements.kt, JsonExceptionHelpers.kt, JsonExceptions.kt, JsonInput.kt, JsonOutput.kt, JsonParser.kt, JsonReader.kt, Polymorphic.kt, StreamingJsonInput.kt, StreamingJsonOutput.kt, StringOps.kt, TreeJsonInput.kt, TreeJsonOutput.kt, WriteMode.kt, PolymorphicModuleBuilder.kt, SerialModule.kt, SerialModuleBuilders.kt, SerialModuleCollector.kt, SerialModuleExtensions.kt, SerialModuleImpl.kt, SerializerAlreadyRegisteredException.kt, StandardSubtypesOfAny.kt, ProtoBuf.kt, ProtoTypes.kt, Buffers.kt, Streams.kt, Writers.kt, Platform.kt
 * Compiler version info: Konan: 1.3.60-eap-12794 / Kotlin: 1.3.60
 * Output kind: LIBRARY

e: java.lang.IllegalStateException: No descriptor ID found for public final val id: kotlin.Int defined in kotlinx.serialization.SerialId.Impl[PropertyDescriptorImpl@e4e9bc2]
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer.declarationTableHandler(KlibMetadataSerializer.kt:50)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer$createNewContext$extension$1.invoke(KlibMetadataSerializer.kt:59)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer$createNewContext$extension$1.invoke(KlibMetadataSerializer.kt:33)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializerExtension.uniqId(KlibMetadataSerializerExtension.kt:35)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializerExtension.serializeProperty(KlibMetadataSerializerExtension.kt:78)
        at org.jetbrains.kotlin.serialization.DescriptorSerializer.propertyProto(DescriptorSerializer.kt:279)
        at org.jetbrains.kotlin.serialization.DescriptorSerializer.classProto(DescriptorSerializer.kt:112)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer.serializeClass(KlibMetadataSerializer.kt:111)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer.serializeClasses(KlibMetadataSerializer.kt:131)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer.serializeClass(KlibMetadataSerializer.kt:117)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer.serializeClasses(KlibMetadataSerializer.kt:131)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer$serializeDescriptors$2.invoke(KlibMetadataSerializer.kt:182)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer$serializeDescriptors$2.invoke(KlibMetadataSerializer.kt:33)
        at kotlin.collections.CollectionsKt___CollectionsKt.windowed(_Collections.kt:2196)
        at kotlin.collections.CollectionsKt___CollectionsKt.chunked(_Collections.kt:1949)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializerKt.maybeChunked(KlibMetadataSerializer.kt:31)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataSerializer.serializeDescriptors(KlibMetadataSerializer.kt:175)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataMonolithicSerializer.serializePackageFragment(KlibMetadataMonolithicSerializer.kt:51)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.KlibMetadataMonolithicSerializer.serializeModule(KlibMetadataMonolithicSerializer.kt:62)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$serializerPhase$1.invoke(ToplevelPhases.kt:233)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$serializerPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:115)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:74)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:225)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:222)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:224)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :kotlinx-serialization-runtime:compileKotlinMacosX64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotlinx-serialization-runtime:compileKotlinMacosX64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
1 actionable task: 1 executed
```

**Comment by SvyatoslavScherbina** [comment]
What's the status of this issue now?

**Comment by sandwwraith** [comment]
Fixed by https://github.com/JetBrains/kotlin/commit/6d905157b33f2fec2a25680f5ed62f823f54669f and https://github.com/JetBrains/kotlin/commit/efcf1368135add49398107ac5b71e4eb19e24ebd
