### ISSUE TITLE
Cannot build for iOS target on 1.3.60

### ISSUE THREAD

**Issue by mgrzechocinski** [JetBrains/kotlin-native#3436]
Hi, 

I have a pretty simple code in KN to compile for the following platforms:

- Android ARM 32-bit
- Android ARM 64-bit
- Android x86 32-bit
- Android x86 64-bit
- iOS ARM 64-bit
- iOS x86 64-bit

Regarding configuration, I followed [this](https://github.com/Kotlin/kotlin-examples/blob/64e6cf95508056d716cb024cad3d6e9cc5dda0d5/tutorials/mpp-iOS-Android/SharedCode/build.gradle#L5) example, but when it comes to build any iOS target, I get:

```
> Task :linkEmpikappNativeLibraryDebugFrameworkIos
e: Compilation failed: org.jetbrains.kotlin.descriptors.SourceFile$1@14b789f6 has no name

 * Source files:
 * Compiler version info: Konan: 1.3.60-eap-12794 / Kotlin: 1.3.60
 * Output kind: FRAMEWORK

e: java.lang.IllegalStateException: org.jetbrains.kotlin.descriptors.SourceFile$1@14b789f6 has no name
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerImpl$getFileClassName$candidate$2.invoke(ObjCExportNamer.kt:291)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerImpl$getFileClassName$candidate$2.invoke(ObjCExportNamer.kt:164)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerImpl.getFileClassName(ObjCExportNamer.kt:297)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportTranslatorImpl.translateFile(ObjCExportHeaderGenerator.kt:272)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.generateFile(ObjCExportHeaderGenerator.kt:1104)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.access$generateFile(ObjCExportHeaderGenerator.kt:920)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$translateModule$5.accept(ObjCExportHeaderGenerator.kt:1087)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator$translateModule$5.accept(ObjCExportHeaderGenerator.kt:920)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportHeaderGenerator.translateModule(ObjCExportHeaderGenerator.kt:1086)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produceInterface(ObjCExport.kt:66)
        at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.<init>(ObjCExport.kt:39)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$objCExportPhase$1.invoke(ToplevelPhases.kt:111)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$objCExportPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:115)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:74)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:225)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:222)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:224)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :linkEmpikappNativeLibraryDebugFrameworkIos FAILED
```

Tried on `1.3.60-eap9` and `1.3.60-eap-16`. When I switch to `1.3.50`, it builds successfully and produces iOS frameworks.

I need 1.3.60 branch since it introduces support for Android x86 target.

I'd appreciate any hints.

**Comment by artdfel** [comment]
Hello!
This is a known issue, we're working on it. Please stay tuned!

**Comment by alexander-gorshenev** [comment]
@mgrzechocinski  Can you try 1.3.60-eap-22?

**Comment by alexander-gorshenev** [comment]
@mgrzechocinski  Ah, wait. The fix's going to be only in eap-23.

**Comment by mgrzechocinski** [comment]
@alexander-gorshenev I can confirm that on eap-23 project compiles successfully. Will try if it actually works at runtime tomorrow. Thanks for such a quick feedback!
