### ISSUE TITLE
fatal error: module 'CoreAudioTypes' not found

### ISSUE THREAD

**Issue by wuseal** [JetBrains/kotlin-native#3454]
When build with ```./gradlew dist distPlatformLibs``` on Mac.

It build failed with next error info:
```
> Task :platformLibs:compileKonanMacos_x64-CoreAudioTypesMacos_x64 FAILED
Exception in thread "main" java.lang.Error: /var/folders/6h/_fzry8_s7k196c6vjnptvf2h0000gn/T/tmp4040090440387412775.m:1:9: fatal error: module 'CoreAudioTypes' not found
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:146)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:364)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:219)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:39)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:71)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platformLibs:compileKonanMacos_x64-CoreAudioTypesMacos_x64'.
> A failure occurred while executing shadow.org.jetbrains.kotlin.gradle.plugin.tasks.KonanInteropTask$RunTool
   > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
108 actionable tasks: 10 executed, 98 up-to-date
```
Is there any way to resolve this problem?

**Comment by artdfel** [comment]
Hello!
What version of the Xcode do you use?

**Comment by wuseal** [comment]
After changing the source code of this project to tag: `v1.3.50`, It builds OK! I think my Xcode version only supports v1.3.50, All right?

**Comment by olonho** [comment]
Yes, Xcode 11 is required to build recent master.
