### ISSUE TITLE
Possibility of CPP interop ? 

### ISSUE THREAD

**Issue by dickensas** [JetBrains/kotlin-native#3579]
Any initiative is in progress support C++ interop ?

-x c++

this linker and compiler args will open new gateway to many interop libraries like OpenCV, Tesseract .. etc

I tried to do this in the def file, but I am receiving CXX template errors

My Def File
--------------
linkerOpts= -ltesseract -std=c++11 -x c++
compilerOpts= -ltesseract -std=c++11 -x c++
headers = tesseract/baseapi.h leptonica/allheaders.h

The Exception
---------------
> Task :cinteropTesseractDemo
Exception in thread "Thread-1" java.lang.IllegalStateException: CXCursor_ClassTemplatePartialSpecialization
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.createStructDef(Indexer.kt:208)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.getStructDeclAt(Indexer.kt:183)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexImpl.indexDeclaration(Indexer.kt:766)
        at

**Comment by Dominaezzz** [comment]
https://github.com/JetBrains/kotlin-native/issues/2835

**Comment by SvyatoslavScherbina** [comment]
No related initiative is in progress.
Closing as answered.
