### ISSUE TITLE
Build Failed Cocoapods Firebase pods

### ISSUE THREAD

**Issue by artemsivcev** [JetBrains/kotlin-native#3588]
Hey there!  I try to add Firebase ML Kit to Multiplatform project. I took an example of cocoapods as a basis but something went wrong when I try to build project with my lib. 
I have this in my Podfile:
`
use_frameworks!

platform :ios, '9.0'

target 'ios_test' do
    pod 'some_lib', :path => '../some_lib'
end
`

and this in my build.gradle.kts

`plugins {
    kotlin("multiplatform") version "1.3.60"
    kotlin("native.cocoapods") version "1.3.60"
}

repositories {
    mavenCentral()
    jcenter()
    maven { setUrl("https://dl.bintray.com/kotlin/kotlin-dev") }
    maven { setUrl("https://dl.bintray.com/kotlin/kotlin-eap") }
}

group = "org.jetbrains.kotlin.sample.native"
version = "1.0"

kotlin {

    // Add a platform switching to have an IDE support.
    val buildForDevice = project.findProperty("kotlin.native.cocoapods.target") == "ios_arm"
    if (buildForDevice) {
        iosArm64("iOS64")
        iosArm32("iOS32")

        val iOSMain by sourceSets.creating
        sourceSets["iOS64Main"].dependsOn(iOSMain)
        sourceSets["iOS32Main"].dependsOn(iOSMain)
    } else {
        iosX64("iOS")
    }

    cocoapods {
        // Configure fields required by CocoaPods.
        summary = "Working with AFNetworking from Kotlin/Native using CocoaPods"
        homepage = "https://github.com/JetBrains/kotlin-native"

        pod("Firebase")
        pod("FirebaseAnalytics")
        pod("FirebaseCore")
        pod("FirebaseCoreDiagnostics")
        pod("FirebaseCoreDiagnosticsInterop")
        pod("FirebaseInstanceID")
        pod("FirebaseMLCommon")
        pod("FirebaseMLVision")
        pod("GoogleAPIClientForREST")
        pod("GoogleAppMeasurement")
        pod("GoogleDataTransportCCTSupport")
        pod("GoogleToolboxForMac")
        pod("GoogleUtilities")
        pod("GTMSessionFetcher")
        pod("nanopb")
        pod("Protobuf")

    }

    jvm("android")

    sourceSets["commonMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
    }

    sourceSets["androidMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib")
    }
}

`

when I try to compile from Xcode, or script (like in example), I achieve only this error:
`> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :generateDefFirebaseAnalytics UP-TO-DATE
> Task :cinteropFirebaseAnalyticsIOS
> Task :generateDefFirebaseCoreDiagnostics UP-TO-DATE

> Task :cinteropFirebaseCoreDiagnosticsIOS FAILED
Exception in thread "main" java.lang.Error: /var/folders/nw/4qwcqz2s79537__d2g5x4t7c0000gn/T/tmp11524627231234724599.m:1:9: fatal error: could not build module 'FirebaseCoreDiagnostics'
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:146)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:359)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:220)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:69)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cinteropFirebaseCoreDiagnosticsIOS'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1`

**Comment by msink** [comment]
> /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk

Did you try oraclejdk11?

**Comment by artdfel** [comment]
Hello @artemsivcev! Can you the status of this issue? Is it still reproducible on 1.3.61 for you?

**Comment by DmyMi** [comment]
> Hi @artdfel! I've solve problem other way

@artemsivcev Hi, can you please share how you solved it?:) got the same problem with Firebase Analytics

**Comment by sergiocasero** [comment]
Hello @artemsivcev @DmyMi, how did you solve the issue?? Because I'm getting same issue now :(

**Comment by DmyMi** [comment]
@sergiocasero Hello, as i had problems with Firebase Analytics i eventually moved the dependency to iOS app and created an interface to invoke it from Kotlin :( i still wonder how to to solve it correctly

**Comment by sergiocasero** [comment]
@DmyMi I've solved it!! The key is `invalidate cache and restart`

1. Add PODs to the `cocoapods` plugin
2. `./gradlew podspec`
3. Go to project folder and `pod install`
4. Build xcode project
5. Intellij: `invalidate cache an restart`
6. You will see the pods on your common code. `import cocoapods.FirebaseAnalytics`

Hope this is helpful for you :)

**Comment by danielocampo2** [comment]
@sergiocasero thanks for sharing, but I keep getting that error - either that or similar ones like the posted below.
This happens when I try to build the iOS App from Xcode. I can succesfully reference FirebaseAnalytics from iOSMain Kotlin code 

I have tried different combinations of pods but always get that error. Could you share your cocoapods plugin block and anything else you may have configured? Thanks a lot in advance.

Btw, I am trying to add Firebase Analytics.

```
> Task :shared:cinteropFirebaseCoreDiagnosticsInteropIOS FAILED
Exception in thread "main" java.lang.Error: /var/folders/qy/lnhfp35s3vjcxkxfj77r85xr0000gn/T/tmp8519378257351541167.m:1:9: fatal error: module 'FirebaseCoreDiagnosticsInterop' not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:446)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:228)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:46)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:44)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:37)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:cinteropFirebaseCoreDiagnosticsInteropIOS'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

My pods look like this:

```
cocoapods {
        // Configure fields required by CocoaPods.
        summary = "Some description for a Kotlin/Native module"
        homepage = "Link to a Kotlin/Native module homepage"

        pod("Firebase")
        pod("FirebaseAnalytics")
        pod("FirebaseCore")
        pod("FirebaseCoreDiagnostics")
        pod("FirebaseCoreDiagnosticsInterop")
        pod("FirebaseInstallations")
        pod("FirebaseInstanceID")
        pod("GoogleAppMeasurement")
        pod("GoogleDataTransport")
        pod("GoogleDataTransportCCTSupport")
        pod("GoogleUtilities")
        pod("PromisesObjC")
        pod("nanopb")
    }
```

**Comment by sergiocasero** [comment]
@danielocampo2 You also need to add the pods to the `podfile`

**Comment by Ornolfr** [comment]
@sergiocasero how did you get import and code completion work for you regarding cocoapods libs? Everything builds fine for me but I get unresolved imports in my iOS-specific kotlin code trying to use classes from pods.

**Comment by danielocampo2** [comment]
@Ornolfr seems that we all are having different type of issues. I can do what you're trying to achieve, and from my testing so far I think you need to:
1) In the cocoapods block in your build.gradle, instead of adding only one pod as it should normally be ("Firebase/Analytics"), add all the pods needed for it to work ("Firebase", "FirebaseCore", etc, refer to my post or original post).
2) as Sergio mentioned, Invalidate Cache and Restart.

@sergiocasero I did that. I tried many different combinations. Adding to the Podfile only the main pods ("Firebase/Analytics"), adding all the different pods, but none of them work. It always throws some kind of module not found error, and it changes if I change this combination. I even tried adding Crashlytics which I need too, and got same error, but with a different module.

@Ornolfr how does your Podfile look like?

Thanks.

**Comment by Ornolfr** [comment]
@danielocampo2 I believe this issue cannot be fixed on developers side. See https://youtrack.jetbrains.com/issue/KT-30581

**Comment by danielocampo2** [comment]
@Ornolfr That seems to make sense, but for me IDE resolves imports correctly and I can actually use the dependencies and have regular autocomplete and stuff. Which is actually what I would expect (or at least expect it to work) after reading to the following documentation:
https://github.com/JetBrains/kotlin-native/blob/master/COCOAPODS.md

Would you care to share your Podfile? 

Guess that if this doesn't work I can always import Firebase manually, and, as you say, at least it generates the ios framework that is quite helpful.

**Comment by artemsivcev** [comment]
@sergiocasero @DmyMi 
This is how I resolve the problem
https://medium.com/swlh/kotlin-multiplatform-ios-frameworks-dependencies-2320ca13ea30

**Comment by Ornolfr** [comment]
@danielocampo2 Here is my `Podfile`:

```
platform :ios, '12.4'

target 'Test' do
  use_frameworks!

  pod 'shared', :path => '../../shared'

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesttUITests' do
    # Pods for testing
  end

end
```

My `build.gradle.kts`:
```
plugins {
    id("com.android.library")
    kotlin("multiplatform")
    kotlin("native.cocoapods")
}

android {
    compileSdkVersion(29)

    defaultConfig {
        minSdkVersion(21)
        targetSdkVersion(29)
    }

    sourceSets.all {
        manifest.srcFile("src/androidMain/AndroidManifest.xml")
        java.srcDirs("src/androidMain/java")
        res.srcDirs("src/androidMain/res")
    }
}

version = "1.0"

kotlin {
    android()
    ios()

    cocoapods {
        // Configure fields required by CocoaPods.
        summary = "..."
        homepage = "..."

        // You can change the name of the produced framework.
        // By default, it is the name of the Gradle project.
        frameworkName = "SharedModule"
    }

    sourceSets["commonMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
    }

    sourceSets["androidMain"].dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib")
    }

    sourceSets.all {
        languageSettings.progressiveMode = true
    }
}
```

**Comment by danielocampo2** [comment]
@Ornolfr thanks, but I see you don't have any external Pods added? I thought you were trying to import Firebase too.

**Comment by danielocampo2** [comment]
I think the problem may be that they have just announced this as a feature for Kotlin 1.4.0-RC (see Kotlin Native section).

https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/ 

Not sure why this is not mentioned in the docs I shared earlier though. I may give it a try later on, but updating Kotlin's version usually comes with a bunch of other issues (coroutines, ktor...)

**Comment by yahyanik** [comment]
Hey guys I have the same issues when importing OpenCV. Any new help in 2021?

My .podfile:
```
target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'OpenCV', '~> 4.3'
end
```


and here is my gradle.build:
```
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    id("com.android.library")
}

version = "1.0"

kotlin {
    android()

    val iosTarget: (String, KotlinNativeTarget.() -> Unit) -> KotlinNativeTarget =
        if (System.getenv("SDK_NAME")?.startsWith("iphoneos") == true)
            ::iosArm64
        else
            ::iosX64

    iosTarget("ios") {}

    cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        ios.deploymentTarget = "14.1"
        frameworkName = "shared"
        podfile = project.file("../iosApp/Podfile")

//        pod("OpenCV"){
//            version= "~> 4.0.0"
//        }
    }
    
    sourceSets {
        val commonMain by getting
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        val androidMain by getting
        val androidTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.13.2")
            }
        }
        val iosMain by getting
        val iosTest by getting
        
    }
}

android {
    compileSdkVersion(30)
    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    defaultConfig {
        minSdkVersion(27)
        targetSdkVersion(30)
    }
}

```

**Comment by artdfel** [comment]
Hello, @yahyanik! Answered at https://youtrack.jetbrains.com/issue/KT-47713.
