### ISSUE TITLE
kotlin.native.BitSet

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3639]
Is `kotlin.native.BitSet` to be compatible with `java.util.BitSet` ?

Tried to use it in common code:
```kotlin
expect class BitSet() {
    operator fun get(index: Int): Boolean
    fun set(index: Int)
    fun clear(index: Int)
    fun or(another: BitSet)
}
```

On JVM - works:
```kotlin
actual typealias BitSet = java.util.BitSet
```

On native - fails:
```kotlin
actual typealias BitSet = kotlin.native.BitSet
```

**Comment by artdfel** [comment]
Hello! Thank you for the report, this probably should not work like that. It seems like there is some problem with default values on the `actual` side of the MPP. [This](https://youtrack.jetbrains.com/issue/KT-28580) issue may be related. Please try to workaround it with something like that:
```
expect class BitSet constructor(size: Int = 64) {
    operator fun get(index: Int): Boolean
    fun set(index: Int, value: Boolean = true)
    fun clear(index: Int)
    fun or(another: BitSet)
}
```

**Comment by msink** [comment]
Your variant crashed:
```
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :compose-runtime
Kotlin Multiplatform Projects are an experimental feature.

> Task :compose-runtime:compileKotlinWindows
e: Compilation failed: public constructor BitSet(size: kotlin.Int = ...) defined in androidx.compose.BitSet[ClassConstructorDescriptorImpl@10be5d15]

 * Source files: Ambient.kt, Applier.kt, Component.kt, Composable.kt, Compose.kt, Composer.kt, CompositionContext.kt, CompositionLifecycleObserver.kt, CompositionReference.kt, Effects.kt, EffectsDsl.kt, Emittable.kt, Expect.kt, FrameManager.kt, HiddenAttribute.kt, Immutable.kt, JoinedKey.kt, Key.kt, KeySourceInfo.kt, Model.kt, Observe.kt, ObserverMap.kt, Pivotal.kt, Recompose.kt, Recomposer.kt, SlotTable.kt, StableMarker.kt, Stack.kt, Trace.kt, UnionType.kt, ViewComposerCommon.kt, Hide.kt, FrameContainers.kt, FrameIdSet.kt, Frames.kt, sourceLocation.kt, ActualAndroid.kt, ActualNative.kt, KeySourceInfo.kt, Recomposer.kt, ViewComposer.kt
 * Compiler version info: Konan: 1.3.60 / Kotlin: 1.3.60
 * Output kind: LIBRARY

e: java.lang.IllegalStateException: public constructor BitSet(size: kotlin.Int = ...) defined in androidx.compose.BitSet[ClassConstructorDescriptorImpl@10be5d15]
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitValueParameter(ExpectDeclarationsRemoving.kt:222)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitValueParameter(IrElementVisitorVoid.kt:78)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitValueParameter(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitValueParameter(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.declarations.impl.IrValueParameterImpl.accept(IrValueParameterImpl.kt:85)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFunctionBase.acceptChildren(IrFunctionBase.kt:65)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:268)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitElement(ExpectDeclarationsRemoving.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitDeclaration(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:46)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitFunction(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructor(IrElementVisitorVoid.kt:52)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitConstructor(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructor(IrElementVisitorVoid.kt:53)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitConstructor(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitConstructor(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.declarations.impl.IrConstructorImpl.accept(IrConstructorImpl.kt:74)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.acceptChildren(IrClassImpl.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:268)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitElement(ExpectDeclarationsRemoving.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitDeclaration(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:43)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitClass(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitClass(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier$copyDefaultArgumentsFromExpectToActual$1.visitClass(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:89)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:264)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier.copyDefaultArgumentsFromExpectToActual(ExpectDeclarationsRemoving.kt:60)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier.process(ExpectDeclarationsRemoving.kt:54)
	at org.jetbrains.kotlin.backend.konan.lower.ExpectToActualDefaultValueCopier.process(ExpectDeclarationsRemoving.kt:47)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$copyDefaultValuesToActualPhase$1.invoke(ToplevelPhases.kt:219)
	at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$copyDefaultValuesToActualPhase$1.invoke(ToplevelPhases.kt)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:115)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:113)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:74)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:225)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:222)
	at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
	at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:224)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :compose-runtime:compileKotlinWindows FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compose-runtime:compileKotlinWindows'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_111\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
1 actionable task: 1 executed
```

**Comment by artdfel** [comment]
Sorry for the problem abandoned for such a long time. Reproduced it again and made a ticket on YouTrack, see https://youtrack.jetbrains.com/issue/KT-42615. Closing this one as a part of YouTrack migration(#4079)
