### ISSUE TITLE
Build errors on OSX

### ISSUE THREAD

**Issue by fjanicki** [JetBrains/kotlin-native#3681]
I am trying to build the project on OSX. I followed the instructions in the readme but I am unable to successfully bundle the project. I have tried off `master` and also from tag `v.1.3.60`, both leading to the same error.

XCode 11 is installed, JDK has been updated to latest version `13.0.1`.

First command `./gradlew dependencies:update` works fine. But then `./gradlew bundle` leads to an error.

I get this:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platformLibs:compileKonanIos_arm32-ARDisplayDeviceIos_arm32'.
> A failure occurred while executing shadow.org.jetbrains.kotlin.gradle.plugin.tasks.KonanInteropTask$RunTool
   > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

Again but with --debug option enabled:
```
14:24:26.589 [ERROR] [system.err] Exception in thread "main" java.lang.Error: /var/folders/ct/x6_54t7d55d1flhj_0ghw45r0000gn/T/tmp8541740169232186446.m:1:9: fatal error: module 'ARDisplayDevice' not found
14:24:26.589 [ERROR] [system.err]       at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:146)
14:24:26.589 [ERROR] [system.err]       at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
14:24:26.589 [ERROR] [system.err]       at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
14:24:26.589 [ERROR] [system.err]       at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:364)
14:24:26.589 [ERROR] [system.err]       at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:219)
14:24:26.590 [ERROR] [system.err]       at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:39)
14:24:26.590 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:71)
14:24:26.590 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)
14:24:26.608 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
```

Any idea on what to do? Thanks!

**Comment by olonho** [comment]
Which version of K/N is that? Current master doesn't have such definition file.

**Comment by fjanicki** [comment]
Actually I think this error was with 1.3.50 tag, which I tried after failing on master. I just re-tried it on `master`

```
 fjanicki@prometheus ~/Development/kotlin-native master git rev-parse HEAD
919db81fba64450aaf86735cfaced4c0dcff2f41
```

This is the error message I am getting:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platformLibs:compileKonanIos_arm32-AccountsIos_arm32'.
> A failure occurred while executing shadow.org.jetbrains.kotlin.gradle.plugin.tasks.KonanInteropTask$RunTool
   > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with non-zero exit value 134

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by olonho** [comment]
Not sure if error above is informative, add `--stacktrace` or `-i`.

**Comment by artdfel** [comment]
Hello, @fjanicki! Can you tell me the status of this problem?

**Comment by SvyatoslavScherbina** [comment]
Got no response, closing.
