### ISSUE TITLE
e: java.lang.AssertionError: Number of arguments should not be less then number of parameters, but: parameters=3, args=2

### ISSUE THREAD

**Issue by algidrus** [JetBrains/kotlin-native#3930]
When I try to use ArgParser for targets linuxX64, macosX64 compilation fails with error:

========= log ==========

> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :compileKotlinLinuxX64
e: Compilation failed: Number of arguments should not be less then number of parameters, but: parameters=3, args=2

 * Source files: converter.kt
 * Compiler version info: Konan: 1.3.61 / Kotlin: 1.3.60
 * Output kind: LIBRARY

e: java.lang.AssertionError: Number of arguments should not be less then number of parameters, but: parameters=3, args=2
        at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:90)
        at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:87)
        at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:97)
        at org.jetbrains.kotlin.types.TypeConstructorSubstitution$Companion.create(TypeSubstitution.kt:79)
        at org.jetbrains.kotlin.types.KotlinTypeFactory.computeMemberScope(KotlinTypeFactory.kt:53)
        at org.jetbrains.kotlin.types.KotlinTypeFactory.simpleType(KotlinTypeFactory.kt:78)
        at org.jetbrains.kotlin.types.KotlinTypeFactory.simpleType$default(KotlinTypeFactory.kt:70)
        at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.simpleType(TypeDeserializer.kt:94)
        at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.type(TypeDeserializer.kt:63)
        at org.jetbrains.kotlin.serialization.deserialization.MemberDeserializer.loadFunction(MemberDeserializer.kt:278)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.computeFunctions(DeserializedMemberScope.kt:101)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.access$computeFunctions(DeserializedMemberScope.kt:40)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(DeserializedMemberScope.kt:66)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(DeserializedMemberScope.kt:40)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:446)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:521)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedFunctions(DeserializedMemberScope.kt:139)
        at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedFunctions(ChainedMemberScope.kt:39)
        at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedFunctions(AbstractScopeAdapter.kt:40)
        at org.jetbrains.kotlin.backend.common.serialization.DescriptorReferenceDeserializer.getContributedDescriptors(DeserializeDescriptorReference.kt:57)
        at org.jetbrains.kotlin.backend.common.serialization.DescriptorReferenceDeserializer.getContributedDescriptors(DeserializeDescriptorReference.kt:46)
        at org.jetbrains.kotlin.backend.common.serialization.DescriptorReferenceDeserializer.deserializeDescriptorReference(DeserializeDescriptorReference.kt:105)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeDescriptorReference(KotlinIrLinker.kt:349)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeIrSymbolData(KotlinIrLinker.kt:326)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeIrSymbol(KotlinIrLinker.kt:365)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeCall(IrFileDeserializer.kt:364)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeOperation(IrFileDeserializer.kt:850)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeExpression(IrFileDeserializer.kt:888)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeStatement(IrFileDeserializer.kt:293)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeBlock(IrFileDeserializer.kt:311)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeOperation(IrFileDeserializer.kt:847)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeExpression(IrFileDeserializer.kt:888)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeTypeOp(IrFileDeserializer.kt:664)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeOperation(IrFileDeserializer.kt:872)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeExpression(IrFileDeserializer.kt:888)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeBranch(IrFileDeserializer.kt:260)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeStatement(IrFileDeserializer.kt:287)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeWhen(IrFileDeserializer.kt:696)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeOperation(IrFileDeserializer.kt:874)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeExpression(IrFileDeserializer.kt:888)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeStatement(IrFileDeserializer.kt:293)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeBlockBody(IrFileDeserializer.kt:251)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeStatement(IrFileDeserializer.kt:285)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeStatementBody(KotlinIrLinker.kt:392)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrFunction(IrFileDeserializer.kt:1451)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1281)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrClass(IrFileDeserializer.kt:991)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1280)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1299)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeDeclaration(KotlinIrLinker.kt:171)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile$deserializeAllFileReachableTopLevel$1.invoke(KotlinIrLinker.kt:408)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile$deserializeAllFileReachableTopLevel$1.invoke(KotlinIrLinker.kt:150)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$DeserializationState$SimpleDeserializationState.processPendingDeclaration(KotlinIrLinker.kt:113)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeAllFileReachableTopLevel(KotlinIrLinker.kt:407)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$deserializeAllModuleReachableTopLevels$1.invoke(KotlinIrLinker.kt:473)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$deserializeAllModuleReachableTopLevels$1.invoke(KotlinIrLinker.kt:132)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$DeserializationState$ModuleDeserializationState.processPendingDeclaration(KotlinIrLinker.kt:90)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer.deserializeAllModuleReachableTopLevels(KotlinIrLinker.kt:471)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.deserializeAllReachableTopLevels(KotlinIrLinker.kt:526)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.findDeserializedDeclarationForDescriptor(KotlinIrLinker.kt:554)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.getDeclaration(KotlinIrLinker.kt:561)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.getDeclaration(DeclarationStubGenerator.kt:64)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.access$getDeclaration(DeclarationStubGenerator.kt:35)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateClassStub$1.invoke(DeclarationStubGenerator.kt:214)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator$generateClassStub$1.invoke(DeclarationStubGenerator.kt:35)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass(SymbolTable.kt:571)
        at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass$default(SymbolTable.kt:238)
        at org.jetbrains.kotlin.ir.util.DeclarationStubGenerator.generateClassStub$ir_tree(DeclarationStubGenerator.kt:213)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:56)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:63)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:82)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:175)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:115)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:27)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:74)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:225)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:222)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:224)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:304)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)

=========== part of application =============

import kotlinx.cinterop.*
import platform.posix.*
import kotlinx.cli.*

@kotlin.ExperimentalStdlibApi
fun main(args: Array<String>)
{
    val argParser = ArgParser("someApp")
}

**Comment by artdfel** [comment]
Thank you for the report! Please extend it with a Gradle script or an exact command you use, because the snippet above does not reproduce the error.

**Comment by algidrus** [comment]
=========== build.gradle.kts ===========

plugins {
    kotlin("multiplatform") version "1.3.61"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven("https://dl.bintray.com/kotlin/ktor")
    maven("https://kotlin.bintray.com/kotlinx")
}

kotlin {
    macosX64().apply {
        compilations["main"].enableEndorsedLibs = true
        binaries {
            executable {
                entryPoint = "com.main"
            }
        }
    }

    linuxX64().apply {
        compilations["main"].enableEndorsedLibs = true
        binaries {
            executable {
                entryPoint = "com.main"
            }
        }
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDirs("./src/main")
            dependencies {
                implementation(kotlin("stdlib-common"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.3.3")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.3.3")                       implementation("org.jetbrains.kotlinx:kotlinx-cli:0.+")
            }
        }
        val commonTest by getting {
            kotlin.srcDirs("./src/tests")
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
    }
}

tasks.compileKotlinMetadata {
    enabled = false
}

**Comment by artdfel** [comment]
Ok, the cause can be determined correctly now. You violate [this](https://github.com/Kotlin/kotlinx.cli#-important-information) rule of the library use. As kotlinx.cli comes to be the first endorsed library, it has two different options:
* it can be either declared as a dependency for some source set or,
* turned on by the enableEndorsedLibs Gradle compilation setting.
As stated above, they should not be mixed. Therefore, you have to choose the only option for your project. 
enableEndorsedLibs option is accessible only for [Kotlin/Native targets](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#supported-platforms), which are listed here. If you plan to use the library for all of the MPP targets(including JVM and JS) the dependency approach should be preferred. 
To avoid duplications, you can enable endorsed libraries for all Native targets like this:
```
targets.withType<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget> { compilations.all { enableEndorsedLibs=true } }
```

**Comment by algidrus** [comment]
Thanks, I've removed this line and project has compiled.
