### ISSUE TITLE
compile error from cocoapods example

### ISSUE THREAD

**Issue by levifan** [JetBrains/kotlin-native#4026]
I tried to upgrade the cocoapods example to base on kotlin_version=1.4-M1, and then added another pod package in build.gradle.kts, 
```
        pod("AFNetworking", "~> 3.2.0")
        pod("WCDB")
```
and then I got compile error listed below,
```
> Task :cinteropWCDBIOS FAILED
Exception in thread "main" java.lang.Error: /var/folders/wf/kj52xnh17czbr_9nxsvjl39r0000gn/T/tmp7201273799338922127.m:1:9: fatal error: could not build module 'WCDB'
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:67)
        at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:13)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:430)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:228)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:46)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:44)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:37)

FAILURE: Build failed with an exception.

```

**Comment by artdfel** [comment]
Hello, @levifan! Your problem here was caused by the fact, that this framework is only Objective-C++ compatible(As I read [on its GH page](https://github.com/Tencent/wcdb#prerequisites)). Currently, Kotlin/Native provides interoperability only with Objective-C, see the details [here](https://kotlinlang.org/docs/reference/native/objc_interop.html).

**Comment by levifan** [comment]
Thanks @artdfel ! Is it any plan Kotlin/native will provides interoperability with C++ or pure swift?

**Comment by artdfel** [comment]
Yes, there are some plans, but, for now, the best option would be finding another framework to use.

**Comment by fenglh** [comment]
> 你好，@ levifan！您的问题是由以下事实引起的：该框架仅与Objective-C ++兼容（正如我[在其GH页面上](https://github.com/Tencent/wcdb#prerequisites)所读）。目前，Kotlin / Native仅提供与Objective-C的互操作性，请参见[此处](https://kotlinlang.org/docs/reference/native/objc_interop.html)的详细信息。

Doesn't framework work either? Even though he was written in swift ？
