### ISSUE TITLE
Compilation error on csvparser sample

### ISSUE THREAD

**Issue by camabeh** [JetBrains/kotlin-native#460]
I get this `build.sh` compilation error on Ubuntu 16.04.

```
/home/camabeh/Git/Download/kotlin-native/dist/dependencies/clang-llvm-3.9.0-linux-x86-64/bin/clang -D_POSIX_SOURCE -isystem /home/camabeh/Git/Download/kotlin-native/dist/dependencies/clang-llvm-3.9.0-linux-x86-64/lib/clang/3.9.0/include --gcc-toolchain=/home/camabeh/Git/Download/kotlin-native/dist/dependencies/target-gcc-toolchain-3-linux-x86-64 -L/home/camabeh/Git/Download/kotlin-native/dist/dependencies/clang-llvm-3.9.0-linux-x86-64/lib -B/home/camabeh/Git/Download/kotlin-native/dist/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/sysroot/../bin --sysroot=/home/camabeh/Git/Download/kotlin-native/dist/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/sysroot  -emit-llvm -c stdio.kt.bc-build/natives/cstubs.c -o stdio.kt.bc-build/natives/cstubs.bc
clang-3.9: warning: argument unused during compilation: '-L/home/camabeh/Git/Download/kotlin-native/dist/dependencies/clang-llvm-3.9.0-linux-x86-64/lib'
stdio.kt.bc-build/natives/cstubs.c:37:63: error: expected expression
    return (int32_t) (_IO_ftrylockfile((struct _IO_FILE*)arg0));
                                                              ^
1 error generated.
Exception in thread "main" java.lang.Error: Process finished with non-zero exit code: 1
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.runExpectingSuccess(main.kt:106)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.runCmd(main.kt:152)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processLib(main.kt:392)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.main(main.kt:37)

```

**Comment by olonho** [comment]
Use excludedFunctions list (for example, see https://github.com/JetBrains/kotlin-native/blob/master/samples/tetris/sdl.def) as a workaround. 
Problem comes from corner case in C headers current cinterop tool cannot cope with.

**Comment by camabeh** [comment]
Thanks, it worked.
