### ISSUE TITLE
kotlinc lists iphone_sim target, but can't download dependencies.

### ISSUE THREAD

**Issue by petmac** [JetBrains/kotlin-native#486]
I know https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md#supported-platforms doesn't list the iPhone simulator, but it is listed when running:
```
kotlinc -list_targets
```
Output as follows:
```
iphone:                                 
iphone_sim:                             
macbook:                      (default) 
```
When I enter the command:
```
kotlinc -output hello -target iphone_sim hello.kt
```
I see the following output:
```
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.

Download dependency: http://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-ios-sim.tar.gz (0 bytes/-). Done.
Exception in thread "main" java.lang.IllegalStateException: Cannot download dependencies.
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.maybeExecuteHelper(K2Native.kt:47)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.access$maybeExecuteHelper(K2Native.kt:1)
	at org.jetbrains.kotlin.cli.bc.K2Native.setupPlatformSpecificArgumentsAndServices(K2Native.kt:147)
	at org.jetbrains.kotlin.cli.bc.K2Native.setupPlatformSpecificArgumentsAndServices(K2Native.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:166)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:137)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:64)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMainNoExit(CLICompiler.java:403)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMain(CLICompiler.java:387)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:157)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:154)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:28)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:156)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:162)
Caused by: java.lang.RuntimeException: Cannot download dependency: http://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-ios-sim.tar.gz
	at org.jetbrains.kotlin.konan.DependencyDownloader.download(DependencyDownloader.kt:152)
	at org.jetbrains.kotlin.konan.DependencyDownloader.processDependency(DependencyDownloader.kt:80)
	at org.jetbrains.kotlin.konan.DependencyDownloader.run(DependencyDownloader.kt:164)
	at org.jetbrains.kotlin.konan.Helper0.run(Helper0.kt:31)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.maybeExecuteHelper(K2Native.kt:43)
	... 14 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://download-cf.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-ios-sim.tar.gz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at org.jetbrains.kotlin.konan.DependencyDownloader$download$1.invoke(DependencyDownloader.kt:127)
	at org.jetbrains.kotlin.konan.DependencyDownloader$download$1.invoke(DependencyDownloader.kt:27)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by olonho** [comment]
Simulator is not yet supported. See documentation.
