### ISSUE TITLE
 Undefined reference to 'kfun:main(kotlin.Array<kotlin.String>)'

### ISSUE THREAD

**Issue by jiamo** [JetBrains/kotlin-native#619]
```
#  ./gradlew dependencies:update
#  ./gradlew -Pshims=true dist 
#  cat Hello.kt

package hello

fun getHelloString() : String {
    return "Hello, world!"
}

fun main(args : Array<String>) {
    println(getHelloString())
}


#  kotlinc Hello.kt -o hello

/tmp/combined777855394143824836.o:ld-temp.o:function Konan_start: error: undefined reference to 'kfun:main(kotlin.Array<kotlin.String>)'
exception: java.lang.IllegalStateException: The /home/jiamo/develop/kotlin-native/dist/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/bin/ld.gold command returned non-zero exit code: 1.
	at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:268)
	at org.jetbrains.kotlin.backend.konan.LinkStage.link(LinkStage.kt:239)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$3.invoke(LinkStage.kt:290)
	at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$3.invoke(LinkStage.kt:162)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:125)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:104)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:124)
	at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:289)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:122)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:125)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:104)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:124)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:121)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:68)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:182)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:130)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMainNoExit(CLICompiler.java:383)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMain(CLICompiler.java:373)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:165)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:28)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:167)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)

```

**Comment by alexander-gorshenev** [comment]
The main() function in a package other than the default one is not supported yet.

**Comment by vvlevchenko** [comment]
#628

**Comment by olonho** [comment]
It is supported now.
