### ISSUE TITLE
Problem when compiling the Android activity sample

### ISSUE THREAD

**Issue by RomainPiel** [JetBrains/kotlin-native#752]
When I try to compile the [Android activity sample](https://github.com/JetBrains/kotlin-native/tree/master/samples/androidNativeActivity) using `ANDROID_HOME=... ../gradlew buildApk`, I get:

```
...
:compileArm32InteropStubs
KtFile: android.kt
exception: java.lang.Error: No such file or directory
        at org.jetbrains.kotlin.backend.konan.llvm.LlvmUtilsKt.parseBitcodeFile(LlvmUtils.kt:243)
        at org.jetbrains.kotlin.backend.konan.llvm.Runtime.<init>(Runtime.kt:30)
        at org.jetbrains.kotlin.backend.konan.llvm.Llvm.<init>(ContextUtils.kt:238)
        at org.jetbrains.kotlin.backend.konan.Context.setLlvmModule(Context.kt:204)
        at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.emitLLVM(IrToBitcode.kt:62)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt:111)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4$2.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:128)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:107)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:127)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:110)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:128)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:107)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:127)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:104)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:69)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:56)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:93)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:46)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:154)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:145)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:169)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:166)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:28)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:168)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:174)

:compileArm32InteropStubs FAILED
```

Any idea how to fix that?

**Comment by olonho** [comment]
Romain, could you please provide more information about your configuration (host OS, Android SDK, etc) and error context. Otherwise it's pretty hard to understand reasons of probelm you've got. 
Did you use git checkout or v0.3 binary distributable?

**Comment by RomainPiel** [comment]
Oh yeah sorry. I'm running macOS Sierra, The build tools of my Android SDK are on 26.0.0 and I've checked out from master. Should I check with 0.3 instead?

**Comment by olonho** [comment]
Yes, please try v0.3. Also, when running master, make sure you did ./gradlew cross_dist before building sample.

**Comment by olonho** [comment]
Does it work now?

**Comment by RomainPiel** [comment]
Sorry about the late reply. yeah it's all good now, thanks!
