### ISSUE TITLE
Can't build sample/uikit app

### ISSUE THREAD

**Issue by Orgmir** [JetBrains/kotlin-native#972]
I'm trying to compile and run the konan uikit sample app but it seems I'm missing something.

I'm just hitting Run on XCode, and there's a shell script invocation error:

```
KtFile: main.kt
src/main/kotlin/main.kt:2:8: error: unresolved reference: platform
import platform.Foundation.*
       ^
src/main/kotlin/main.kt:3:8: error: unresolved reference: platform
import platform.UIKit.*
       ^
src/main/kotlin/main.kt:11:13: error: unresolved reference: UIApplicationMain
            UIApplicationMain(argc, argv, null, NSStringFromClass(AppDelegate))
            ^
src/main/kotlin/main.kt:11:49: error: unresolved reference: NSStringFromClass
            UIApplicationMain(argc, argv, null, NSStringFromClass(AppDelegate))
                                                ^
src/main/kotlin/main.kt:16:21: error: unresolved reference: UIResponder
class AppDelegate : UIResponder(), UIApplicationDelegateProtocol {
                    ^
src/main/kotlin/main.kt:16:36: error: unresolved reference: UIApplicationDelegateProtocol
class AppDelegate : UIResponder(), UIApplicationDelegateProtocol {
                                   ^
src/main/kotlin/main.kt:17:24: error: unresolved reference: UIResponderMeta
    companion object : UIResponderMeta(), UIApplicationDelegateProtocolMeta {}
                       ^
src/main/kotlin/main.kt:17:43: error: unresolved reference: UIApplicationDelegateProtocolMeta
    companion object : UIResponderMeta(), UIApplicationDelegateProtocolMeta {}
                                          ^
src/main/kotlin/main.kt:19:5: error: 'init' overrides nothing
    override fun init() = initBy(AppDelegate())
    ^
src/main/kotlin/main.kt:19:27: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
@Intrinsic public external fun <T : ObjCObjectBase> ???.initBy(constructorCall: ???): ??? defined in kotlinx.cinterop
    override fun init() = initBy(AppDelegate())
                          ^
src/main/kotlin/main.kt:21:26: error: unresolved reference: UIWindow
    private var _window: UIWindow? = null
                         ^
src/main/kotlin/main.kt:22:5: error: 'window' overrides nothing
    override fun window() = _window
    ^
src/main/kotlin/main.kt:23:5: error: 'setWindow' overrides nothing
    override fun setWindow(window: UIWindow?) { _window = window }
    ^
src/main/kotlin/main.kt:23:36: error: unresolved reference: UIWindow
    override fun setWindow(window: UIWindow?) { _window = window }
                                   ^
src/main/kotlin/main.kt:27:24: error: unresolved reference: UIViewController
class ViewController : UIViewController {
                       ^
src/main/kotlin/main.kt:29:27: error: unresolved reference: NSCoder
    constructor(aDecoder: NSCoder) : super(aDecoder)
                          ^
src/main/kotlin/main.kt:29:44: error: too many arguments for public constructor Any() defined in kotlin.Any
    constructor(aDecoder: NSCoder) : super(aDecoder)
                                           ^
src/main/kotlin/main.kt:30:5: error: 'initWithCoder' overrides nothing
    override fun initWithCoder(aDecoder: NSCoder) = initBy(ViewController(aDecoder))
    ^
src/main/kotlin/main.kt:30:42: error: unresolved reference: NSCoder
    override fun initWithCoder(aDecoder: NSCoder) = initBy(ViewController(aDecoder))
                                         ^
src/main/kotlin/main.kt:30:53: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
@Intrinsic public external fun <T : ObjCObjectBase> ???.initBy(constructorCall: ???): ??? defined in kotlinx.cinterop
    override fun initWithCoder(aDecoder: NSCoder) = initBy(ViewController(aDecoder))
                                                    ^
src/main/kotlin/main.kt:33:25: error: unresolved reference: UILabel
    lateinit var label: UILabel
                        ^
src/main/kotlin/main.kt:36:29: error: unresolved reference: UITextField
    lateinit var textField: UITextField
                            ^
src/main/kotlin/main.kt:39:26: error: unresolved reference: UIButton
    lateinit var button: UIButton
```

From all the unresolved references, it seems to me that I don't have the required interop definitions. I've created a `objc.def` file:

```
headers = Foundation/Foundation.h UIKit/UIKit.h
headerFilter = Foundation/** UIKit/**

language = Objective-C
linkerOpts = -framework Foundation -framework UIKit
```

And tried to run it, but I don't really get what I'm doing wrong

```
$ pwd
/Users/me/kotlin-native/samples/uikit
$ ../../dist/bin/cinterop -def src/main/objc_interop/objc.def
Exception in thread "main" java.lang.Error: /var/folders/l2/9xx8z6qn5335_2pgyjn89wlm0000gn/T/tmp8175739025378838971.m:2:10: fatal error: 'UIKit/UIKit.h' file not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:135)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:875)
	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:865)
	at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:55)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processLib(main.kt:317)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:33)
	at org.jetbrains.kotlin.cli.utilities.MainKt.invokeCinterop(main.kt:90)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:112)
```

I've search the web/docs but couldn't find any solution. Where do I run cinterop? Is my `objc.def` file correct? Is this even the issue or am I not linking required files?

**Comment by olonho** [comment]
See https://github.com/JetBrains/kotlin-native/issues/974

**Comment by Orgmir** [comment]
@olonho Thank you. I've run `./gradlew distPlatformLibs` on the root of the project and it built fine. But the uikit example still reports the same errors. I've tried running the same command on the samples folder, but the task doesn't exist. Do I need to copy some files over to the sample project for it to work?

**Comment by SvyatoslavScherbina** [comment]
Try to run `./gradlew iphonePlatformLibs` in the root of the project, and then build the sample again.

**Comment by olonho** [comment]
Does it work now?

**Comment by olonho** [comment]
Closing, reopen if still an issue
